### ISSUE TITLE
'rvm repair all' fails when building wrappers

### ISSUE THREAD

**Issue by andersennl** [rvm/rvm#2734]
Hi, I just tried to install ruby v 2.1.0 and use it as default via rvm. The installation worked well but when I type `rvm --default use 2.1.0`, I get this warning:

```
Warning! PATH is not properly set up, '/Users/linus/.rvm/gems/ruby-2.1.0/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.1.0'.
Using /Users/linus/.rvm/gems/ruby-2.1.0

```

So I ran `rvm get stable --auto-dotfiles` which worked. Well, I got this warning:

```
Upgrade Notes:


  * WARNING: You have '~/.profile' file, you might want to load it,
    to do that add the following line to '/Users/linusandersen/.bash_profile':

      source ~/.profile
```

Side note: as I'm a complete beginner on this topic, what exactly does this warning mean and what exactly should I do?

Next I tried to run `irb` and got this error:

```
/Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    /Users/linus/.rvm/rubies/ruby-2.1.0/bin/ruby extconf.rb 
checking for main() in -lpthread... yes
checking for main() in -lobjc... yes
checking for v8.h... no
/Users/linus/.rvm/gems/ruby-2.1.0/gems/libv8-3.16.14.3/ext/libv8/location.rb:50:in `configure': You have chosen to use the version of V8 found on your system (Libv8::Location::System::NotFoundError)
and *not* the one that is bundle with the libv8 rubygem. However,
it could not be located. please make sure you have a version of
v8 that is compatible with 3.16.14.3 installed. You may
need to special --with-v8-dir options if it is in a non-standard
location

thanks,
The Mgmt

    from /Users/linus/.rvm/gems/ruby-2.1.0/gems/libv8-3.16.14.3/lib/libv8.rb:7:in `configure_makefile'
    from extconf.rb:32:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/linus/.rvm/gems/ruby-2.1.0/gems/therubyracer-0.12.0 for inspection.
Results logged to /Users/linus/.rvm/gems/ruby-2.1.0/extensions/x86_64-darwin-12/2.1.0-static/therubyracer-0.12.0/gem_make.out
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:38:in `block in build'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tempfile.rb:324:in `open'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/ext_conf_builder.rb:17:in `build'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:160:in `chdir'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:160:in `block in build_extension'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:159:in `synchronize'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:159:in `build_extension'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1436:in `block in build_extensions'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/user_interaction.rb:45:in `use_ui'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1434:in `build_extensions'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:924:in `each'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:924:in `find'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:924:in `find_inactive_by_path'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems.rb:185:in `try_activate'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/locale.rb:150:in `block in search_file'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/locale.rb:158:in `block in each_localized_path'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/locale.rb:167:in `each_sublocale'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/locale.rb:157:in `each_localized_path'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/locale.rb:145:in `search_file'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/locale.rb:124:in `find'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/locale.rb:108:in `load'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/locale.rb:32:in `initialize'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/init.rb:114:in `new'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/init.rb:114:in `init_config'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb/init.rb:16:in `setup'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/irb.rb:380:in `start'
    from /Users/linus/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'
```

I googled and found the tip to run `rvm repair all` which showed me this:

```
Repairing symlinks...
Symlinks repaired
Repairing archives...
Archives repaired
Regenerating environments...
Environments regenerated
Regenerating all wrappers...
Regenerating wrappers for ruby-1.9.2-p320..................................................................
Regenerating wrappers for ruby-1.9.2-p320@global...................................................................
Regenerating wrappers for ruby-1.9.3-p0....................................................................
Regenerating wrappers for ruby-1.9.3-p0@global....................................................................
Regenerating wrappers for ruby-1.9.3-p392..................................................................
Regenerating wrappers for ruby-1.9.3-p392@global...................................................................
Regenerating wrappers for ruby-1.9.3-p448..................................................................
Regenerating wrappers for ruby-1.9.3-p448@global...................................................................
Regenerating wrappers for ruby-2.0.0-p0....................................................................
Regenerating wrappers for ruby-2.0.0-p0@global....................................................................
Regenerating wrappers for ruby-2.0.0-p247..................................................................
Regenerating wrappers for ruby-2.0.0-p247@global...................................................................
Regenerating wrappers for ruby-2.0.0-p353.................................................................^CError running '__rvm_with ruby-2.0.0-p353 run_gem_wrappers_regenerate',
showing last 15 lines of /Users/linus/.rvm/log/1395655716/wrappers.regenerate.ruby-2.0.0-p353.log
+ gem_spec+=', '\''>=1.2.4'\'''
+ version_check=1.2.4
+ ls -ld /Users/linus/.rvm/gems/ruby-2.0.0-p353/gems/gem-wrappers-1.2.4
+ /Users/linus/.rvm/rubies/ruby-2.0.0-p353/bin/ruby -rrubygems -e 'gem '\''gem-wrappers'\'', '\''>=1.2.4'\'''
+ rvm_log 'gem gem-wrappers >=1.2.4 is already installed'
+ rvm_pretty_print stdout
+ case "${rvm_pretty_print_flag:=auto}" in
+ case "${TERM:-dumb}" in
+ case "$1" in
+ [[ -t 1 ]]
+ return 1
+ printf %b 'gem gem-wrappers >=1.2.4 is already installed\n'
gem gem-wrappers >=1.2.4 is already installed
+ return 0
+ gem wrappers regenerate

Regenerating wrappers for ruby-2.0.0-p353@global...................................................................
Regenerating wrappers for ruby-2.0.0-p353@rails_app...................................................................
Regenerating wrappers for ruby-2.1.0.....................................................................
Error running '__rvm_with ruby-2.1.0 run_gem_wrappers_regenerate',
showing last 15 lines of /Users/linus/.rvm/log/1395655716/wrappers.regenerate.ruby-2.1.0.log

thanks,
The Mgmt

    from /Users/linus/.rvm/gems/ruby-2.1.0/gems/libv8-3.16.14.3/lib/libv8.rb:7:in `configure_makefile'
    from extconf.rb:32:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/linus/.rvm/gems/ruby-2.1.0/gems/therubyracer-0.12.0 for inspection.
Results logged to /Users/linus/.rvm/gems/ruby-2.1.0/extensions/x86_64-darwin-12/2.1.0-static/therubyracer-0.12.0/gem_make.out
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
+ return 1
+ return 1
Regenerating wrappers for ruby-2.1.0@global..................................................................
Wrappers regeneration failed for:  

```

Help is highly appreciated. Thanks!

**Comment by Hamzabutt1401** [comment]
help needed.
i run two file on a single server.
my new application take the wrapper of old application instead of there can you please help me out in this
