### ISSUE TITLE
Unable to install rbx 2.2.10 on arch linux 

### ISSUE THREAD

**Issue by mijoharas** [rvm/rvm#2942]
Error is here:

```
$ rvm install rbx
Searching for binary rubies, this might take some time.
No binary rubies available for: arch/libc-2.19/x86_64/rbx-2.2.10.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for arch.
Requirements installation successful.
ruby-2.1.2@rubinius - #regenerating binstubs - please wait
rbx-2.2.10 - #downloading rubinius-2.2.10, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.8M  100 10.8M    0     0  1424k      0  0:00:07  0:00:07 --:--:-- 1772k
rbx-2.2.10 - #extracting rubinius-2.2.10 to /home/michael/.rvm/src/rbx-2.2.10 - please wait
ruby-2.1.2@rubinius - #bundle install - please wait
rbx-2.2.10 - #configuring - please wait
rbx-2.2.10 - #compiling - please wait
Error running '/home/michael/.rvm/wrappers/ruby-2.1.2@rubinius/rake install --trace',
showing last 15 lines of /home/michael/.rvm/log/1405006146_rbx-2.2.10/rake.log
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/bin/rake:23:in `load'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/bin/rake:23:in `<main>'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/bin/ruby_executable_hooks:15:in `eval'
/home/michael/.rvm/gems/ruby-2.1.2@rubinius/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => install => build:build => build:llvm
```

Here are my settings:

```
$  rvm info

rbx-2.2.1:

  system:
    uname:       "Linux michael-work 3.15.1-1-ARCH #1 SMP PREEMPT Tue Jun 17 09:32:20 CEST 2014 x86_64 GNU/Linux"
    system:      "arch/libc-2.19/x86_64"
    bash:        "/usr/bin/bash => GNU bash, version 4.3.18(1)-release (x86_64-unknown-linux-gnu)"
    zsh:         "/usr/bin/zsh => zsh 5.0.5 (x86_64-unknown-linux-gnu)"

  rvm:
    version:      "rvm 1.25.28 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "20 minutes 30 seconds ago"
    path:         "/home/michael/.rvm"

  ruby:
    interpreter:  "rubinius"
    version:      "2.2.1"
    date:         "rubinius 2.2.1 (2.1.0 3ed43137 2013-11-17 JI) [x86_64-linux-gnu]"
    platform:     "x86_64-linux-gnu"
    patchlevel:   "2.1.0 3ed43137 2013-11-17 JI"
    full_version: "rubinius 2.2.1 (2.1.0 3ed43137 2013-11-17 JI) [x86_64-linux-gnu]"

  homes:
    gem:          "/home/michael/.rvm/gems/rbx-2.2.1"
    ruby:         "/home/michael/.rvm/rubies/rbx-2.2.1"

  binaries:
    ruby:         "/home/michael/.rvm/rubies/rbx-2.2.1/bin/ruby"
    irb:          "/home/michael/.rvm/gems/rbx-2.2.1@global/bin/irb"
    gem:          "/home/michael/.rvm/rubies/rbx-2.2.1/bin/gem"
    rake:         "/home/michael/.rvm/gems/rbx-2.2.1@global/bin/rake"

  environment:
    PATH:         "/home/michael/.rvm/gems/rbx-2.2.1/bin:/home/michael/.rvm/gems/rbx-2.2.1@global/bin:/home/michael/.rvm/rubies/rbx-2.2.1/bin:/home/michael/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/core_perl:/home/michael/scripts"
    GEM_HOME:     "/home/michael/.rvm/gems/rbx-2.2.1"
    GEM_PATH:     "/home/michael/.rvm/gems/rbx-2.2.1:/home/michael/.rvm/gems/rbx-2.2.1@global"
    MY_RUBY_HOME: "/home/michael/.rvm/rubies/rbx-2.2.1"
    IRBRC:        "/home/michael/.rvm/rubies/rbx-2.2.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

I am easily able to install other rubies and absolutely everything else works fine. Rubinius used to be able to be installed a while ago (last version is 2.2.1).

**Comment by andrewfader** [comment]
This should change to point to llvm35 and clang35 for rbx 2.5 because 3.6 is too new.

**Comment by mpapis** [comment]
@andrewfader please open a new ticket with details
