### ISSUE TITLE
rbx-2.5.2 fails with 'Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)'

### ISSUE THREAD

**Issue by ileitch** [rvm/rvm#3293]
``` sh
➜  ~  ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
➜  ~  rvm list

rvm rubies

   jruby-1.7.16 [ x86_64 ]
   jruby-1.7.18 [ x86_64 ]
   rbx-2.4.1 [ x86_64 ]
   rbx-2.5.0 [ x86_64 ]
   ruby-2.0.0-p598 [ x86_64 ]
   ruby-2.1.1 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
=* ruby-2.2.0 [ x86_64 ]

➜  ~  rvm use 2.2.0@global
Using /Users/ian/.rvm/gems/ruby-2.2.0 with gemset global
➜  ~  gem list

*** LOCAL GEMS ***

bigdecimal (1.2.6)
bundler (1.7.10)
bundler-unload (1.0.2)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
test-unit (3.0.8)
```

**Configure log**

``` sh
➜  ~  cat /Users/ian/.rvm/log/1423090103_rbx-2.5.2/configure.log
Checking /usr/bin/clang: found
Checking g++: found
Checking bison: found

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/spec_set.rb:85:in `map!'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/spec_set.rb:85:in `materialize'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/definition.rb:132:in `specs'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/definition.rb:177:in `specs_for'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/definition.rb:166:in `requested_specs'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/environment.rb:18:in `requested_specs'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/runtime.rb:13:in `setup'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler.rb:122:in `setup'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/setup.rb:17:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
not found
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
```

**Full output**

``` sh
➜  ~  rvm --debug reinstall rbx-2.5.2
rbx-2.5.2 - reinstall
rbx-2.5.2 - #already removed src/rbx-2.5.2
rbx-2.5.2 - #already removed rubies/rbx-2.5.2
rbx-2.5.2 - #already removed src/rbx-2.5.2
rbx-2.5.2 - #already removed rubies/rbx-2.5.2
Searching for binary rubies, this might take some time.
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/rubinius-2.5.2.tar.bz2
Remote file does not exist http://binaries.rubini.us/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
Remote file does not exist https://rubies.travis-ci.org/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
rvm_remote_server_url4 not found
No remote file name found
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/rubinius-2.5.2.tar.bz2
Remote file does not exist http://binaries.rubini.us/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
Remote file does not exist https://rubies.travis-ci.org/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
rvm_remote_server_url4 not found
No remote file name found
No binary rubies available for: osx/10.10/x86_64/rbx-2.5.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Free disk space 195293MB, required 770MB.
__rvm_setup_compile_environment_setup rbx-2.5.2
rvm_autolibs_flag=4
__rvm_setup_compile_environment_movable_early rbx-2.5.2
__rvm_setup_compile_environment_system_early rbx-2.5.2
__rvm_setup_compile_environment_requirements rbx-2.5.2
Checking requirements for osx.
requirements code for osx loaded
requirements lib type set to osx_brew
brew seems to be writable
Found required packages: autoconf, automake, libtool, pkg-config, libyaml, readline, libksba, openssl.
PATH=/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/ian/.rvm/gems/ruby-2.2.0@global/bin:/Users/ian/.rvm/rubies/ruby-2.2.0/bin:/Users/ian/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/libyaml )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/readline )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/libksba )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/openssl )
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
__rvm_setup_compile_environment_movable rbx-2.5.2
__rvm_setup_compile_environment_parse_name rbx-2.5.2
__rvm_setup_compile_environment_system rbx-2.5.2
__rvm_setup_compile_environment_architectures rbx-2.5.2
rvm_architectures(0):.
__rvm_setup_compile_environment_gcc47plus rbx-2.5.2
__rvm_setup_compile_environment_bison rbx-2.5.2
__rvm_setup_compile_environment_flags_docs rbx-2.5.2
__rvm_setup_compile_environment_flags_shared_static rbx-2.5.2
__rvm_setup_compile_environment_flags_threads rbx-2.5.2
__rvm_setup_compile_environment_compatibility_flag rbx-2.5.2
found compiler: /usr/bin/clang
Running /Users/ian/.rvm/hooks/after_use_maglev
Log prefix: /Users/ian/.rvm/log/1423090097_ruby-2.2.0/
Log filesystem: local,
Log max name length: 250
Log file: /Users/ian/.rvm/log/1423090097_ruby-2.2.0/regenerate_binstubs.log
[2015-02-04 14:48:17] rubinius_install_regenerate_binstubs
rubinius_install_regenerate_binstubs () {
    gem_install executable-hooks && gem regenerate_binstubs || return $?
}
current path: /Users/ian
PATH=/Users/ian/.rvm/gems/ruby-2.2.0@rubinius/bin:/Users/ian/.rvm/gems/ruby-2.2.0@global/bin:/Users/ian/.rvm/rubies/ruby-2.2.0/bin:/Users/ian/.rvm/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
GEM_HOME=/Users/ian/.rvm/gems/ruby-2.2.0@rubinius
GEM_PATH=/Users/ian/.rvm/gems/ruby-2.2.0@rubinius:/Users/ian/.rvm/gems/ruby-2.2.0@global
command(1): rubinius_install_regenerate_binstubs
ruby-2.2.0@rubinius - #regenerating binstubs - please wait
rbx-2.5.2 - #downloading rubinius-2.5.2, this may take a while depending on your connection...
fetch http://releases.rubini.us/rubinius-2.5.2.tar.bz2 => rubinius-2.5.2.tar.bz2
No archive, downloading
Running(19): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 --create-dirs -C - -o rubinius-2.5.2.tar.bz2.part http://releases.rubini.us/rubinius-2.5.2.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.1M  100 11.1M    0     0  2319k      0  0:00:04  0:00:04 --:--:-- 2522k
No checksum for downloaded archive, recording checksum in user configuration.
Log prefix: /Users/ian/.rvm/log/1423090103_rbx-2.5.2/
Log filesystem: local,
Log max name length: 250
Log file: /Users/ian/.rvm/log/1423090103_rbx-2.5.2/extract.log
[2015-02-04 14:48:23] __rvm_package_extract
__rvm_package_extract () {
    rvm_debug __rvm_package_extract:$#: "$@"
    \typeset __tempdir __path __file __return
    __return=0
    __tempdir="$( TMPDIR="${rvm_tmp_path}" mktemp -d -t rvm-tmp.XXXXXXXXX )"
    __rvm_package_extract_run "$1" "$__tempdir" || __return=$?
    if (( __return == 0 ))
    then
        for __path in "$__tempdir"/*
        do
            __file="${__path##*/}"
            if [[ -n "${__file}" && -e "$2/${__file}" ]]
            then
                \command \rm -rf "$2/${__file}" || __return=$?
            fi
            \command \mv -f "${__path}" "$2/" || __return=$?
        done
    fi
    if [[ -n "$__tempdir" ]]
    then
        \command \rm -rf "$__tempdir"
    fi
    return $__return
}
current path: /Users/ian
PATH=/Users/ian/.rvm/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
command(3): __rvm_package_extract /Users/ian/.rvm/archives/rubinius-2.5.2.tar.bz2 /Users/ian/.rvm/tmp/rvm_src_52065
rbx-2.5.2 - #extracting rubinius-2.5.2 to /Users/ian/.rvm/src/rbx-2.5.2 - please wait
__rvm_rm_rf already gone: /Users/ian/.rvm/src/rbx-2.5.2
Patch name 'optional', expanded_name(s) ''.
Patch name 'default', expanded_name(s) ''.
Patch name 'osx', expanded_name(s) ''.
All found patches(0): .
Log file: /Users/ian/.rvm/log/1423090103_rbx-2.5.2/bundle.log
[2015-02-04 14:48:27] /Users/ian/.rvm/wrappers/ruby-2.2.0@rubinius/bundle
current path: /Users/ian/.rvm/src/rbx-2.5.2
PATH=/Users/ian/.rvm/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
command(2): /Users/ian/.rvm/wrappers/ruby-2.2.0@rubinius/bundle install
ruby-2.2.0@rubinius - #bundle install - please wait
Log file: /Users/ian/.rvm/log/1423090103_rbx-2.5.2/configure.log
[2015-02-04 14:48:27] env
current path: /Users/ian/.rvm/src/rbx-2.5.2
PATH=/Users/ian/.rvm/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
command(8): env /Users/ian/.rvm/wrappers/ruby-2.2.0@rubinius/ruby ./configure --prefix=/Users/ian/.rvm/rubies/rbx-2.5.2 --with-opt-dir=/usr/local/opt/libyaml --with-opt-dir=/usr/local/opt/readline --with-opt-dir=/usr/local/opt/libksba --with-opt-dir=/usr/local/opt/openssl
rbx-2.5.2 - #configuring - please wait
Error running 'env /Users/ian/.rvm/wrappers/ruby-2.2.0@rubinius/ruby ./configure --prefix=/Users/ian/.rvm/rubies/rbx-2.5.2 --with-opt-dir=/usr/local/opt/libyaml --with-opt-dir=/usr/local/opt/readline --with-opt-dir=/usr/local/opt/libksba --with-opt-dir=/usr/local/opt/openssl',
showing last 15 lines of /Users/ian/.rvm/log/1423090103_rbx-2.5.2/configure.log
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/spec_set.rb:85:in `map!'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/spec_set.rb:85:in `materialize'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/definition.rb:132:in `specs'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/definition.rb:177:in `specs_for'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/definition.rb:166:in `requested_specs'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/environment.rb:18:in `requested_specs'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/runtime.rb:13:in `setup'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler.rb:122:in `setup'
    from /Users/ian/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/setup.rb:17:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
not found
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
__rvm_rm_rf already gone: /Users/ian/.rvm/tmp/52065*
```

**Comment by rys** [comment]
It's because llvm-config is missing. I guess we solve this the same way ruby-install does, by getting llvm from homebrew and using its llvm-config using configure params. I'll work on a patch.

**Comment by Envek** [comment]
`rvm @global do gem install rake -v '10.4.2'` helped me, rake just wasn't installed in global gemset.

Meanwhile I also have played with installing llvm from brew and trying to provide `--with-opt-dir` option to `rvm install`, but with no luck.

**Comment by cannikin** [comment]
I'm running into the same thing while doing the install with ruby-install. And I *do* have rake 10.4.2 installed.

```
Checking for 'llvm-config': /Users/rob/.gem/ruby/2.2.2/gems/bundler-1.9.4/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)
	from /Users/rob/.gem/ruby/2.2.2/gems/bundler-1.9.4/lib/bundler/spec_set.rb:85:in `map!'
	from /Users/rob/.gem/ruby/2.2.2/gems/bundler-1.9.4/lib/bundler/spec_set.rb:85:in `materialize'
	from /Users/rob/.gem/ruby/2.2.2/gems/bundler-1.9.4/lib/bundler/definition.rb:132:in `specs'
	from /Users/rob/.gem/ruby/2.2.2/gems/bundler-1.9.4/lib/bundler/definition.rb:177:in `specs_for'
	from /Users/rob/.gem/ruby/2.2.2/gems/bundler-1.9.4/lib/bundler/definition.rb:166:in `requested_specs'
	from /Users/rob/.gem/ruby/2.2.2/gems/bundler-1.9.4/lib/bundler/environment.rb:18:in `requested_specs'
	from /Users/rob/.gem/ruby/2.2.2/gems/bundler-1.9.4/lib/bundler/runtime.rb:13:in `setup'
	from /Users/rob/.gem/ruby/2.2.2/gems/bundler-1.9.4/lib/bundler.rb:122:in `setup'
	from /Users/rob/.gem/ruby/2.2.2/gems/bundler-1.9.4/lib/bundler/setup.rb:18:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
not found
ABORT: unable to set up LLVM
```

```
*** LOCAL GEMS ***

activemodel (4.2.1)
activerecord (4.2.1)
activesupport (4.2.1)
arel (6.0.0)
axiom-types (0.1.1)
bigdecimal (1.2.6)
builder (3.2.2)
bundler (1.9.4)
byebug (4.0.5)
celluloid (0.16.0)
coderay (1.1.0)
coercible (1.0.0)
columnize (0.9.0)
daemons (1.2.2)
dalli (2.7.4)
delayed_job (4.0.6)
delayed_job_active_record (4.0.3)
delayed_job_web (1.2.10)
descendants_tracker (0.0.4)
dotenv (2.0.1)
equalizer (0.0.11)
eventmachine (1.0.7)
grape (0.11.0)
grape-activerecord (0.0.8)
hashie (3.4.1)
hashie-forbidden_attributes (0.1.1)
hitimes (1.2.2)
i18n (0.7.0)
ice_nine (0.11.1)
io-console (0.4.3)
json (1.8.2, 1.8.1)
kgio (2.9.3)
method_source (0.8.2)
minitest (5.6.0)
multi_json (1.11.0)
multi_xml (0.5.5)
mysql2 (0.3.18)
protected_attributes (1.0.9)
pry (0.10.1)
pry-byebug (3.1.0)
psych (2.0.8)
puma (2.11.2)
rack (1.6.0)
rack-accept (0.4.5)
rack-mount (0.8.3)
rack-protection (1.5.3)
raindrops (0.13.0)
rake (10.4.2)
rdoc (4.2.0)
rufus-scheduler (3.1.1)
sinatra (1.4.6)
slop (3.6.0)
sqlite3 (1.3.10)
thin (1.6.3)
thread_safe (0.3.5)
tilt (2.0.1)
timers (4.0.1)
tzinfo (1.2.2)
unicorn (4.9.0)
virtus (1.0.5)
```

**Comment by cannikin** [comment]
Ooo, found a workaround in another issue: https://github.com/postmodern/ruby-install/issues/184

    brew install llvm
    ruby-install rbx 2.3.0 -i ~/.rubies/rbx -- --llvm-config /usr/local/opt/llvm/bin/llvm-config

**Comment by mtwentyman** [comment]
In case this helps someone else (with v 2.5.2):

On OS X 10.10 (yosemite) I successfully installed with:

```
rvm get stable
brew update
brew tap homebrew/versions
brew install llvm34
CXXFLAGS=-Wno-undefined-bool-conversion bash -c 'rvm install rbx-2.5.2 -- --llvm-config "$(brew --prefix llvm34)/bin/llvm-config-3.4"'
```

**Comment by pkuczynski** [comment]
This has been just fixed. Feel free to test with `rvm get master` and re-open when needed.

**Comment by pkuczynski** [comment]
Duplicate of #3287
