### ISSUE TITLE
Cannot install ruby-2.2.1 on NFS drive

### ISSUE THREAD

**Issue by bjpe** [rvm/rvm#3331]
Hi, trying to install ruby-2.2.1 on my NFS-mounted home fails with:

```
$ rvm install ruby-2.2.1
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/8/x86_64/ruby-2.2.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Requirements installation successful.
Installing Ruby from source to: /home/bjp/.rvm/rubies/ruby-2.2.1, this may take a while depending on your cpu(s)...
ruby-2.2.1 - #downloading ruby-2.2.1, this may take a while depending on your connection...
ruby-2.2.1 - #extracting ruby-2.2.1 to /home/bjp/.rvm/src/ruby-2.2.1....
ruby-2.2.1 - #configuring.........................................................
ruby-2.2.1 - #post-configuration..
ruby-2.2.1 - #compiling...............................................................................
ruby-2.2.1 - #installing...................
Error running '__rvm_make install',
showing last 15 lines of /home/bjp/.rvm/log/1425457224_ruby-2.2.1/install.log
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/request_set.rb:249:in `each'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/request_set.rb:249:in `install_into'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/request_set.rb:141:in `install'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/dependency_installer.rb:394:in `install'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems.rb:558:in `install'
	from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:721:in `each'
	from ./tool/rbinstall.rb:721:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
uncommon.mk:253: recipe for target 'do-install-nodoc' failed
make: *** [do-install-nodoc] Error 1
++ return 2
There has been an error while running make install. Halting the installation.
```

The mentioned log file contains the following information:

```
...
installing default gems:      /home/bjp/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.2.6
                              io-console 0.4.3
                              json 1.8.1
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
installing bundle gems:       /home/bjp/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              power_assert-0.2.2.gem
/home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:369:in `initialize': Permission denied @ rb_sysopen - /home/bjp/.rvm/gems/ruby-2.0.0-p643/gems/minitest-5.4.3/test/minitest/metametameta.rb (Errno::EACCES)
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:369:in `open'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:369:in `block (2 levels) in extract_tar_gz'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package/tar_reader.rb:64:in `each'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:351:in `block in extract_tar_gz'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:442:in `block in open_tar_gz'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:439:in `wrap'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:439:in `open_tar_gz'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:350:in `extract_tar_gz'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:331:in `block (2 levels) in extract_files'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package/tar_reader.rb:64:in `each'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:328:in `block in extract_files'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package/file_source.rb:29:in `open'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package/file_source.rb:29:in `with_read_io'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/package.rb:325:in `extract_files'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/installer.rb:722:in `extract_files'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/installer.rb:248:in `install'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/resolver/specification.rb:96:in `install'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/request_set.rb:257:in `block in install_into'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/request_set.rb:249:in `each'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/request_set.rb:249:in `install_into'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/request_set.rb:141:in `install'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems/dependency_installer.rb:394:in `install'
	from /home/bjp/.rvm/src/ruby-2.2.1/lib/rubygems.rb:558:in `install'
	from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:721:in `each'
	from ./tool/rbinstall.rb:721:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
uncommon.mk:253: recipe for target 'do-install-nodoc' failed
make: *** [do-install-nodoc] Error 1
++ return 2
```

I believe that the cause for this error is in rubygems (https://github.com/rubygems/rubygems/issues/1161, fixes in Rubygems 2.4.6) and occurs when installing minitest (https://github.com/seattlerb/minitest/issues/435). However, this issue prevents me from installing ruby-2.2.1. Do you have an idea for a workaround?

**Comment by zenspider** [comment]
Depending partially on how rvm builds/installs... this should only be affecting the gem installs at the very end. Updating rubygems (`gem update --system`) and then installing them should work fine.

**Comment by bjpe** [comment]
Okay, I didn't know if the failing gem installation causes some subsequent steps to fail, but this might work. Meanwhile, I solved the problem for me by logging in to another machine where my home directory was not mounted using NFS.

**Comment by havenwood** [comment]
Closed as resolved upstream.
