### ISSUE TITLE
problems installing Rubinius, can't find rake

### ISSUE THREAD

**Issue by tompave** [rvm/rvm#3386]
I'm having troubles installing `rbx-2.5.2` on OS X 10.10.3

I'm getting the same error both with the latest `stable` and with `rvm get head` (and then `reload`).

Here is the error:
```
$ rvm install rbx
rbx-2.5.2 - #removing src/rbx-2.5.2..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.10/x86_64/rbx-2.5.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
ruby-2.2.2@rubinius - #regenerating binstubs..........
rbx-2.5.2 - #downloading rubinius-2.5.2, this may take a while depending on your connection...
rbx-2.5.2 - #extracting rubinius-2.5.2 to /Users/username/.rvm/src/rbx-2.5.2....
ruby-2.2.2@rubinius - #bundle install..
rbx-2.5.2 - #configuring...
Error running 'env /Users/username/.rvm/wrappers/ruby-2.2.2@rubinius/ruby ./configure --prefix=/Users/username/.rvm/rubies/rbx-2.5.2 --with-opt-dir=/usr/local/opt/libyaml --with-opt-dir=/usr/local/opt/readline --with-opt-dir=/usr/local/opt/libksba --with-opt-dir=/usr/local/opt/openssl',
showing last 15 lines of /Users/username/.rvm/log/1429360782_rbx-2.5.2/configure.log

# ...omissis
```

and here is the log:
```
$ cat /Users/username/.rvm/log/1429360060_rbx-2.5.2/configure.log

[2015-04-18 13:39:55] env
current path: /Users/username/.rvm/src/rbx-2.5.2
PATH=/Users/username/.rvm/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin
command(8): env /Users/username/.rvm/wrappers/ruby-2.2.2@rubinius/ruby ./configure --prefix=/Users/username/.rvm/rubies/rbx-2.5.2 --with-opt-dir=/usr/local/opt/libyaml --with-opt-dir=/usr/local/opt/readline --with-opt-dir=/usr/local/opt/libksba --with-opt-dir=/usr/local/opt/openssl
Checking /usr/bin/clang: found
Checking g++: found
Checking bison: found

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/spec_set.rb:85:in `map!'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/spec_set.rb:85:in `materialize'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/definition.rb:132:in `specs'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/definition.rb:177:in `specs_for'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/definition.rb:166:in `requested_specs'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/environment.rb:18:in `requested_specs'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/runtime.rb:13:in `setup'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler.rb:122:in `setup'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/setup.rb:18:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
not found
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
```

It looks like it's using the default system ruby from OS X, and it also can't find `rake`, although:

```
$ gem list rake

*** LOCAL GEMS ***

rake (10.4.2)
```

Here is the output of `rvm --debug install rbx`:

```
$ rvm --debug install rbx
rbx-2.5.2 - install
Log prefix: /Users/username/.rvm/log/1429361181_rbx-2.5.2/
Log filesystem: local,
Log max name length: 250
Log file: /Users/username/.rvm/log/1429361181_rbx-2.5.2/remove.src.log
[2015-04-18 13:46:21] __rvm_rm_rf
__rvm_rm_rf ()
{
    __rvm_rm_rf_verbose "$@"
}
current path: /Users/Tom
GEM_HOME=/Users/username/.rvm/gems/ruby-2.2.2
PATH=/Users/username/.rvm/gems/ruby-2.2.2/bin:/Users/username/.rvm/gems/ruby-2.2.2@global/bin:/Users/username/.rvm/rubies/ruby-2.2.2/bin:/Users/username/.rvm/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin
GEM_PATH=/Users/username/.rvm/gems/ruby-2.2.2:/Users/username/.rvm/gems/ruby-2.2.2@global
command(2): __rvm_rm_rf /Users/username/.rvm/src/rbx-2.5.2
rbx-2.5.2 - #removing src/rbx-2.5.2..
rbx-2.5.2 - #already removed rubies/rbx-2.5.2
Searching for binary rubies, this might take some time.
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/rubinius-2.5.2.tar.bz2
Remote file does not exist http://binaries.rubini.us/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
Remote file does not exist https://rubies.travis-ci.org/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
rvm_remote_server_url4 not found
No remote file name found
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/rubinius-2.5.2.tar.bz2
Remote file does not exist http://binaries.rubini.us/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
Remote file does not exist https://rubies.travis-ci.org/osx/10.10/x86_64/rubinius-2.5.2.tar.bz2
rvm_remote_server_url4 not found
No remote file name found
No binary rubies available for: osx/10.10/x86_64/rbx-2.5.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Free disk space 323841MB, required 770MB.
__rvm_setup_compile_environment_setup rbx-2.5.2
rvm_autolibs_flag=enable
__rvm_setup_compile_environment_movable_early rbx-2.5.2
__rvm_setup_compile_environment_system_early rbx-2.5.2
__rvm_setup_compile_environment_requirements rbx-2.5.2
Checking requirements for osx.
requirements code for osx loaded
requirements lib type set to osx_brew
brew seems to be writable
Found required packages: autoconf, automake, libtool, pkg-config, libyaml, readline, libksba, openssl.
PATH=/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/username/.rvm/gems/ruby-2.2.2/bin:/Users/username/.rvm/gems/ruby-2.2.2@global/bin:/Users/username/.rvm/rubies/ruby-2.2.2/bin:/Users/username/.rvm/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/libyaml )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/readline )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/libksba )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/openssl )
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
__rvm_setup_compile_environment_movable rbx-2.5.2
__rvm_setup_compile_environment_parse_name rbx-2.5.2
__rvm_setup_compile_environment_system rbx-2.5.2
__rvm_setup_compile_environment_architectures rbx-2.5.2
rvm_architectures(0):.
__rvm_setup_compile_environment_gcc47plus rbx-2.5.2
__rvm_setup_compile_environment_bison rbx-2.5.2
__rvm_setup_compile_environment_flags_docs rbx-2.5.2
__rvm_setup_compile_environment_flags_shared_static rbx-2.5.2
__rvm_setup_compile_environment_flags_threads rbx-2.5.2
__rvm_setup_compile_environment_compatibility_flag rbx-2.5.2
found compiler: /usr/bin/clang
Running /Users/username/.rvm/hooks/after_use_maglev
Log file: /Users/username/.rvm/log/1429361181_ruby-2.2.2/regenerate_binstubs.log
[2015-04-18 13:46:33] rubinius_install_regenerate_binstubs
rubinius_install_regenerate_binstubs ()
{
    gem_install executable-hooks && gem regenerate_binstubs || return $?
}
current path: /Users/Tom
GEM_HOME=/Users/username/.rvm/gems/ruby-2.2.2@rubinius
PATH=/Users/username/.rvm/gems/ruby-2.2.2@rubinius/bin:/Users/username/.rvm/gems/ruby-2.2.2@global/bin:/Users/username/.rvm/rubies/ruby-2.2.2/bin:/Users/username/.rvm/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin
GEM_PATH=/Users/username/.rvm/gems/ruby-2.2.2@rubinius:/Users/username/.rvm/gems/ruby-2.2.2@global
command(1): rubinius_install_regenerate_binstubs
ruby-2.2.2@rubinius - #regenerating binstubs..........
rbx-2.5.2 - #downloading rubinius-2.5.2, this may take a while depending on your connection...
fetch http://releases.rubini.us/rubinius-2.5.2.tar.bz2 => rubinius-2.5.2.tar.bz2
Archive checksum matched, not downloading
Downloaded archive checksum matched.
Log file: /Users/username/.rvm/log/1429361181_rbx-2.5.2/extract.log
[2015-04-18 13:46:34] __rvm_package_extract
__rvm_package_extract ()
{
    rvm_debug __rvm_package_extract:$#: "$@";
    \typeset __tempdir __path __file __return;
    __return=0;
    __tempdir="$( TMPDIR="${rvm_tmp_path}" mktemp -d -t rvm-tmp.XXXXXXXXX )";
    __rvm_package_extract_run "$1" "$__tempdir" || __return=$?;
    if (( __return == 0 )); then
        for __path in "$__tempdir"/*;
        do
            __file="${__path##*/}";
            if [[ -n "${__file}" && -e "$2/${__file}" ]]; then
                \command \rm -rf "$2/${__file}" || __return=$?;
            fi;
            \command \mv -f "${__path}" "$2/" || __return=$?;
        done;
    fi;
    if [[ -n "$__tempdir" ]]; then
        \command \rm -rf "$__tempdir";
    fi;
    return $__return
}
current path: /Users/Tom
PATH=/Users/username/.rvm/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin
command(3): __rvm_package_extract /Users/username/.rvm/archives/rubinius-2.5.2.tar.bz2 /Users/username/.rvm/tmp/rvm_src_32828
rbx-2.5.2 - #extracting rubinius-2.5.2 to /Users/username/.rvm/src/rbx-2.5.2.....
__rvm_rm_rf already gone: /Users/username/.rvm/src/rbx-2.5.2
Patch name 'optional', expanded_name(s) ''.
Patch name 'default', expanded_name(s) ''.
Patch name 'osx', expanded_name(s) ''.
All found patches(0): .
Log file: /Users/username/.rvm/log/1429361181_rbx-2.5.2/bundle.log
[2015-04-18 13:46:38] /Users/username/.rvm/wrappers/ruby-2.2.2@rubinius/bundle
current path: /Users/username/.rvm/src/rbx-2.5.2
PATH=/Users/username/.rvm/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin
command(2): /Users/username/.rvm/wrappers/ruby-2.2.2@rubinius/bundle install
ruby-2.2.2@rubinius - #bundle install..
Log file: /Users/username/.rvm/log/1429361181_rbx-2.5.2/configure.log
[2015-04-18 13:46:38] env
current path: /Users/username/.rvm/src/rbx-2.5.2
PATH=/Users/username/.rvm/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/9.3/bin
command(8): env /Users/username/.rvm/wrappers/ruby-2.2.2@rubinius/ruby ./configure --prefix=/Users/username/.rvm/rubies/rbx-2.5.2 --with-opt-dir=/usr/local/opt/libyaml --with-opt-dir=/usr/local/opt/readline --with-opt-dir=/usr/local/opt/libksba --with-opt-dir=/usr/local/opt/openssl
rbx-2.5.2 - #configuring...
Error running 'env /Users/username/.rvm/wrappers/ruby-2.2.2@rubinius/ruby ./configure --prefix=/Users/username/.rvm/rubies/rbx-2.5.2 --with-opt-dir=/usr/local/opt/libyaml --with-opt-dir=/usr/local/opt/readline --with-opt-dir=/usr/local/opt/libksba --with-opt-dir=/usr/local/opt/openssl',
showing last 15 lines of /Users/username/.rvm/log/1429361181_rbx-2.5.2/configure.log
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/spec_set.rb:85:in `map!'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/spec_set.rb:85:in `materialize'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/definition.rb:132:in `specs'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/definition.rb:177:in `specs_for'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/definition.rb:166:in `requested_specs'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/environment.rb:18:in `requested_specs'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/runtime.rb:13:in `setup'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler.rb:122:in `setup'
    from /Users/username/.rvm/gems/ruby-2.2.2@rubinius/gems/bundler-1.9.4/lib/bundler/setup.rb:18:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
not found
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
__rvm_rm_rf already gone: /Users/username/.rvm/tmp/32828*
```

**Comment by d4rky-pl** [comment]
```
rvm @global do gem install rake -v '10.4.2'
brew install llvm
CXXFLAGS=-Wno-undefined-bool-conversion rvm install rbx
```

This worked for me. You must have homebrew installed on your machine (though it'd probably work with macports too)

**Comment by d4rky-pl** [comment]
The reason this crashes is that environmental variables RUBYOPT and RUBYLIB are leaked to Homebrew causing it to crash. That's why installing rake in global gemset accidentally masked the problem.

**Comment by d4rky-pl** [comment]
After some more digging it looks like the problem is actually with Rubinius and not with RVM. I'm preparing a pull request for them.

**Comment by tompave** [comment]
I see, thank you @d4rky-pl
