### ISSUE TITLE
Problem ruby-2.1.6 installation with SmartOS (v14.4.1) 

### ISSUE THREAD

**Issue by loommy24** [rvm/rvm#3415]
Hi Guys,

I found this problem below when installing ruby-2.1.6 on SmartOS(14.4.1), but 2.1.5 version are ok.

    [2015-05-07 16:25:57] /home/rommy/.rvm/rubies/ruby-2.1.6/bin/ruby
    current path: /home/rommy/.rvm/src/rubygems-2.4.0
    GEM_HOME=/home/rommy/.rvm/gems/ruby-2.1.6
    PATH=/home/rommy/.rvm/gems/ruby-2.1.6/bin:/home/rommy/.rvm/gems/ruby2.1.6@global/bin:/home/rommy/.rvm/rubies/ruby-2.1.6/bin:/home/rommy/.rvm/bin:/usr/local/sbin:/usr/local/bin:/opt/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin
    GEM_PATH=/home/rommy/.rvm/gems/ruby-2.1.6:/home/rommy/.rvm/gems/ruby-2.1.6@global
    command(7): env GEM_HOME=/home/rommy/.rvm/gems/ruby-2.1.6@global GEM_PATH= /home/rommy/.rvm/rubies/ruby-2.1.6/bin/ruby -d /home/rommy/.rvm/src/rubygems-2.4.0/setup.rb --no-document
    Exception `LoadError' at /home/rommy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems.rb:1194 - cannot load such file -- rubygems/defaults/operating_system
    Exception `LoadError' at /home/rommy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems.rb:1203 - cannot load such file -- rubygems/defaults/ruby
    /home/rommy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/yaml.rb:4:in `<top (required)>':
    It seems your ruby installation is missing psych (for YAML output).
    To eliminate this warning, please install libyaml and reinstall your ruby.
    /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/core_ext/kernel_require.rb:54:in `require': ld.so.1: ruby: fatal: relocation error: file /home/rommy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/x86_64-solaris2.11/date_core.so: symbol rb_infinity: referenced symbol not found - /home/rommy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/x86_64-solaris2.11/date_core.so (LoadError)
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/rommy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/date.rb:3:in `<top (required)>'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/rommy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/psych/deprecated.rb:1:in `<top (required)>'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/rommy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/psych.rb:12:in `<top (required)>'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/rommy/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/yaml.rb:5:in `<top (required)>'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems.rb:618:in `load_yaml'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/config_file.rb:328:in `load_file'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/config_file.rb:197:in `initialize'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/gem_runner.rb:74:in `new'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/gem_runner.rb:74:in `do_configuration'
        from /home/rommy/.rvm/src/rubygems-2.4.0/lib/rubygems/gem_runner.rb:39:in `run'
        from setup.rb:45:in `<main>':

Thanks.

--
Regards,
Rommy

**Comment by ojab** [comment]
Can you post `cat /etc/release` & `uname -a` output or provide me with link to that SmartOS release?

**Comment by bbhoss** [comment]
Use CFLAGS="-std=iso9899:1999" when compiling and it'll work.
