### ISSUE TITLE
Please add JRuby 9.0.0.0.rc1

### ISSUE THREAD

**Issue by garysweaver** [rvm/rvm#3444]
Currently the latest version of JRuby in `rvm list known` after updating RVM is `jruby-9.0.0.0.pre2`, but the [latest version](http://jruby.org/2015/06/10/jruby-9-0-0-0-rc1.html) of JRuby at time of writing this is 9.0.0.0.rc1. Could that version be added?

**Comment by jzakiya** [comment]
I just did an upgrade on my system and it went out and found the sources and installed them.
Everything worked like a charm even though rc1 was not in the "rvm list known" list.

Do:  rvm upgrade jruby-9.0.0.0.pre2 jruby-9.0.0.0.rc1

**Comment by garysweaver** [comment]
Thanks, @jzakiya!

Going to leave this open so they can update the known rubies list.

**Comment by Envek** [comment]
`rvm install jruby-9.0.0.0.rc1` works fine too, despite numerous `Unknown ruby string (do not know how to handle): jruby-9.0.0.0.rc1.` messages in red.

**Comment by thehappycoder** [comment]
Doesn't work for me.

$ rvm reinstall jruby-9.0.0.0.pre1
jruby-9.0.0.0.pre1 - #removing rubies/jruby-9.0.0.0.pre1..
Searching for binary rubies, this might take some time.
Found remote file /home/idnet/.rvm/archives/jruby-bin-9.0.0.0.pre1.tar.gz
Checking requirements for debian.
Requirements installation successful.
jruby-9.0.0.0.pre1 - #configure
jruby-9.0.0.0.pre1 - #download
jruby-9.0.0.0.pre1 - #validate archive
jruby-9.0.0.0.pre1 - #extract
jruby-9.0.0.0.pre1 - #validate binary
jruby-9.0.0.0.pre1 - #setup
jruby-9.0.0.0.pre1 - #gemset created /home/idnet/.rvm/gems/jruby-9.0.0.0.pre1@global
jruby-9.0.0.0.pre1 - #importing gemset /home/idnet/.rvm/gemsets/jruby/global.gems...........................-
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at com.martiansoftware.nailgun.NGServer.run(NGServer.java:411)
	at java.lang.Thread.run(Thread.java:745)
jruby-9.0.0.0.pre1 - #generating global wrappers..............
jruby-9.0.0.0.pre1 - #gemset created /home/idnet/.rvm/gems/jruby-9.0.0.0.pre1
jruby-9.0.0.0.pre1 - #importing gemsetfile /home/idnet/.rvm/gemsets/default.gems evaluated to empty gem list
jruby-9.0.0.0.pre1 - #generating default wrappers..............
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at com.martiansoftware.nailgun.NGServer.run(NGServer.java:411)
	at java.lang.Thread.run(Thread.java:745)
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at com.martiansoftware.nailgun.NGServer.run(NGServer.java:411)
	at java.lang.Thread.run(Thread.java:745)
Making gemset jruby-9.0.0.0.pre1 pristine...............................................................
Error running '__rvm_with jruby-9.0.0.0.pre1 gemset_pristine',
showing last 15 lines of /home/idnet/.rvm/log/1436277702_jruby-9.0.0.0.pre1/gemset.pristine-jruby-9.0.0.0.pre1.log
++ [[ -t 2 ]]
++ return 1
++ printf %b '\n'\''command gem pristine error: --version ng'\'' failed, you need to fix this gems manually.\n'

'command gem pristine error: --version ng' failed, you need to fix this gems manually.
++ return 1
++ return 1
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at com.martiansoftware.nailgun.NGServer.run(NGServer.java:411)
	at java.lang.Thread.run(Thread.java:745)
Making gemset jruby-9.0.0.0.pre1@global pristine............................................................|
Error running '__rvm_with jruby-9.0.0.0.pre1@global gemset_pristine',
showing last 15 lines of /home/idnet/.rvm/log/1436277702_jruby-9.0.0.0.pre1/gemset.pristine-jruby-9.0.0.0.pre1@global.log
++ [[ -t 2 ]]
++ return 1
++ printf %b '\n'\''command gem pristine error: --version ng'\'' failed, you need to fix this gems manually.\n'

'command gem pristine error: --version ng' failed, you need to fix this gems manually.
++ return 1
++ return 1
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at com.martiansoftware.nailgun.NGServer.run(NGServer.java:411)
	at java.lang.Thread.run(Thread.java:745)

**Comment by thehappycoder** [comment]
I explained in detail at #3458

**Comment by garysweaver** [comment]
Note that JRuby 9.0.0.0 is available now. At the moment, you need to be using the development version of RVM to access it, but that will change soon I think.
