### ISSUE TITLE
fail to compile ruby-2.2.3

### ISSUE THREAD

**Issue by hrzhu** [rvm/rvm#3504]
Xubuntu 14.04  rvm master

```
rvm install 2.2.3 \ 
--with-tcltkversion=8.6 \
--with-tcl-lib=/usr/lib/x86_64-linux-gnu \
--with-tk-lib=/usr/lib/x86_64-linux-gnu \
--with-tcl-include=/usr/include/tk8.6 \
--with-tk-include=/usr/include/tk8.6 \
> 
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /home/h/.rvm/rubies/ruby-2.2.3, this may take a while depending on your cpu(s)...
ruby-2.2.3 - #downloading ruby-2.2.3, this may take a while depending on your connection...
ruby-2.2.3 - #extracting ruby-2.2.3 to /home/h/.rvm/src/ruby-2.2.3 - please wait
ruby-2.2.3 - #configuring - please wait
sending incremental file list
config.log
        916.97K 100%  421.62MB/s    0:00:00 (xfr#1, to-chk=0/1)

sent 917.28K bytes  received 35 bytes  1.83M bytes/sec
total size is 916.97K  speedup is 1.00
ruby-2.2.3 - #post-configuration - please wait
ruby-2.2.3 - #compiling - please wait
ruby-2.2.3 - #installing - please wait
Error running '__rvm_make install',
showing last 15 lines of /home/h/.rvm/log/1441798369_ruby-2.2.3/install.log
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
installing bundle gems:       /home/h/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              power_assert-0.2.2.gem
                              test-unit-3.0.8.gem
                              minitest-5.4.3.gem
./tool/rbinstall.rb:728:in `chmod': Operation not permitted @ chmod_internal - / (Errno::EPERM)
	from ./tool/rbinstall.rb:728:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-nodoc] Error 1
+__rvm_make:0> return 2
There has been an error while running make install. Halting the installation.
```

I can successfully compile 2.2.2, just substitute 2.2.3 with 2.2.2.

**Comment by hrzhu** [comment]
I can compile it now with rvm reinstall 2.2.3 --with-tcltkversion=8.6 --with-tcl-lib=/usr/lib/x86_64-linux-gnu --with-tk-lib=/usr/lib/x86_64-linux-gnu --with-tcl-include=/usr/include/tcl8.6 --with-tk-include=/usr/include/tcl8.6 --enable-pthread --enable-shared
