### ISSUE TITLE
Installing Rubinius 2.5.8 on Ubuntu 15.04

### ISSUE THREAD

**Issue by glebm** [rvm/rvm#3541]
On Ubuntu 15.04 the default clang points to clang-3.6, which is too new for Rubinius, and `rvm install rbx-2.5.8` fails.

This worked:

``` console
$ sudo apt-get install clang-3.5
$ rvm install rbx-2.5.8 -C --llvm-config=/usr/bin/llvm-config-3.5
```

**Comment by dblock** [comment]
Related? https://github.com/rubinius/rubinius/issues/3497

**Comment by dalpo** [comment]
It doesn't work on ubuntu 15.10... :disappointed: 
Any idea on how I can install it on the latest version of Ubuntu?

**Comment by olistik** [comment]
@dalpo same problem here:

```
ಠ_ಠ rvm --version
rvm 1.26.11 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ಠ_ಠ uname -a
Linux ronin 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ಠ_ಠ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
ಠ_ಠ rvm install rbx-2.5.8 -C --llvm-config=/usr/bin/llvm-config-3.5
rbx-2.5.8 - #removing src/rbx-2.5.8..
Checking requirements for ubuntu.
Requirements installation successful.
ruby-2.2.3@rubinius - #regenerating binstubs..........
rbx-2.5.8 - #downloading rubinius-2.5.8, this may take a while depending on your connection...
rbx-2.5.8 - #extracting rubinius-2.5.8 to /home/olistik/.rvm/src/rbx-2.5.8....
ruby-2.2.3@rubinius - #bundle install..
rbx-2.5.8 - #configuring............
rbx-2.5.8 - #compiling................................................................................................................................
Error running '/home/olistik/.rvm/wrappers/ruby-2.2.3@rubinius/rake install --trace',
showing last 15 lines of /home/olistik/.rvm/log/1448888538_rbx-2.5.8/rake.log
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/olistik/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/olistik/.rvm/rubies/ruby-2.2.3/bin/rake:33:in `<main>'
/home/olistik/.rvm/gems/ruby-2.2.3@rubinius/bin/ruby_executable_hooks:15:in `eval'
/home/olistik/.rvm/gems/ruby-2.2.3@rubinius/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => install => build:build => vm/vm
ಠ_ಠ 
```

Here's the content of rake.log: [link](https://gist.github.com/olistik/34eb3de1cb14e0639d23)

**Comment by lucianolev** [comment]
Same issue here in Ubuntu 15.10.. Any workaround?

**Comment by pkuczynski** [comment]
This has been just fixed. Feel free to test with `rvm get master` and re-open when needed.
