### ISSUE TITLE
Static builds fail on ruby-head (and 2.3.0) on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [rvm/rvm#3591]
Travis CI has been having problems compiling ruby-head on OS X since early September. (We did not pay much attention to this issue until 2.3.0 was officially released. Sorry about that.)

You can see a recent failure at https://travis-ci.org/travis-ci/travis-rubies/jobs/98930310.

We run `rvm autolibs smf`, `rvm install ruby-head --verify-downloads 1 --movable --disable-install-doc`, but the latter would fail (https://travis-ci.org/travis-ci/travis-rubies/jobs/98930310#L248) with:

```
/Users/travis/.rvm/src/ruby-head/lib/rubygems/security.rb:343:in `<module:Security>': uninitialized constant OpenSSL::Digest::SHA1 (NameError)
```

For completeness, here's the install log in its entirety:

```
/Users/travis/.rvm/log//1451184087_ruby-head-clang/install.log
[2015-12-27 02:53:05] __rvm_make
__rvm_make () 
{ 
    \make "$@" || return $?
}
current path: /Users/travis/.rvm/src/ruby-head-clang
GEM_HOME=/Users/travis/.rvm/gems/ruby-2.0.0-p643
PATH=/Users/travis/.sm/pkg/active/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/travis/.rvm/rubies/ruby-2.0.0-p643/bin:/Users/travis/bin:/Users/travis/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/travis/.rvm/gems/ruby-2.0.0-p643/bin:/Users/travis/.rvm/gems/ruby-2.0.0-p643@global/bin:/Users/travis/.rvm/rubies/ruby-2.0.0-p643/bin:/Users/travis/.rvm/bin:/Users/travis/.rvm/bin:/Users/travis/.rvm/bin:/Users/travis/.sm/bin:/Users/travis/.sm/pkg/active/sbin
GEM_PATH=/Users/travis/.rvm/gems/ruby-2.0.0-p643:/Users/travis/.rvm/gems/ruby-2.0.0-p643@global
command(2): __rvm_make install
++make install
generating x86_64-darwin14-fake.rb
x86_64-darwin14-fake.rb updated
	CC = clang
	LD = ld
	LDSHARED = clang -dynamic -bundle
	CFLAGS = -O3 -I/Users/travis/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe -arch x86_64
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT
	CPPFLAGS = -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I.ext/include/x86_64-darwin14 -I./include -I.
	DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -fstack-protector -Wl,-u,_objc_msgSend -framework CoreFoundation  -arch x86_64
	SOLIBS = -lgmp 
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
generating enc.mk
making libenc
make[1]: Nothing to be done for `libenc'.
making srcs under enc
make[1]: Nothing to be done for `srcs'.
generating transdb.h
transdb.h unchanged
making libtrans
make[1]: Nothing to be done for `libtrans'.
making libencs
make[1]: Nothing to be done for `libencs'.
generating makefile exts.mk
configuring rbconfig/sizeof
configuring ripper
configuring socket
Failed to configure win32. It will not be installed.
LIBRUBY_SO_UPDATE=$(LIBRUBY_EXTS)
SETUP=ext/Setup
EXTLIBS=-lz -lssl -lcrypto -lz -lssl -lcrypto -lz -lssl -lcrypto -lz -lssl -lcrypto -lz -lssl -lcrypto -lyaml -lreadline -ltermcap -ldl -lffi -lgdbm -lutil
EXTLDFLAGS=-L. -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -L. -L/Users/travis/.sm/pkg/active/lib -fPIC -Bstatic -lz -fstack-protector -L/usr/local/lib
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
checking ../.././parse.y and ../.././ext/ripper/eventids2.c
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
make[2]: Nothing to be done for `static'.
generating enc.mk
compiling enc/encinit.c
linking ruby
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-darwin14-fake ./tool/rbinstall.rb --make="/Applications/Xcode.app/Contents/Developer/usr/bin/make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
/Users/travis/.rvm/src/ruby-head-clang/lib/rubygems/security.rb:344:in `<module:Security>': uninitialized constant OpenSSL::Digest::SHA1 (NameError)
	from /Users/travis/.rvm/src/ruby-head-clang/lib/rubygems/security.rb:332:in `<top (required)>'
	from /Users/travis/.rvm/src/ruby-head-clang/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/travis/.rvm/src/ruby-head-clang/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/travis/.rvm/src/ruby-head-clang/lib/rubygems/package.rb:44:in `<top (required)>'
	from /Users/travis/.rvm/src/ruby-head-clang/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/travis/.rvm/src/ruby-head-clang/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/travis/.rvm/src/ruby-head-clang/lib/rubygems/installer.rb:10:in `<top (required)>'
	from /Users/travis/.rvm/src/ruby-head-clang/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/travis/.rvm/src/ruby-head-clang/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./tool/rbinstall.rb:657:in `<module:RbInstall>'
	from ./tool/rbinstall.rb:585:in `<main>'
make: *** [do-install-nodoc] Error 1
++return 2
```

**Comment by havenwood** [comment]
I was able to reproduce this. Manually updating the SM Framework OpenSSL version from 1.0.1j to 1.0.2e fixed it for me.

@mpapis [updated the openssl version in the sm-libraries](https://github.com/sm/sm-libraries/commit/698d355238dc4a28eeb3dce6d0e51eef4545f3e4) upstream so that should be ready for testing.

**Comment by BanzaiMan** [comment]
Hmmm. I ran a new build, but it is still failing. In https://s3.amazonaws.com/archive.travis-ci.org/jobs/99545167/log.txt, you see that OpenSSL 1.0.2e is compiled and installed.

**Comment by mpapis** [comment]
the log ends at 
```bash
++for __set in '"$@"'^M
++__smf_t
```

**Comment by BanzaiMan** [comment]
@mpapis Indeed. But that's because I dumped all log files in `$rvm_path/log/`. You can see the entire content of `
/Users/travis/.rvm/log//1451532292_ruby-head-clang/install.log`.

**Comment by mpapis** [comment]
in the log there is this line:
```bash
rvm autolibs homebrew
```
which means it's on the homebrew openssl not sm

also the script does some trickery which could be simplified, but if it works ;)

**Comment by BanzaiMan** [comment]
Neither skipping `rvm autolibs homebrew` (https://travis-ci.org/travis-ci/travis-rubies/builds/99557950; see [`build.sh`](https://github.com/travis-ci/travis-rubies/blob/fb5f5c0785705a37906d1a01040d3221e5f5dfdf/build.sh)) nor using Homebrew's OpenSSL 1.0.2e (https://travis-ci.org/travis-ci/travis-rubies/builds/99559385#L243; see [`build.sh`](https://github.com/travis-ci/travis-rubies/blob/b59d12e30d502037637be9f0f69c4a09b335208e/build.sh)) worked.

(Both builds are marked passing, because there is only one job in the build matrix, and it is allowed to fail.)

**Comment by mpapis** [comment]
in `/Users/travis/.rvm/src/ruby-2.3.0` could you run: `otool -L miniruby` and show us the results - this should show which libraries are used, btw, the ruby/rubygems code that triggers this problem is buggy IMHO:
```ruby
  DIGEST_ALGORITHM =
    if defined?(OpenSSL::Digest) then
      OpenSSL::Digest::SHA1
    end
```
which assumes that there will be `SHA1` if there is `Digest`

**Comment by segiddins** [comment]
That rubygems bug is fixed as of 2.5.2

**Comment by BanzaiMan** [comment]
@mpapis That directory doesn't seem to exist at the end of the build. https://travis-ci.org/travis-ci/travis-rubies/jobs/107149525#L214

**Comment by mpapis** [comment]
@BanzaiMan it could not exist because the process failed a lot earlier and the errors of the earlier problem are in `/Users/travis/.rvm/log/1454641158_ruby-head/package_install_openssl.log` ... well the timestamp will change so try: `ls -t1 /Users/travis/.rvm/log/*_ruby-head/package_install_openssl.log | head -n 1 | xargs cat`

**Comment by BanzaiMan** [comment]
@mpapis https://travis-ci.org/travis-ci/travis-rubies/jobs/107852816#L217

**Comment by mpapis** [comment]
looks like the configure step failed for openssle, can I see content of those files: `/Users/travis/.sm/src/openssl-1.0.2e/*.log` (config/configure is most likely what we need)

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/travis-rubies/jobs/107909193#L301

**Comment by mpapis** [comment]
@BanzaiMan can you investigate the worker and look into the failures? it's following the displayed errors, I'm guessing the next step would be checking `/Users/travis/.sm/src/openssl-1.0.2e` - maybe there are some clues, I wonder why there is no other log file, make sure to check for `Makefile` - according to the message it's missing.
