### ISSUE TITLE
problem with installing ruby 2.3.0 on OSX El Capitan 10.11.3 couldn't understand kern.osversion 15.3.0

### ISSUE THREAD

**Issue by hristopeev** [rvm/rvm#3626]
Hello,

I am having issues with installing ruby 2.3.0 on my OSX El Capitan 10.11.3. I think something is wrong with gcc, but I am not able to identify exactly what.

In the following gist, you can find my configuration + all command I have tried and their output.
https://gist.github.com/hristopeev/7f56ae286cb2763df87e .

Here is a short version of the gist.
**$ rvm install 2.3.0**
```
...
configure: error: something wrong with CFLAGS="-g -O2 "
...
```

Then I tried to pass ```CFLAGS=''```
**$ CFLAGS='' rvm install 2.3.0**
```
...
configure: error: something wrong with CFLAGS=" "
...
```

Then I tried to pass ```CC=/usr/bin/gcc```
**$ CC=/usr/bin/gcc rvm install 2.3.0**
```
...
ruby-2.3.0 - #compiling.......................................................
Error running '__rvm_make -j 1',
showing last 15 lines of /Users/hristopeev/.rvm/log/1455285228_ruby-2.3.0/make.log
                                      ^
etc.c:788:56: error: passing 'void' to parameter of incompatible type 'VALUE' (aka 'unsigned long')
    rb_hash_aset(result, ID2SYM(rb_intern("machine")), rb_str_new_cstr(u.machine));
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:803:30: note: expanded from macro 'rb_str_new_cstr'
#define rb_str_new_cstr(str) __extension__ (    \
                             ^~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:520:39: note: passing argument to parameter here
VALUE rb_hash_aset(VALUE, VALUE, VALUE);
                                      ^
1 warning and 6 errors generated.
make[2]: *** [etc.o] Error 1
make[1]: *** [ext/etc/all] Error 2
make: *** [build-ext] Error 2
++ return 2
...
```

Then I tried passing both ```CC=/usr/bin/gcc and CFLAGS=''```
**$ CC=/usr/bin/gcc CFLAGS='' rvm install 2.3.0**
```
...
ruby-2.3.0 - #installing..
Error running '__rvm_make install',
showing last 15 lines of /Users/hristopeev/.rvm/log/1455285517_ruby-2.3.0/install.log
PATH=/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/hristopeev/.rvm/gems/ruby-2.1.2/bin:/Users/hristopeev/.rvm/gems/ruby-2.1.2@global/bin:/Users/hristopeev/.rvm/rubies/ruby-2.1.2/bin:/Users/hristopeev/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hristopeev/.rvm/bin
GEM_PATH=/Users/hristopeev/.rvm/gems/ruby-2.1.2:/Users/hristopeev/.rvm/gems/ruby-2.1.2@global
command(2): __rvm_make install
++ make install
generating x86_64-darwin15-fake.rb
couldn't understand kern.osversion `15.3.0'
cc1: error: unrecognized command line option "-Wdivision-by-zero"
./template/fake.rb.in:14:in `block in <main>': undefined method `gsub' for nil:NilClass (NoMethodError)
    from ./template/fake.rb.in:12:in `scan'
    from ./template/fake.rb.in:12:in `<main>'
    from /Users/hristopeev/.rvm/src/ruby-2.3.0/lib/erb.rb:864:in `eval'
    from /Users/hristopeev/.rvm/src/ruby-2.3.0/lib/erb.rb:864:in `result'
    from ./tool/generic_erb.rb:38:in `<main>'
make: *** [x86_64-darwin15-fake.rb] Error 1
++ return 2
...
```

At the bottom of my gist you can find the output of the last command with --debug flag included.

If you need any other details, I am ready to provide them.

Thank you!

**Comment by hristopeev** [comment]
I found 3 suspicious lines in my ```~/.bashrc``` file which were causing the problems:
```
export CC=/usr/local/Cellar/apple-gcc42/4.2.1-5666.3/bin/gcc-4.2
export CXX=/usr/local/Cellar/apple-gcc42/4.2.1-5666.3/bin/g++-4.2
export CPP=/usr/local/Cellar/apple-gcc42/4.2.1-5666.3/bin/cpp-4.2
```

I removed them and then the command ```rvm install 2.3.0``` finished normally without any issues.
