### ISSUE TITLE
Issue installing 2.2.4 when MacPorts has a ruby 2.2 installed

### ISSUE THREAD

**Issue by mat813** [rvm/rvm#3643]
Hi,

I have this:

```
$ /opt/local/bin/ruby2.2 -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
```

And ruby 2.2.1 installed via rvm works without a problem, but 2.2.4 installs a libruby shared library, and it has the same name as the one from macports, and they conflict:

```
$ rvm install 2.2.4
[...]
ruby-2.2.4 - #removing old rubygems.........
ruby-2.2.4 - #installing rubygems-2.4.8.
Error running 'env GEM_HOME=/Users/mat/.rvm/gems/ruby-2.2.4@global GEM_PATH= /Users/mat/.rvm/rubies/ruby-2.2.4/bin/ruby -d /Users/mat/.rvm/src/rubygems-2.4.8/setup.rb --no-document',
showing last 15 lines of /Users/mat/.rvm/log/1457653361_ruby-2.2.4/rubygems.install.log
[2016-03-11 00:45:56] /Users/mat/.rvm/rubies/ruby-2.2.4/bin/ruby
current path: /Users/mat/.rvm/src/rubygems-2.4.8
GEM_HOME=/Users/mat/.rvm/gems/ruby-2.2.1
PATH=/opt/local/bin:/Users/mat/.rvm/gems/ruby-2.2.1/bin:/Users/mat/.rvm/gems/ruby-2.2.1@global/bin:/Users/mat/.rvm/rubies/ruby-2.2.1/bin:/opt/local/sbin:/opt/local/sbin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/mat/bin:/Users/mat/.rvm/bin
GEM_PATH=/Users/mat/.rvm/gems/ruby-2.2.1:/Users/mat/.rvm/gems/ruby-2.2.1@global
command(7): env GEM_HOME=/Users/mat/.rvm/gems/ruby-2.2.4@global GEM_PATH= /Users/mat/.rvm/rubies/ruby-2.2.4/bin/ruby -d /Users/mat/.rvm/src/rubygems-2.4.8/setup.rb --no-document
Exception `fatal' at /Users/mat/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/x86_64-darwin15/thread.bundle - incompatible library version - /Users/mat/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/x86_64-darwin15/thread.bundle
/Users/mat/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems.rb:9:in `require': incompatible library version - /Users/mat/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/x86_64-darwin15/thread.bundle (fatal)
    from /Users/mat/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems.rb:9:in `<top (required)>'
    from <internal:gem_prelude>:1:in `require'
    from <internal:gem_prelude>:1:in `<compiled>'
```

Fiddeling around, running the same command through dtruss, I found out it tried to load

```
close(0x7)       = 0 0
stat64("/opt/local/lib/libruby.2.2.0.dylib\0", 0x7FFF5D4B7808, 0x1)      = 0 0
open("/opt/local/lib/libruby.2.2.0.dylib\0", 0x0, 0x0)       = 7 0
pread(0x7, "\317\372\355\376\a\0", 0x1000, 0x0)      = 4096 0
```

instead of the `~/.rvm/rubies/ruby-2.2.4/lib/libruby.2.2.0.dylib` that I have

moving the /opt/local/lib/libruby.2.2.0.dylib some place else allowed me to install ruby 2.2.4 via rvm.

**Comment by mpapis** [comment]
I'm not sure if it's ruby or rvm bug, did the trace provide any information why the `/opt/local/lib` was picked over `~/.rvm/rubies/ruby-2.2.4/lib`? like who called the `stat64`? maybe some previous lines would shed some light on what happen.

**Comment by mat813** [comment]
Well, the previous ruby (like, 2.2.1) don't use a shared libruby, so the problem was not present. The stat64 calls are made by, well, ruby, or the dynamic linker, or whatever its name is on osx.

**Comment by mpapis** [comment]
hmm, do you have any kind of environmnet variables that could influence library load? can I see `env | sort`?

**Comment by mat813** [comment]
```
$ env|sort
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.gmZHuiXGCV/Render
BLOCKSIZE=K
CLICOLOR_FORCE=xterm-color
COLORFGBG=12;8
CVS_RSH=ssh
DBUS_LAUNCHD_SESSION_BUS_SOCKET=/private/tmp/com.apple.launchd.zb98paU0up/unix_domain_listener
DISPLAY=/private/tmp/com.apple.launchd.Z09icSAsEL/org.macosforge.xquartz:0
EDITOR=vim
GEMEDITOR=mate
GEM_EDITOR=mate
GEM_HOME=/Users/mat/.rvm/gems/ruby-2.2.1
GEM_PATH=/Users/mat/.rvm/gems/ruby-2.2.1:/Users/mat/.rvm/gems/ruby-2.2.1@global
GPG_AGENT_INFO=/private/tmp/com.apple.launchd.oPFfYWPHGz/Listeners_agent
HISTCONTROL=ignoreboth:erasedups
HISTFILE=/Users/mat/.bash_history
HISTFILESIZE=50000
HISTSIZE=50000
HOME=/Users/mat
INPUTRC=/Users/mat/.absoconf/abso-files/files/inputrc
IRBRC=/Users/mat/.rvm/rubies/ruby-2.2.1/.irbrc
ITERM_PROFILE=UTF-8 Dark
ITERM_SESSION_ID=w0t6p1:873F8C02-3D9B-4198-B3CC-B034D5AE4FD6
LANG=fr_FR.UTF-8
LESS=-r -e -i -P?f%f :<STDIN> .?m (%i/%m) .?lt-- lignes %lt-%lb?L/%L. .?e-- [FIN] ?x-- Suivant\: %x .:-- ?pB%pB\%..%t
LOGNAME=mat
MANPATH=/opt/local/man:/opt/local/share/man:
MY_RUBY_HOME=/Users/mat/.rvm/rubies/ruby-2.2.1
OLDPWD=/Users/mat/work/show/app/assets/stylesheets
P4CONFIG=.p4config
PACKAGES=/usr/ports/packages/153.0i386-default/
PACKAGESITE=http://pkg.absolight.net/153.0i386-default/
PAGER=less
PATH=/Users/mat/.rvm/gems/ruby-2.2.1/bin:/Users/mat/.rvm/gems/ruby-2.2.1@global/bin:/Users/mat/.rvm/rubies/ruby-2.2.1/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/mat/bin:/Users/mat/.rvm/bin:/opt/local/lib/postgresql94/bin/
PORTS_DBDRIVER=bdb1_btree
PWD=/Users/mat/work/show
RSYNC_RSH=ssh
RUBY_VERSION=ruby-2.2.1
SHELL=/bin/bash
SHLVL=1
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TMPDIR=/var/folders/rr/tk43zywj74ndnl6lmc6m8g680000gn/T/
USER=mat
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x1
_system_arch=x86_64
_system_name=OSX
_system_type=Darwin
_system_version=10.11
rvm_bin_path=/Users/mat/.rvm/bin
rvm_path=/Users/mat/.rvm
rvm_prefix=/Users/mat
rvm_version=1.26.11 (latest)
```

**Comment by mpapis** [comment]
would you be up for an experiment? we would need to build another 2.2.4 ruby manually from source, in current state it's really hard to say if the error comes from rvm or from ruby.

if you are up for this:
- run the installation from rvm: `rvm --debug install 2.2.4` - let it run to the end
- repeat the same steps outside of rvm (best with a new target installation path)

you will see in the rubygems step if it's rvm's or ruby's fault ... I know it's a lot but it's the fastest way to find out where the error happens. Also please write down all the steps so we can open a ticket for ruby if it's not on rvm.

**Comment by pkuczynski** [comment]
Closing due lack of response...
