### ISSUE TITLE
RVM install fails with multiple errors on El Capitan

### ISSUE THREAD

**Issue by tmlbl** [rvm/rvm#3756]
Seems to be related to:
#3736
#3734

```bash
tim$ curl -L https://get.rvm.io | bash -s stable --rails
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    186      0 --:--:-- --:--:-- --:--:--   186
100 22865  100 22865    0     0  13452      0  0:00:01  0:00:01 --:--:--  122k
Downloading https://github.com/rvm/rvm/archive/1.27.0.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc',
but no GPG software exists to validate it, skipping.

Upgrading the RVM installation in /Users/tim/.rvm/
    RVM PATH line found in /Users/tim/.mkshrc /Users/tim/.bashrc /Users/tim/.zshrc.
    RVM sourcing line found in /Users/tim/.zlogin.
    RVM sourcing line not found for Bash, rerun this command with '--auto-dotfiles' flag to fix it.
    Installing rvm gem in 1 gemsetsError running 'command gem install /Users/tim/.rvm/gem-cache/rvm-1.11.3.9.gem --local --no-ri --no-rdoc',
showing last 15 lines of /Users/tim/.rvm/log/1473913022_ruby-2.3.0/gem.install.rvm->=1.11.3.9.log
[2016-09-14 21:17:02] command
current path: /Users/tim/.rvm/src/rvm
GEM_HOME=/Users/tim/.rvm/gems/ruby-2.3.0@global
PATH=/Users/tim/.rvm/gems/ruby-2.3.0@global/bin:/Users/tim/.rvm/rubies/ruby-2.3.0/bin:/Users/tim/.rvm/bin:/usr/local/google-cloud-sdk/bin:/Users/tim/go/bin:/usr/local/google-cloud-sdk/bin:/Users/tim/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/TeX/texbin:/usr/local/google-cloud-sdk/bin:/Users/tim/go/bin
GEM_PATH=/Users/tim/.rvm/gems/ruby-2.3.0@global
command(7): command gem install /Users/tim/.rvm/gem-cache/rvm-1.11.3.9.gem --local --no-ri --no-rdoc
+ ./scripts/functions/utility_logging : __rvm_log_dotted()  210 > gem install /Users/tim/.rvm/gem-cache/rvm-1.11.3.9.gem --local --no-ri --no-rdoc
ERROR:  Loading command: install (LoadError)
	cannot load such file -- date
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
.
    Installing gem-wrappers gem in 1 gemsetsError running 'command gem install /Users/tim/.rvm/gem-cache/gem-wrappers-1.2.7.gem --local --no-ri --no-rdoc',
showing last 15 lines of /Users/tim/.rvm/log/1473913023_ruby-2.3.0/gem.install.gem-wrappers->=1.2.7.log
[2016-09-14 21:17:03] command
current path: /Users/tim/.rvm/src/rvm
GEM_HOME=/Users/tim/.rvm/gems/ruby-2.3.0@global
PATH=/Users/tim/.rvm/gems/ruby-2.3.0@global/bin:/Users/tim/.rvm/rubies/ruby-2.3.0/bin:/Users/tim/.rvm/bin:/usr/local/google-cloud-sdk/bin:/Users/tim/go/bin:/usr/local/google-cloud-sdk/bin:/Users/tim/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/TeX/texbin:/usr/local/google-cloud-sdk/bin:/Users/tim/go/bin
GEM_PATH=/Users/tim/.rvm/gems/ruby-2.3.0@global
command(7): command gem install /Users/tim/.rvm/gem-cache/gem-wrappers-1.2.7.gem --local --no-ri --no-rdoc
+ ./scripts/functions/utility_logging : __rvm_log_dotted()  210 > gem install /Users/tim/.rvm/gem-cache/gem-wrappers-1.2.7.gem --local --no-ri --no-rdoc
ERROR:  Loading command: install (LoadError)
	cannot load such file -- date
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
.
    Regenerating gem wrappers in 1 rubiesERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command wrappers
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command wrappers
.
Upgrade of RVM in /Users/tim/.rvm/ is complete.

# Tim Lebel,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:


  * WARNING: You have '~/.profile' file, you might want to load it,
    to do that add the following line to '/Users/tim/.bash_profile':

      source ~/.profile

  * No new notes to display.

rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
Already installed ruby-2.3.0.
To reinstall use:

    rvm reinstall ruby-2.3.0

/Users/tim/.rvm/bin/rvm: line 66: shell_session_update: command not found
Creating alias default for ruby-2.3.0....
ERROR:  Loading command: install (LoadError)
	cannot load such file -- date
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
bash: line 856: shell_session_update: command not found
```

**Comment by seifer72** [comment]
i have the same problem :( 
When try gem install 
```
ERROR:  Loading command: update (LoadError)
	cannot load such file -- date
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

```
Check .rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/  and there file date does not exist :(
os El Capitan, iterm2, zsh

**Comment by pkuczynski** [comment]
Try

```
rvm get master
rvm install ruby 2.3.1
```

**Comment by seifer72** [comment]
did not help :( 
gem env
`RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/rts/.rvm/gems/ruby-2.3.1
  - USER INSTALLATION DIRECTORY: /Users/rts/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/rts/.rvm/rubies/ruby-2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/rts/.rvm/gems/ruby-2.3.1/bin
  - SPEC CACHE DIRECTORY: /Users/rts/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/rts/.rvm/gems/ruby-2.3.1
     - /Users/rts/.rvm/gems/ruby-2.3.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000`
<img width="1154" alt="2016-09-15 17 46 54" src="https://cloud.githubusercontent.com/assets/3541140/18554293/d8b01886-7b74-11e6-82b1-cbb2f405dec9.png">
<img width="1278" alt="2016-09-15 17 47 33" src="https://cloud.githubusercontent.com/assets/3541140/18554312/e7f71c2c-7b74-11e6-986c-3608ce0d2c28.png">

**Comment by duffyjp** [comment]
Mine is similarly broken following an ```implode``` a few hours ago.    I've imploded and reinstalled stable, dev, multiple ruby versions a bunch of times.  Sometimes ruby appears to install okay, sometimes I get the errors shown on the first post.  No matter what I try though,  ```gem``` is totally broken when using rvm.  After imploding, I can use my system ruby (2.0.0) and update rubygems manually from the old fashioned download and use ```gem``` to install stuff systemwide just fine.  

> El Cap 10.11.6


```
🌶  anketto 15:15$ rvm list rubies

rvm rubies

 * ruby-2.3.0 [ x86_64 ]
=> ruby-2.3.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

🌶  anketto 15:15$ gem
/Users/jpd800/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/config_file.rb:334:in `load_file': private method `load' called for Psych:Module (NoMethodError)
	from /Users/jpd800/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/config_file.rb:199:in `initialize'
	from /Users/jpd800/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/gem_runner.rb:75:in `new'
	from /Users/jpd800/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/gem_runner.rb:75:in `do_configuration'
	from /Users/jpd800/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/gem_runner.rb:40:in `run'
	from /Users/jpd800/.rvm/rubies/ruby-2.3.1/bin/gem:21:in `<main>'
```

**Comment by pkuczynski** [comment]
Indeed there is an issue with 2.3.x which I am working on with @mpapis. Stay tuned.

**Comment by ohwutup** [comment]
Seeing this building ruby from source, so not just an `rvm` issue!

**Comment by Stupac** [comment]
was there every a solution reached for this issue?
