### ISSUE TITLE
Error on installing binary 2.3.1 on Mac OS X

### ISSUE THREAD

**Issue by 907th** [rvm/rvm#3759]
After installing binary Ruby 2.3.1 version on Mac OS X I can not execute `gem` command due to error:

```
~ gem list
/Users/laise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/config_file.rb:334:in `load_file': private method `load' called for Psych:Module (NoMethodError)
        from /Users/laise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/config_file.rb:199:in `initialize'
        from /Users/laise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/gem_runner.rb:75:in `new'
        from /Users/laise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/gem_runner.rb:75:in `do_configuration'
        from /Users/laise/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/gem_runner.rb:40:in `run'
        from /Users/laise/.rvm/rubies/ruby-2.3.1/bin/gem:21:in `<main>'
```

PS. Installation from source (with `--disable-binary`) works well!
PPS. rvm 1.27.0, OS X 10.11.6

**Comment by 907th** [comment]
cc @pkuczynski

**Comment by pkuczynski** [comment]
Indeed there is a problem with the binary for 2.3.0 and 2.3.1. Your comment pointed me to a possible source of the issue: SMF which we use to prepare binary build somehow breaks recognition of libyaml. We are working on solution. In the meantime I removed the binary package...

**Comment by ohwutup** [comment]
FYI: I am seeing this error trying to compile/build ruby from source. So I don't believe this is an rvm specific issue :(.

**Comment by rjrobinson** [comment]
Yea. Im getting this error 

```shell
rvm install 2.3.1                                                                                                                               bb-coveralls
ruby-2.3.1 - #removing src/ruby-2.3.1 - please wait
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/osx/10.12/x86_64/ruby-2.3.1.tar.bz2
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
ruby-2.3.1 - #configure
ruby-2.3.1 - #download
ruby-2.3.1 - #validate archive
ruby-2.3.1 - #extract
ruby-2.3.1 - #validate binary
Libraries missing for ruby-2.3.1: /Users/travis/.rvm/rubies/ruby-2.3.1/lib/libruby.2.3.0.dylib. Refer to your system manual for installing libraries
Mounting remote ruby failed with status 10, trying to compile.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/rrobin244/.rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
ruby-2.3.1 - #extracting ruby-2.3.1 to /Users/rrobin244/.rvm/src/ruby-2.3.1 - please wait
ruby-2.3.1 - #configuring - please wait
ruby-2.3.1 - #post-configuration - please wait
ruby-2.3.1 - #compiling - please wait
Error running '__rvm_make -j 1',
showing last 15 lines of /Users/rrobin244/.rvm/log/1480537373_ruby-2.3.1/make.log
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:18:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2267:21: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at ossl_ssl.c:85:14) []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:18:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
6 warnings and 9 errors generated.
make[2]: *** [ossl_ssl.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make: *** [build-ext] Error 2
+__rvm_make:0> return 2
There has been an error while running make. Halting the installation.
```

**Comment by rjrobinson** [comment]
But mine if for MacOS

**Comment by pkuczynski** [comment]
Can you try with

```
rvm get head
rvm install 2.3.1
```

and if it fails gist `make.log`

**Comment by rjrobinson** [comment]
Same issue. 

here is the gist

https://gist.github.com/rjrobinson/cdbd11080203e0b950a139cab65fe7f1

**Comment by rjrobinson** [comment]
Also... not sure if it is related. 
I'm using iterm2  and also using RubyMine. 

In iterm 2 RVM runs just fine, 

but in RubyMine, which loads the same shell, rvm doesnt work at all. 
For some reason it defaults to system ruby, and then gives me this error when I run rvm use. 
```shell
rvm use 2.2.5                                                                                                                                                                  
RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.
```

**Comment by yemster** [comment]
Same issue.
Any solutions?

**Comment by philoserf** [comment]
Hmm? Debug output extract around the validate test. Seems to be an issue when installing from binary.

```
ruby-2.1.10 - #extract
__rvm_package_extract:2: /Users/===>markayers<===/.rvm/archives/bin-ruby-2.1.10.tar.bz2 /Users/markayers/.rvm/rubies/ruby-2.1.10
ruby-2.1.10 - #validate binary
Libraries missing for ruby-2.1.10: /Users/====>travis<===/.rvm/rubies/ruby-2.1.10/lib/libruby.2.1.0.dylib. Refer to your system manual for installing libraries
Mounting remote ruby failed with status 10, trying to compile.
```

**Comment by pkuczynski** [comment]
@philoserf this issue should not exist if you get latest master `rvm get master` and then try to install again

**Comment by pkuczynski** [comment]
@rjrobinson I am using IntelliJ and RubyMine with RVM without a problem. Seems that you missing loading rvm into shell. Could you please check RubyMine preferences and search for 'Tools > Terminal'. Check what you have listed in Shell path

**Comment by pkuczynski** [comment]
@rjrobinson your issue is connected with the fact that you have openssl098 installed. Could you please verify?

**Comment by pkuczynski** [comment]
I am closing this due lack of feedback from the original reporter. If anyone still has the issue after `rvm get master`, please let me know or open a new issue.

**Comment by philoserf** [comment]
The change I saw after `rvm get master` is that `ram install ruby-x.y.z` never finds a binary to attempt. This that code path is not exercised.

**Comment by jannewaren** [comment]
Just for the record to help anyone in the future, I had this problem on the newest version of RVM (1.29.2 on MacOS Sierra) just now, and was finally able to solve it by `brew uninstall --force openssl098`

**Comment by 907th** [comment]
@pkuczynski My original report was related to broken osx binaries (only). But now the discussion went far away from original problem.

**Comment by joel1di1** [comment]
Tx @jannewaren,
I had the issue and uninstall openssl098 worked!
