### ISSUE TITLE
Error after installing 2.3.1 from source on Ubuntu

### ISSUE THREAD

**Issue by rchekaluk** [rvm/rvm#3760]
Issue after installing Ruby 2.3.1 on Ubuntu 16.04.1 LTS (rvm 1.27.0). Related to https://github.com/rvm/rvm/issues/3759?

```
$ gem list
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': incompatible library version - /usr/local/rvm/gems/ruby-2.3.1/gems/psych-2.1.1/lib/psych.so (LoadError)
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from /usr/local/rvm/gems/ruby-2.3.1/gems/psych-2.1.1/lib/psych.rb:7:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/yaml.rb:6:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems.rb:628:in `load_yaml'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/config_file.rb:326:in `load_file'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/config_file.rb:198:in `initialize'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/gem_runner.rb:75:in `new'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/gem_runner.rb:75:in `do_configuration'
    from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/gem_runner.rb:40:in `run'
    from /usr/local/rvm/rubies/ruby-2.3.1/bin/gem:21:in `<main>'
```

This stacktrace occurred after installing Ruby 2.3.1 using `--disable-binary`:

```
$ rvm --disable-binary install 2.3.1
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.5/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.5'.
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.7M  100 13.7M    0     0  7427k      0  0:00:01  0:00:01 --:--:-- 7425k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.1 - #extracting ruby-2.3.1 to /usr/local/rvm/src/ruby-2.3.1....
ruby-2.3.1 - #configuring...........................................................
ruby-2.3.1 - #post-configuration..
ruby-2.3.1 - #compiling.............................................................................|
ruby-2.3.1 - #installing.................
ruby-2.3.1 - #making binaries executable..
Installed rubygems 2.5.1 is newer than 2.4.8 provided with installed ruby, skipping installation, use --force to force installation.
ruby-2.3.1 - #gemset created /usr/local/rvm/gems/ruby-2.3.1@global
ruby-2.3.1 - #importing gemset /usr/local/rvm/gemsets/global.gems...................................|
ruby-2.3.1 - #generating global wrappers........
ruby-2.3.1 - #gemset created /usr/local/rvm/gems/ruby-2.3.1
ruby-2.3.1 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.3.1 - #generating default wrappers..........
ruby-2.3.1 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-2.3.1 - #complete 
Ruby was built without documentation, to build it run: rvm docs generate-ri
```

**Comment by pkuczynski** [comment]
Can you check if you have libyaml installed?

**Comment by raelgc** [comment]
Hi @rchekaluk and thank you for raising this.

Can you, please, try with our [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm)?

**Comment by rchekaluk** [comment]
Using [ubuntu_rvm](https://github.com/rvm/ubuntu_rvm) seems to work.  (why is this option not mentioned in [installation guide](https://rvm.io/rvm/install)?)

I first removed RVM using these blogs (why no uninstall guide in [RVM docs](https://rvm.io/rvm)?)
* https://richonrails.com/articles/uninstalling-rvm
* https://mkoby.com/2011/06/03/completely-removing-rvm/

I then installed RVM using ubuntu_rvm, and successfully installed `ruby-2.3.1`:
```
$ rvm install 2.3.1
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-2.3.1.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
ruby-2.3.1 - #configure
ruby-2.3.1 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.8M  100 24.8M    0     0  10.8M      0  0:00:02  0:00:02 --:--:-- 10.8M
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.1 - #validate archive
ruby-2.3.1 - #extract
ruby-2.3.1 - #validate binary
ruby-2.3.1 - #setup
ruby-2.3.1 - #gemset created /home/REDACTED/.rvm/gems/ruby-2.3.1@global
ruby-2.3.1 - #importing gemset /usr/share/rvm/gemsets/global.gems..............................
ruby-2.3.1 - #generating global wrappers........
ruby-2.3.1 - #gemset created /home/REDACTED/.rvm/gems/ruby-2.3.1
ruby-2.3.1 - #importing gemsetfile /usr/share/rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.3.1 - #generating default wrappers........

$ rvm current
ruby-2.3.1

$ rvm list

rvm rubies

=* ruby-2.3.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by raelgc** [comment]
@rchekaluk In fact, we're really missing to mention this package in the install page :(

**Comment by pkuczynski** [comment]
I added info about the ubuntu package to the readme and I will add it to the rvm.io soon

**Comment by pkuczynski** [comment]
https://github.com/rvm/rvm-site/issues/295
