### ISSUE TITLE
Allow option for forcing RVM to attempt to install old versions of ruby

### ISSUE THREAD

**Issue by mdotterer** [rvm/rvm#3936]
## Description

  I am able to successfully install ruby 1.8.6 on OSX 10.12 through some machinations, but I have to resort to patching scripts/functions/build_config_system in order to get RVM to even try to install. While I don't expect the install for such an old version of ruby to be maintained, I would like to have a command line option to bypass the version check and try anyway.

## Steps to reproduce

 1. `rvm get stable`
 2. `sudo port install gcc44`
 3. `CC=/opt/local/bin/gcc-apple-4.2 rvm reinstall 1.8.6 --patch PATHTO/ruby186_virtual_timer.patch`

## Expected behavior

RVM at tries to install ruby 1.8.6 

## Actual behavior

RVM errors out immediately: 

> RVM does not know how to build working ruby-1.8.6-p420 on OSX 10.12,
> if you know please let us know by opening a ticket with instructions here:
> 
>    https://github.com/rvm/rvm/issues

## Environment info

OSX 10.12

**Comment by mwlang** [comment]
Just ran into this problem myself...Upgraded OS from Mavericks to Sierra and Ruby 1.8.6 worked for the most part except for scripts requiring readline (Rails 1.x script/console, for example).  Followed the usual dance of uninstalling to reinstall and ended up surprised 1.8.6 couldn't be recompiled and installed.

~~~bash
10:47:39:2.x >> script/console
Loading development environment.
Readline was unable to be required, if you need completion or history install readline then reinstall the ruby.
You may follow 'rvm notes' for dependencies and/or read the docs page https://rvm.io/packages/readline/ . Be sure you 'rvm remove X ; rvm install X' to re-compile your ruby with readline support after obtaining the readline libraries.
dlopen(/Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/i686-darwin13.3.0/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/i686-darwin13.3.0/readline.bundle
  Reason: image not found - /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/i686-darwin13.3.0/readline.bundle
/Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/i686-darwin13.3.0/readline.bundle: dlopen(/Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/i686-darwin13.3.0/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib (LoadError)
  Referenced from: /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/i686-darwin13.3.0/readline.bundle
  Reason: image not found - /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/i686-darwin13.3.0/readline.bundle
	from /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/irb/completion.rb:10
	from /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/irb/init.rb:252:in `require'
	from /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/irb/init.rb:252:in `load_modules'
	from /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/irb/init.rb:250:in `each'
	from /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/irb/init.rb:250:in `load_modules'
	from /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/irb/init.rb:21:in `setup'
	from /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/lib/ruby/1.8/irb.rb:54:in `start'
	from /Users/mwlang/.rvm/rubies/ruby-1.8.6-p420/bin/irb:13
10:47:43:2.x >> rvm list

rvm rubies

   jruby-1.7.19 [ x86_64 ]
   rbx-2.5.8 [ x86_64 ]
   ree-1.8.7-2012.02 [ i686 ]
=> ruby-1.8.6-p420 [ i686 ]
   ruby-1.8.7-head [ i686 ]
   ruby-1.8.7-p374 [ i686 ]
   ruby-1.9.3-p392 [ x86_64 ]
   ruby-2.0.0-p481 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
   ruby-2.2.4 [ x86_64 ]
 * ruby-2.3.3 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

10:47:55:2.x >> brew install readline
Warning: readline is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
10:48:08:2.x >> rvm uninstall ruby-1.8.6-p420
ruby-1.8.6-p420 - #removing rubies/ruby-1.8.6-p420..
10:48:27:2.x >> rvm install 1.8.6-p420
Warning, new version of rvm available '1.29.1', you are using older version '1.28.0'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-1.8.6-p420.
It is not possible to build movable binaries for rubies 1.8-1.9.2, but you can do it for your system only.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.

RVM does not know how to build working ruby-1.8.6-p420 on OSX 10.12,
if you know please let us know by opening a ticket with instructions here:

    https://github.com/rvm/rvm/issues

10:48:41:2.x >> rvm install 1.8.6
Warning, new version of rvm available '1.29.1', you are using older version '1.28.0'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-1.8.6-p420.
It is not possible to build movable binaries for rubies 1.8-1.9.2, but you can do it for your system only.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.

RVM does not know how to build working ruby-1.8.6-p420 on OSX 10.12,
if you know please let us know by opening a ticket with instructions here:

    https://github.com/rvm/rvm/issues
~~~

**Comment by mwlang** [comment]
So what are the steps to side-stepping rvm's guard against installing older Rubies so I can patch and install?

**Comment by mdotterer** [comment]
What has worked for me is using MacPorts to install gcc44, and then applying the attached to remove the safegaurd with:
  `patch ~/.rvm/scripts/functions/build_config_system rvm-allow-186.patch`
[rvm-allow-186.patch.zip](https://github.com/rvm/rvm/files/800011/rvm-allow-186.patch.zip)

So far we haven't had any luck with Homebrew, just MacPorts. Using Homebrew to install an older gcc and then attempting to install still compiles, but then there is a segfault somewhere in gem install.

**Comment by mwlang** [comment]
@mdotterer thanks for that, but I don't think going down the macports route is viable for me.  I was able to get back to working 1.8.6 by restoring the binaries from a backup.

**Comment by pkuczynski** [comment]
We could definitely add `ignore_version_guard` switch to help you get going. It would be good if you could then share back the patches as PR so other people can benefit of this

**Comment by pkuczynski** [comment]
@mdotterer and @mwlang do you still want to work ok this
