### ISSUE TITLE
Error running '__rvm_make install',

### ISSUE THREAD

**Issue by DanielViglione** [rvm/rvm#4216]
I have been met with many errors while trying to install rvm on a new MacBook Air with OSX Sierra:

$ rvm install 2.4.1

Error running '__rvm_make install',
please read /Users/viggy/.rvm/log/1509209087_ruby-2.4.1/install.log
There has been an error while running make install. Halting the installation.

$ less /Users/viggy/.rvm/log/1509209087_ruby-2.4.1/install.log

installing binary commands:   /Users/viggy/.rvm/rubies/ruby-2.4.1/bin
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Users/viggy/.rvm/src/ruby-2.4.1/libruby.2.4.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Users/viggy/.rvm/src/ruby-2.4.1/libruby.2.4.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

make: *** [do-install-nodoc] Abort trap: 6
++ return 2

**Comment by DanielViglione** [comment]
Keep in mind I already do iOS development so I have command line tools already:

$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

**Comment by DanielViglione** [comment]
But apparent the command line tools were not installed:

    xcode-select --install

After installing them, no error.

**Comment by Merovex** [comment]
I ran into the same error, and @DanielViglione's solution (xcode-select) fixed for me.

**Comment by Connieh1** [comment]
Thanks Daniel!

**Comment by DaZhuzhu** [comment]
Thanks Daniel!!!I have solouted my problem!

**Comment by chabely** [comment]
Hello I'm getting the same error: Error running '__rvm_make install' 
And the log is: installing default gems:      /Users/isabel.crescencio/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.2.6
                              io-console 0.4.3
                              json 1.8.1
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
./tool/rbinstall.rb:714:in `rescue in block in <main>': uninitialized constant LoadErroe (NameError)
	from ./tool/rbinstall.rb:712:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-nodoc] Error 1
+__rvm_make:0> return 2


I had tried to apply the patch:
rvm install 2.2.1 --patch patchDown/2.2.1-typo.patch
 but it didn't work  due to it shows me:
Error running '__rvm_patch -F 25 -p1 -N -f -i patchDown/2.2.1-typo.patch'

Anybody has some idea?

**Comment by Connieh1** [comment]
https://github.com/rvm/rvm/issues/4216#issuecomment-340205973

**Comment by Connieh1** [comment]
See this: https://github.com/rvm/rvm/issues/4216#issuecomment-340205973

**Comment by chabely** [comment]
I've already done but it didn't work. :(
