### ISSUE TITLE
Rake warnings with Ruby 2.5.0 and RVM

### ISSUE THREAD

**Issue by DanielKehoe** [rvm/rvm#4301]
## Description

With Ruby 2.5.0, when I build a new Rails 5.2.0.rc1 app, I get many warnings indicating "already initialized constant" when I run a rake command.

## Steps to reproduce
```
 1. $ \curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles
 2. $ echo "source $HOME/.rvm/scripts/rvm" >> ~/.bash_profile
 3. $ rvm -v
      rvm 1.29.3 (master)
4. $ source ~/.rvm/scripts/rvm
5. $ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
6. $ rvm use ruby-2.5.0@rails5.2 --create
7. $ gem install rails --pre
8. $ rails -v
Rails 5.2.0.rc1
9. $ rails new myapp
10. $ cd myapp
11. $ bundle install
12. $ rails -T
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/danielkehoe/workspace/wip/myapp/bin/spring:8:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
13. $ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
```
Seems the system Ruby is used.

```
14. close and reopen terminal
15. $ rails -T
 (got expected output)
16. $ rake -v
 (warnings see below)
```
## Expected behavior

Expected to see rake output without warnings.

## Actual behavior
```
$ rake -v
/Users/danielkehoe/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/lib/rake/file_utils.rb:10: warning: already initialized constant FileUtils::RUBY
/Users/danielkehoe/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/file_utils.rb:10: warning: previous definition of RUBY was here
/Users/danielkehoe/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/lib/rake/file_utils.rb:109: warning: already initialized constant FileUtils::LN_SUPPORTED
```

Continues with many more warnings, see gist:
https://gist.github.com/DanielKehoe/21f40ea1bd1b2d2eeb7a809b83ba2909

## Environment info
```
$ rvm info

ruby-2.5.0:

  system:
    uname:        "Darwin Daniels-MacBook-Air.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:          "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"
    remote_path:  "osx/10.12/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "1 hour 28 seconds ago"
    path:         "/Users/danielkehoe/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.5.0p0"
    date:         "2017-12-25"
    platform:     "x86_64-darwin16"
    patchlevel:   "2017-12-25 revision 61468"
    full_version: "ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]"

  homes:
    gem:          "/Users/danielkehoe/.rvm/gems/ruby-2.5.0"
    ruby:         "/Users/danielkehoe/.rvm/rubies/ruby-2.5.0"

  binaries:
    ruby:         "/Users/danielkehoe/.rvm/rubies/ruby-2.5.0/bin/ruby"
    irb:          "/Users/danielkehoe/.rvm/rubies/ruby-2.5.0/bin/irb"
    gem:          "/Users/danielkehoe/.rvm/rubies/ruby-2.5.0/bin/gem"
    rake:         "/Users/danielkehoe/.rvm/gems/ruby-2.5.0@global/bin/rake"

  environment:
    PATH:         "/Users/danielkehoe/.rvm/gems/ruby-2.5.0/bin:/Users/danielkehoe/.rvm/gems/ruby-2.5.0@global/bin:/Users/danielkehoe/.rvm/rubies/ruby-2.5.0/bin:/Users/danielkehoe/.rvm/bin:/usr/local/bin:/Users/danielkehoe/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    GEM_HOME:     "/Users/danielkehoe/.rvm/gems/ruby-2.5.0"
    GEM_PATH:     "/Users/danielkehoe/.rvm/gems/ruby-2.5.0:/Users/danielkehoe/.rvm/gems/ruby-2.5.0@global"
    MY_RUBY_HOME: "/Users/danielkehoe/.rvm/rubies/ruby-2.5.0"
    IRBRC:        "/Users/danielkehoe/.rvm/rubies/ruby-2.5.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by DanielKehoe** [comment]
Same problem referenced in a Rake issue and described as an RVM issue: https://github.com/ruby/rake/issues/248

**Comment by mpapis** [comment]
this is caused by `bootsnap` using `rails new myapp --skip-bootsnap` I can not reproduce it.
