### ISSUE TITLE
`bundle` and `bundler` being treated differently in RVM ? 

### ISSUE THREAD

**Issue by equivalent** [rvm/rvm#4324]
I had this interesting bug in Codeship 3 days ago where suddenly (with no change on our side) the Codeship was faling on this setup  script (so during VM preparation, before the actual test was executed):

```
rvm use 2.2.7
gem install bundler -v 1.16.1
bundler config github.com "my-bot-user:secretpassword4"    # < this will cause an error
```

Error:

````
/home/rof/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:231:in `search_for': Unable to resolve dependency: user requested 'executable-hooks (= 1.4.2)' (Gem::UnsatisfiableDependencyError) from /home/rof/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:283:in `block in sort_dependencies' from /home/rof/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:277:in `each' from /home/rof/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:277:in `sort_by' from /home/rof/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:277:in `with_index' from /home/rof/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/resolver.rb:277:in `sort_dependencies' from /home/rof/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
````

With that failing command I was just trying to configure bunder `bundler config` for  https login for user `my-bot-usser` with secret token/password `secretpassword4` on platform `github.com` (so I can clone private repos)

now after many hours spent on this if I change the script to : 

```
rvm use 2.2.7
gem install bundler -v 1.16.1
bundle config github.com "my-bot-user:secretpassword4"  
# ...
```

it will work !  (in the script word `bundler` was changed to `bundle`)

From what I understand `bundler` and `bundle` are alias (bundler beeing the tool name and bundle beeing execution command as in `bundle` something with `bundler`) 

so it seems that the RVM  has something configured around hardcoded string `bundle` that is not configured around `bundler` ? 

I'm just guessing here. Just wanted to raise this with you guys may be worth checking out ;).  My problems are solved. And anyone googling this will have a solution discussion.

Thank you Marko Locher from Codeship support for pointing this out !

Thx

**Comment by EdDeAlmeidaJr** [comment]
Having the same issue here!
