### ISSUE TITLE
Can't install ruby-2.2.x in Centos 6.9 from rvm master without rvmsudo

### ISSUE THREAD

**Issue by BrianHawley** [rvm/rvm#4358]
## Description

After updating rvm to master with rvmsudo (see #4356), I try to install a ruby version without rvmsudo, and it fails, complaining about a file in the current ruby version's directory - not the version to be installed. Seen in Centos 6.9 and 7.4.1708.

## Steps to reproduce

```sh
rvmsudo rvm get master
rvm install ruby-2.2.10
```

## Expected behavior

I expect ruby-2.2.10 to be installed without errors.

## Actual behavior

* [command](https://gist.github.com/BrianHawley/bec175b65b86fd7f154345a638a9e400)
* [install.log](https://gist.github.com/BrianHawley/13dcbed80e8c12519eb3144cb644585f)

The error is at the end of install.log:
```
./tool/rbinstall.rb:728:in `chmod': Operation not permitted @ chmod_internal - /usr/local/rvm/gems/ruby-2.4.3/ (Errno::EPERM)
	from ./tool/rbinstall.rb:728:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-nodoc] Error 1
++ return 2
```

## Environment info

```
ruby-2.4.3:

  system:
    uname:        "Linux oceans-ci02.qa.sf.verticalresponse.com 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "CentOS"
    version:      "6"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.1.2(2)-release (x86_64-redhat-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "centos/6/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "17 hours 44 minutes 29 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.3p205"
    date:         "2017-12-14"
    platform:     "x86_64-linux"
    patchlevel:   "2017-12-14 revision 61247"
    full_version: "ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-2.4.3"
    ruby:         "/usr/local/rvm/rubies/ruby-2.4.3"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-2.4.3/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-2.4.3/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-2.4.3/bin/gem"
    rake:         "/usr/local/rvm/gems/ruby-2.4.3@global/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-2.4.3/bin:/usr/local/rvm/gems/ruby-2.4.3@global/bin:/usr/local/rvm/rubies/ruby-2.4.3/bin:/usr/lib64/qt-3.3/bin:/usr/pgsql-9.2/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/rvm/bin:/opt/sites/bin"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-2.4.3"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-2.4.3:/usr/local/rvm/gems/ruby-2.4.3@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.4.3"
    IRBRC:        "/usr/local/rvm/rubies/ruby-2.4.3/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by BrianHawley** [comment]
OK, weird, I tried ruby-2.3.7, ruby-2.4.4, and ruby-2.5.1, and they all installed without this error. And then afterwards, when I tried to install ruby-2.2.10 again, it worked. I'm going to try other machines with the same setup.

**Comment by BrianHawley** [comment]
Checked on a Centos 7.4.1708 box in a fresh session, and it failed with the same failure.

**Comment by BrianHawley** [comment]
OK, figured it out: ruby-2.2.0 to 2.2.4 installs correctly, but 2.2.5 to 2.2.10 doesn't. Looks like the ruby 798 and rvm #3259 patch needs to apply to later 2.2.x versions. Making a PR.

**Comment by BrianHawley** [comment]
Note that it doesn't fail on my single-user rvm install. I think it's limited to multi-user rvm.
