### ISSUE TITLE
Fixing the CI on macOS, or remove it

### ISSUE THREAD

**Issue by eregon** [rvm/rvm#4579]
The CI on macOS has been failing for a long time.
This makes it hard to notice if a new test fails, i.e., it requires to check the build page every time instead of seeing the whole CI as green.

I think the macOS CI should either be fixed, or removed, as currently it's useless and takes more time.

The problem seems to be that there are too many upgrades with Homebrew which take a very long time.
e.g. https://travis-ci.org/rvm/rvm/jobs/480017710

Could you find out what's triggering these updates, most of which don't seem needed, and disable that?

**Comment by eregon** [comment]
`rvm-test/long/named_ruby_and_gemsets_comment_test.sh` refers to an ancient Ruby version, 1.8.7, maybe it's time to update that one to a supported Ruby version?

It seems installing many Homebrew packages start to get installed from
```
Checking requirements for osx.
Do not know how to check/install gcc 'gcc'.
Installing requirements for osx.
Updating system..........
Installing required packages: zlib....
```
and Homebrew goes in a frenzy updating apparently the whole system. Here is one example:
```
==> Upgrading postgis 
==> Installing dependencies for postgis: cfitsio, popt, epsilon, expat, freexl, xz, python, geos, giflib, gmp, isl, mpfr, libmpc, gcc, szip, hdf5, jpeg, jasper, json-c, libxml2, libdap, libtiff, proj, libgeotiff, libpng, libpq, libspatialite, netcdf, openblas, numpy, pcre, freetype, fontconfig, libidn, podofo, glib, pixman, cairo, little-cms2, nspr, nss, openjpeg, qt, poppler, unixodbc, webp, xerces-c, zstd, gdal, icu4c, postgresql, boost, eigen, cgal and sfcgal
```
https://travis-ci.org/rvm/rvm/jobs/490477283

cc @pkuczynski

**Comment by eregon** [comment]
Quick attempt to stop updating/upgrading Homebrew in https://github.com/eregon/rvm/commit/e9a3e43315b09eda362990963171d7a25afe7e49, https://travis-ci.org/eregon/rvm/builds/490494880

**Comment by eregon** [comment]
Note that many tests currently pass on macOS, although they take a very long time to run:
https://travis-ci.org/rvm/rvm/builds/492123234
```
TEST=rvm-test/fast/* rvm-test-rvm1/*
Requirements installation failed with status: 1.
##### Processed commands 621 of 621, success tests 432 of 434, failure tests 2 of 434.

TEST=rvm-test/long/named_ruby_and_gemsets_comment_test.sh
Requirements installation failed with status: 1.
##### Processed commands 21 of 21, success tests 23 of 27, failure tests 4 of 27.

TEST=rvm-test/long/truffleruby_comment_test.sh, completely broken:
Requirements installation failed with status: 1.
##### Processed commands 5 of 5, success tests 3 of 11, failure tests 8 of 11.
```

**Comment by havenwood** [comment]
I made a PR that [updates the tf gem](https://github.com/rvm/tf/pull/9) for compatibility with modern Rubies and Gems, fwiw.

**Comment by eregon** [comment]
I'll reopen this, it fails again on master, seems related to Homebrew again:
https://github.com/rvm/rvm/actions/runs/8303793935/job/22728518663

It seems to install/update way too many packages, probably we need to tell Homebrew to not try updating anything.

**Comment by eregon** [comment]
https://github.com/rvm/rvm/actions/runs/8346161309/job/22842799319?pr=5447#step:4:9
Maybe the issue is there is no recent binary Ruby on macOS, specifically nothing in https://rvm.io/binaries/osx/12.7/

In fact from looking at the parent page, it seems the last binaries on macOS are for 10.12 :https://rvm.io/binaries/osx/10.12/x86_64/

**Comment by eregon** [comment]
```
==> Upgrading 21 dependents of upgraded formulae:
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
```
Yeah Homebrew is going wild, I'm adding an env var to skip `brew update` entirely, definitely don't want that in CI, in https://github.com/rvm/rvm/pull/5387

**Comment by eregon** [comment]
Skipping `brew update` gets to the next error, which looks like a bug in RVM:
https://github.com/rvm/rvm/actions/runs/8346843428/job/22845076656?pr=5387
```
Run source ~/.rvm/scripts/rvm && rvm use 2.7.7 --install --default && gem install tf -v '>=0.4.1'
Required ruby-2.7.7 is not installed - installing.
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/12.7/x86_64/ruby-2.7.7.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Installing requirements for osx.
Updating system|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/.
Installing required packages: automake, coreutils|/-\|/-\|.-\|/-\|/-.|.
Updating certificates bundle '/usr/local/etc/openssl@1.1/cert.pem'
Requirements installation successful.
Installing Ruby from source to: /Users/runner/.rvm/rubies/ruby-2.7.7, this may take a while depending on your cpu(s)...
ruby-2.7.7 - #downloading ruby-2.7.7, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14.1M  100 14.1M    0     0  31.2M      0 --:--:-- --:--:-- --:--:-- 31.3M
ruby-2.7.7 - #extracting ruby-2.7.7 to /Users/runner/.rvm/src/ruby-2.7.7|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.
ruby-2.7.7 - #configuring|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\.
ruby-2.7.7 - #post-configuration|/-\|.
ruby-2.7.7 - #compiling|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-.
ruby-2.7.7 - #installing|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-.
Error running '__rvm_make install',
please read /Users/runner/.rvm/log/1710866461_ruby-2.7.7/install.log
There has been an error while running make install. Halting the installation.
Gemset '' does not exist, 'rvm ruby-2.7.7 do rvm gemset create ' first, or append '--create'.
Error: Process completed with exit code 2.
```

**Comment by eregon** [comment]
> please read /Users/runner/.rvm/log/1710866461_ruby-2.7.7/install.log

Is there a way to make RVM print that log?
Or output directly instead of using a log?

**Comment by eregon** [comment]
https://github.com/rvm/rvm/actions/runs/8347051849/job/22845800653?pr=5387
```
 *** Following extensions are not compiled:
openssl:
	Could not be configured. It will not be installed.
	Check ext/openssl/mkmf.log for more details.
*** Fix the problems, then remove these directories and try again if you want.

...

 /Users/runner/.rvm/src/ruby-2.7.7/lib/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- openssl (LoadError)
	from /Users/runner/.rvm/src/ruby-2.7.7/lib/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /Users/runner/.rvm/src/ruby-2.7.7/lib/rubygems/specification.rb:2430:in `to_ruby'
	from ./tool/rbinstall.rb:846:in `block (2 levels) in install_default_gem'
	from ./tool/rbinstall.rb:279:in `open_for_install'
	from ./tool/rbinstall.rb:845:in `block in install_default_gem'
	from ./tool/rbinstall.rb:835:in `each'
	from ./tool/rbinstall.rb:835:in `install_default_gem'
	from ./tool/rbinstall.rb:799:in `block in <main>'
	from ./tool/rbinstall.rb:950:in `block in <main>'
	from ./tool/rbinstall.rb:947:in `each'
	from ./tool/rbinstall.rb:947:in `<main>'
make: *** [do-install-nodoc] Error 1
```
Not sure why it fails, I guess I'll try to print that log as well.
I wonder if openssl 1.1 is somehow the issue.

**Comment by eregon** [comment]
https://github.com/rvm/rvm/actions/runs/8348657537/job/22851088275?pr=5387#step:4:152
It's the typical mixup of openssl 1.1 and 3, due to pkg-config: https://bugs.ruby-lang.org/issues/18763
Which seems to have been reported on rvm too e.g. #5285 but looks like rvm doesn't set PKG_CONFIG_PATH itself.

**Comment by eregon** [comment]
https://github.com/rvm/rvm/pull/5387 fixes it and has more notes, most notably:
https://github.com/rvm/rvm/pull/5387#issuecomment-2008042189
https://github.com/rvm/rvm/pull/5387#issuecomment-2009391015
