### ISSUE TITLE
FIi issue

### ISSUE THREAD

**Issue by sureshvignesh** [rvm/rvm#4594]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by sureshvignesh** [comment]
Fetching ffi 1.9.14
Installing ffi 1.9.14 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/deploy/.rvm/gems/ruby-2.1.5@vakilsearch/gems/ffi-1.9.14/ext/ffi_c
/home/deploy/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20190128-19254-xl5r3a.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/deploy/.rvm/rubies/ruby-2.1.5/bin/ruby
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/home/deploy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /home/deploy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
        from /home/deploy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
        from /home/deploy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:642:in `block in try_ldflags'
        from /home/deploy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:635:in `with_ldflags'
        from /home/deploy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:641:in `try_ldflags'
        from /home/deploy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:1762:in `pkg_config'
        from extconf.rb:15:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/deploy/.rvm/gems/ruby-2.1.5@vakilsearch/extensions/x86_64-linux/2.1.0/ffi-1.9.14/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/deploy/.rvm/gems/ruby-2.1.5@vakilsearch/gems/ffi-1.9.14 for inspection.
Results logged to /home/deploy/.rvm/gems/ruby-2.1.5@vakilsearch/extensions/x86_64-linux/2.1.0/ffi-1.9.14/gem_make.out

An error occurred while installing ffi (1.9.14), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.14' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mailman was resolved to 0.7.3, which depends on
    listen was resolved to 2.10.1, which depends on
      rb-inotify was resolved to 0.9.7, which depends on
        ffi
