### ISSUE TITLE
Error running rubygems setup.rb

### ISSUE THREAD

**Issue by jdashton** [rvm/rvm#4607]
## Description

When installing MRI 2.6.1 on macOS 10.14.4 Beta, all goes well until #installing rubygems-3.0.2. At that point I see this:
```
Error running 'env GEM_HOME=/ruby-2.6.1@global GEM_PATH= /Users/jdashton/.rvm/rubies/ruby-2.6.1/bin/ruby -d /Users/jdashton/.rvm/src/rubygems-3.0.2/setup.rb --no-document',
please read /Users/jdashton/.rvm/log/1549554328_ruby-2.6.1/rubygems.install.log
```

## Steps to reproduce

 1. Install rvm master with [rvm get master](https://gist.github.com/jdashton/b8e79491b0cb27ae2b41f902dd9d2a9a).

 2. Install Ruby 2.6.1 with [rvm install 2.6](https://gist.github.com/jdashton/e96525615566700f86fa1b550eed84e4).

## Expected behavior

Ruby 2.6.1 should be cleanly installed.

## Actual behavior

Installation fails with an error about running setup.rb for rubygems-3.0.2.

* [rubygems.install.log](https://gist.github.com/jdashton/1045a4066ecbf59c32ef37a4e6607a7d)
* [config.log](https://gist.github.com/jdashton/49a73994c471eff2903ddfdaf2a87fc8)
* [make.log](https://gist.github.com/jdashton/8b7b2cf0fb7125e809b815ba607236d3)

## Environment info

ruby-2.5.3:

  system:
    uname:        "Darwin d11442.nadadventist.org 18.5.0 Darwin Kernel Version 18.5.0: Thu Jan 31 01:17:54 PST 2019; root:xnu-4903.250.319~62/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.14"
    architecture: "x86_64"
    bash:         "/usr/local/bin/bash => GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin18.2.0)"
    zsh:          "/usr/local/bin/zsh => zsh 5.7.1 (x86_64-apple-darwin18.2.0)"
    remote_path:  "osx/10.14/x86_64"
    xcode:        "10.1"

  rvm:
    version:      "1.29.7-next (master)"
    updated:      "58 minutes 18 seconds ago"
    path:         "/Users/jdashton/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.5.3p105"
    date:         "2018-10-18"
    platform:     "x86_64-darwin18"
    patchlevel:   "2018-10-18 revision 65156"
    full_version: "ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]"

  homes:
    gem:          "/Users/jdashton/.rvm/gems/ruby-2.5.3"
    ruby:         "/Users/jdashton/.rvm/rubies/ruby-2.5.3"

  binaries:
    ruby:         "/Users/jdashton/.rvm/rubies/ruby-2.5.3/bin/ruby"
    irb:          "/Users/jdashton/.rvm/rubies/ruby-2.5.3/bin/irb"
    gem:          "/Users/jdashton/.rvm/rubies/ruby-2.5.3/bin/gem"
    rake:         "/Users/jdashton/.rvm/gems/ruby-2.5.3@global/bin/rake"

  environment:
    PATH:         "/Users/jdashton/.rvm/gems/ruby-2.5.3/bin:/Users/jdashton/.rvm/gems/ruby-2.5.3@global/bin:/Users/jdashton/.rvm/rubies/ruby-2.5.3/bin:/Users/jdashton/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/Users/jdashton/.rvm/bin:/Users/jdashton/bin"
    GEM_HOME:     "/Users/jdashton/.rvm/gems/ruby-2.5.3"
    GEM_PATH:     "/Users/jdashton/.rvm/gems/ruby-2.5.3:/Users/jdashton/.rvm/gems/ruby-2.5.3@global"
    MY_RUBY_HOME: "/Users/jdashton/.rvm/rubies/ruby-2.5.3"
    IRBRC:        "/Users/jdashton/.rvm/rubies/ruby-2.5.3/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by Voxoff** [comment]
yup I have this on 10.14.1

**Comment by mshea24** [comment]
10.14.12 as well

**Comment by galtzo** [comment]
This is still an issue on 10.14.5 installing ruby-2.5.3.

@mshea24 10.14.12 doesn't exist.

Here is my install log:
```
∴ cat /Users/pboling/.rvm/log/1562796278_ruby-2.5.3/rubygems.install.log
[2019-07-10 15:06:26] /Users/pboling/.rvm/rubies/ruby-2.5.3/bin/ruby
current path: /Users/pboling/.rvm/src/rubygems-3.0.4
GEM_HOME=/Users/pboling/.rvm/gems/ruby-2.6.3
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/pboling/.rvm/gems/ruby-2.6.3/bin:/Users/pboling/.rvm/gems/ruby-2.6.3@global/bin:/Users/pboling/.rvm/rubies/ruby-2.6.3/bin:/Users/pboling/.rvm/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:~/bin:~/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/git/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Users/pboling/.ec2/tools/bin:/usr/local/share/npm/bin:/Users/pboling/Library/Python/3.7/bin:/Users/pboling/n/bin
GEM_PATH=/Users/pboling/.rvm/gems/ruby-2.6.3:/Users/pboling/.rvm/gems/ruby-2.6.3@global
command(7): env GEM_HOME=/ruby-2.5.3@global GEM_PATH= /Users/pboling/.rvm/rubies/ruby-2.5.3/bin/ruby -d /Users/pboling/.rvm/src/rubygems-3.0.4/setup.rb --no-document
Exception `LoadError' at /Users/pboling/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems.rb:1388 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/pboling/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems.rb:1397 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /Users/pboling/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/dependency.rb:310 - Gem::MissingSpecError
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /ruby-2.5.3@global directory.
Bundler 1.17.3 installed
RubyGems 3.0.4 installed
Regenerating binstubs
```

Pulling the important bits out of the log, we can see `GEM_HOME` and `GEM_PATH` are set:
```
GEM_HOME=/Users/pboling/.rvm/gems/ruby-2.6.3
GEM_PATH=/Users/pboling/.rvm/gems/ruby-2.6.3:/Users/pboling/.rvm/gems/ruby-2.6.3@global
```

But the command seems to override them to very bad values:
command(7): env GEM_HOME=/ruby-2.5.3@global GEM_PATH= /Users/pboling/.rvm/rubies/ruby-2.5.3/bin/ruby -d /Users/pboling/.rvm/src/rubygems-3.0.4/setup.rb --no-document
```
and for that reason fails.

**Comment by renatolond** [comment]
Hi! I'm also having the issue and I'm on Arch Linux.

From what I can gather, seems like a similar issue to #4287 / https://github.com/rubygems/rubygems/issues/2082

```
Exception `LoadError' at /home/renatolond/.rvm/rubies/ruby-2.6.5-jemalloc/lib/ruby/2.6.0/rubygems.rb:1375 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /home/renatolond/.rvm/rubies/ruby-2.6.5-jemalloc/lib/ruby/2.6.0/rubygems.rb:1384 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /home/renatolond/.rvm/rubies/ruby-2.6.5-jemalloc/lib/ruby/2.6.0/rubygems/dependency.rb:311 - Gem::MissingSpecError
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /home/renatolond/.rvm/gems/ruby-2.6.5-jemalloc@global directory.
Bundler 1.17.3 installed
RubyGems 3.0.6 installed
Regenerating binstubs
```
My `GEM_PATH` also seems empty:

```
Error running 'env GEM_HOME=/home/renatolond/.rvm/gems/ruby-2.6.5-jemalloc@global GEM_PATH= /home/renatolond/.rvm/rubies/ruby-2.6.5-jemalloc/bin/ruby -d /home/renatolond/.rvm/src/rubygems-3.0.6/setup.rb --no-document',
please read /home/renatolond/.rvm/log/1575457181_ruby-2.6.5-jemalloc/rubygems.install.log
```

**Comment by Lukom** [comment]
It doesn't fix the error, but after running
```
rvm gemset create global --default
```
command ruby works as expected

**Comment by dorianmariefr** [comment]
happened to me while installing ruby 2.3.1 on macos 10.15.3

**Comment by mehrad-meraji** [comment]
happened here as well ruby 2.3.0 on macos 10.15.3

**Comment by 1990prashant** [comment]
Happened here as well ruby 2.3.1 on macos 10.15.1

**Comment by DanielRuf** [comment]
Any solutions? Otherwise we have to switch to a different language and framework.

**Comment by deivid-rodriguez** [comment]
If someone can provide a docker repro on a ruby that has not yet reached its end of life (ruby 2.4 or higher), I'm happy to at least have a look.

**Comment by DanielRuf** [comment]
Switching to rbenv and testing if this works better.

**Comment by DanielRuf** [comment]
Hm, rbenv has the same issue. Seems macOS is too prblematic.

https://github.com/rbenv/ruby-build/issues/1169#issuecomment-367137554

**Comment by DanielRuf** [comment]
Hm, rbenv has the same issue. Seems macOS is not great for this anymore.

https://github.com/rbenv/ruby-build/issues/1169#issuecomment-367137554

**Comment by rotem-wald** [comment]
@DanielRuf Is there any new?
I did install RVM with the following guide: https://gist.github.com/denji/8706676 on macOS 10.15.4 and then installed Ruby 2.3.1. Got the same issue.

**Comment by DanielRuf** [comment]
@rotem-wald I linked a workaround. I also switched to rbenv and still use nacOS 10.14.

**Comment by DanielRuf** [comment]
@rotem-wald I linked a workaround. I also switched to rbenv and still use macOS 10.14.

**Comment by rotem-wald** [comment]
Thank you @DanielRuf, I can approve it was working.
I suggest you to use the following manual to install rbenv under macOS: https://gist.github.com/stonehippo/cc0f3098516fb52390f1
Then, if you encounter the above issues, solve it via the following workaround: https://github.com/rbenv/ruby-build/issues/1169#issuecomment-367137554

**Comment by CamJN** [comment]
I'm getting the same on CentOS 6.10 when installing ruby 2.1.10 and rubygems 3.1.2.
```
command(7): env GEM_HOME=/usr/local/rvm/gems/ruby-2.1.10@global GEM_PATH= /usr/local/rvm/rubies/ruby-2.1.10/bin/ruby -d /usr/local/rvm/src/rubygems-3.1.2/setup.rb --no-document
Exception `LoadError' at /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rubygems.rb:1194 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/rubygems.rb:1203 - cannot load such file -- rubygems/defaults/ruby
/usr/local/rvm/src/rubygems-3.1.2/lib/rubygems/compatibility.rb:16:in `<module:Gem>': undefined method `deprecate_constant' for Gem:Module (NoMethodError)
        from /usr/local/rvm/src/rubygems-3.1.2/lib/rubygems/compatibility.rb:14:in `<top (required)>'
        from /usr/local/rvm/src/rubygems-3.1.2/lib/rubygems.rb:16:in `require'
        from /usr/local/rvm/src/rubygems-3.1.2/lib/rubygems.rb:16:in `<top (required)>'
        from setup.rb:28:in `require'
        from setup.rb:28:in `<main>'
```

**Comment by CamJN** [comment]
The same is true of rubygems `3.1.1` and `3.1.0`

**Comment by deivid-rodriguez** [comment]
@CamJN In the error you post, the command `env GEM_HOME=/usr/local/rvm/gems/ruby-2.1.10@global GEM_PATH= /usr/local/rvm/rubies/ruby-2.1.10/bin/ruby -d /usr/local/rvm/src/rubygems-3.1.2/setup.rb --no-document` is trying to install rubygems 3.1.2 on ruby 2.1. rubygems 3.1.2 does not support ruby 2.1, so I believe the `rvm` installer should never run such a command. Is `rvm` running this command?

Again, if anybody is really interested in getting this fixed, please work on providing repro steps.

Thanks!

**Comment by CamJN** [comment]
@deivid-rodriguez ah, well that explains my problem. I was running `/usr/local/rvm/bin/rvm install ruby-$RUBY_VERSION --rubygems $RUBYGEMS_VSERSION` in my CI to install a bunch of rubies and the script sets the rubygems to the latest version. Had to lock it to `3.0.8` for now. A message about known incompatible versions and then not trying to continue would have been much clearer to me FWIW.

**Comment by flexid** [comment]
Try another rubygems after reinstalling openssl with brew: `rvm reinstall 2.3.1 --with-openssl-lib=/usr/local/opt/openssl@1.1/lib --with-openssl-include=/usr/local/opt/openssl@1.1/include --rubygems 2.6.6` did the trick here.

**Comment by elfotografo007** [comment]
I had the same issue while trying to install ruby 2.2.2. RVM tries to install 3.0.8, but RubyGems 3.0.0+ requires Ruby 2.3.  I found that the latest pre 3 Rubygems is 2.7.10:

`rvm install 2.2.2 --rubygems 2.7.10`

This was on macOS Catalina 10.15.4.

**Comment by harish-aka-shivi** [comment]
Thanks, @elfotografo007, It worked for me. 👍

**Comment by andreibondarev** [comment]
@elfotografo007 Didn't work for me trying to install `2.1.10` :(

**Comment by mcheck** [comment]
Thanks @flexid, 
This worked great for Ruby 2.3.7 and RubyGems 3.0.8 on osx catalina 10.15.5

**Comment by arunsnt** [comment]
Thanks @flexid 

I had the same issue with ruby 2.1.7 and RubyGems 3.0.8 on Mac 10.15.5

Fixed it with below steps

Restart the laptop
rvm implode
\curl -sSL https://get.rvm.io | bash
rvm pkg install openssl
rvm install 2.3.1 --with-openssl-dir=$HOME/.rvm/usr

**Comment by Nikhil-Wagh** [comment]
@arunsnt worked. Although no need to implode. Just 
```
rvm pkg install openssl
rvm reinstall 2.3.1 --with-openssl-dir=$HOME/.rvm/usr --force
```

**Comment by maddieholtzer** [comment]
@flexid thank you so much I had been stuck on this for hours and your solution just fixed it.

**Comment by anoobbava** [comment]
@flexid Worked your solution on high Sierra

**Comment by lukaszmarcinkowski** [comment]
@flexid  Thank You too, it also worked for me with Catalina 10.15.5

**Comment by prashant-anchanto** [comment]
Thanks, @elfotografo007, it worked.

**Comment by fifiteen82726** [comment]
This works for me, not sure why my Openssl directory is different from everyone else.
```
rvm pkg install openssl
rvm reinstall 2.6.6 --rubygems 3.0.8 --with-openssl-dir=/Users/coda/.rvm/usr/ssl
``

**Comment by Arunscape224** [comment]
> pkg

This worked for me!

**Comment by rafaelcamargo** [comment]
Thanks @flexid! Worked perfectly here (macOS Catalina 10.15.7).

**Comment by anle1337** [comment]
For some odd reason, in my case i had to do:

`rvm remove 2.3.6`
`rvm install 2.3.6 --with-openssl-dir=$HOME/.rvm/usr`

`rvm reinstall 2.3.6 --with-openssl-dir=$HOME/.rvm/usr` didn't work

**Comment by alistair-dejonge** [comment]
same as @akshatagg06, with Monterey 12.1... same ruby and gems versions

`rvm reinstall 2.2.3 --rubygems 2.7.10 --with-openssl-dir=$HOME/.rvm/usr/ssl --force`

still get error:

`Error running 'env GEM_HOME=/Users/alistairdejonge/.rvm/gems/ruby-2.2.3@global GEM_PATH= /Users/alistairdejonge/.rvm/rubies/ruby-2.2.3/bin/ruby -d /Users/alistairdejonge/.rvm/src/rubygems-2.7.10/setup.rb --no-document'`

**Comment by Jahmal23** [comment]
Had the same issue as @akshatagg06 and @akshatagg06 on Monterey 12.1.

Once I encountered - 

`Error running 'env GEM_HOME=/Users/jahmal.lewis/.rvm/gems/ruby-2.3.7@global GEM_PATH= /Users/jahmal.lewis/.rvm/rubies/ruby-2.3.7/bin/ruby -d /Users/jahmal.lewis/.rvm/src/rubygems-3.0.9/setup.rb --no-document',
please read /Users/jahmal.lewis/.rvm/log/1652104448_ruby-2.3.7/rubygems.install.log`

I saw from the log it was an issue with openssl, so I ran - 

`rvm pkg install openssl`
`rvm remove 2.3.7`
`rvm install 2.3.7  --rubygems 2.7.10 --with-openssl-dir=$HOME/.rvm/usr`

Seems to have worked.

**Comment by mansi-sheth** [comment]
> same as @akshatagg06, with Monterey 12.1... same ruby and gems versions
> 
> `rvm reinstall 2.2.3 --rubygems 2.7.10 --with-openssl-dir=$HOME/.rvm/usr/ssl --force`
> 
> still get error:
> 
> `Error running 'env GEM_HOME=/Users/alistairdejonge/.rvm/gems/ruby-2.2.3@global GEM_PATH= /Users/alistairdejonge/.rvm/rubies/ruby-2.2.3/bin/ruby -d /Users/alistairdejonge/.rvm/src/rubygems-2.7.10/setup.rb --no-document'`

@alistair-dejonge  @akshatagg06 Were you able to resolve this? I am facing same problem in Monterey 12.3.1
