### ISSUE TITLE
RVM 1.29.8 breaks older (pre 2.0) ruby installations due to using Rubygems 3.0.3

### ISSUE THREAD

**Issue by mattherrmann** [rvm/rvm#4690]
## Description

Attempting to install pre 2.0 rubies with the latest RVM (1.29.8) fails, as RVM attempts to install Rubygems 3.0.3, which doesn't support Ruby < 2.0. The previous version of RVM (1.29.7) works fine as it installs Rubygems 2.7.9.

## Steps to reproduce

 1. Install or update rvm as per the documentation
 2. `rvm install 1.9.3` (or anything < 2.0)
 3. The following error occurs:
```
Error running 'env GEM_HOME=/usr/local/rvm/gems/ruby-1.9.3-p551@global GEM_PATH= /usr/local/rvm/rubies/ruby-1.9.3-p551/bin/ruby -d /usr/local/rvm/src/rubygems-3.0.3/setup.rb --no-document',
please read /usr/local/rvm/log/1557454044_ruby-1.9.3-p551/rubygems.install.log
```
The log file contains the following:
```
[2019-05-10 02:09:27] /usr/local/rvm/rubies/ruby-1.9.3-p551/bin/ruby
current path: /usr/local/rvm/src/rubygems-3.0.3
GEM_HOME=/usr/local/rvm/gems/ruby-2.0.0-p648
GEM_PATH=/usr/local/rvm/gems/ruby-2.0.0-p648:/usr/local/rvm/gems/ruby-2.0.0-p648@global
PATH=/usr/local/rvm/gems/ruby-2.0.0-p648/bin:/usr/local/rvm/gems/ruby-2.0.0-p648@global/bin:/usr/local/rvm/rubies/ruby-2.0.0-p648/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
command(7): env GEM_HOME=/usr/local/rvm/gems/ruby-1.9.3-p551@global GEM_PATH= /usr/local/rvm/rubies/ruby-1.9.3-p551/bin/ruby -d /usr/local/rvm/src/rubygems-3.0.3/setup.rb --no-document
Exception `LoadError' at /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rubygems.rb:1264 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rubygems.rb:1273 - cannot load such file -- rubygems/defaults/ruby
/usr/local/rvm/src/rubygems-3.0.3/lib/rubygems/core_ext/kernel_require.rb:54:in `require': /usr/local/rvm/src/rubygems-3.0.3/lib/rubygems/core_ext/kernel_warn.rb:15: syntax error, unexpected tLABEL (SyntaxError)
    module_function define_method(:warn) {|*messages, uplevel: nil|
                                                              ^
/usr/local/rvm/src/rubygems-3.0.3/lib/rubygems/core_ext/kernel_warn.rb:18: void value expression
/usr/local/rvm/src/rubygems-3.0.3/lib/rubygems/core_ext/kernel_warn.rb:43: syntax error, unexpected '}', expecting keyword_end
        from /usr/local/rvm/src/rubygems-3.0.3/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/src/rubygems-3.0.3/lib/rubygems.rb:1395:in `<top (required)>'
        from setup.rb:28:in `require'
        from setup.rb:28:in `<main>'
```
## Expected behavior

Using rvm 1.29.7, the following occurs:
```
ruby-1.9.3-p551 - #installing rubygems-2.7.9....................................
```
The install then completes successfully.

**Comment by MatthiasHertel** [comment]
i have exactly the same issue ...

**Comment by SamarthUpadhya** [comment]
I ran into the same issue today. Any idea how can i solve this issue ?

**Comment by mattherrmann** [comment]
For those experiencing this issue, there are a couple of workarounds..

You can run: `rvm get 1.29.7` to downgrade rvm to 1.29.7, which will allow you to successfully install pre 2.0 rubies.

Alternatively (and this is something I had to do as my current automation doesn't seem to allow me to downgrade rvm easily..) you install the ruby version (which will "fail" but the ruby binaries etc will still be there), tell rvm to install an older version of rubygems and then run a repair.. There seems may be unexpected side-effects to this though.
E.g.
```
rvm install 1.9.3
rvm use 1.9.3
rvm rubygems 2.7.9
rvm repair all
```
Hope this helps!

**Comment by SamarthUpadhya** [comment]
@mattherrmann : Thank you. It worked. This is what i i did
rvm implode
curl -sSL https://get.rvm.io | bash -s -- --version 1.29.7
source .bashrc
rvm reload
rvm install ruby-1.9.9

**Comment by MatrixManAtYrService** [comment]
In my case, explicitly specifying the gems version at the same time as the ruby version did the trick:

    rvm install 1.9.3 --rubygems 2.7.9
