### ISSUE TITLE
installing jruby fails 

### ISSUE THREAD

**Issue by ruudgrosmann** [rvm/rvm#4720]
I hope you can guide me on this problem. I am nearly always able to work around the problems that arise during using rvm, but this time I am stuck.
Thanks in advance, Ruud

## Description

installation of jruby 9.1 fails with a

> java.net.ConnectException: Connection timed out

## Steps to reproduce

- rvm get master 
- rvm install "jruby-9.1" --proxy  MYPROXY

## Expected behavior
jruby gets installed
## Actual behavior
The installation of jruby starts very promising, but it always fails after 
jruby-9.1.17.0 - #mvnw - please wait

````
Downloading https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/12.04/x86_64/9.1.17.0/jruby-dist-9.1.17.0-bin.tar.gz failed.
Mounting remote ruby failed with status 2, trying to compile.
Checking requirements for ubuntu.
Requirements installation successful.
HEAD is now at d8b1ff9 Somehow we lost jruby version for another sys variable
Previous HEAD position was d8b1ff9... Somehow we lost jruby version for another sys variable
Switched to branch 'master'
From https://github.com/jruby/jruby
 * branch            master     -> FETCH_HEAD
Already up-to-date.
git checkout 9.1.17.0
Copying from repo to src path...
jruby-9.1.17.0 - #mvnw - please wait
Error running '/home/tp00/.rvm/src/jruby-9.1.17.0/mvnw',
please read /home/tp00/.rvm/log/1561628666_jruby-9.1.17.0/mvnw.log`

Which says:
```
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.zip

Exception in thread "main" java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
```



## Environment info

<!-- Paste below the output of the `rvm info` command. -->

``ruby-2.6.3:

  system:
    uname:        "Linux srv160bh 3.2.0-29-generic #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "12.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.2.25(1)-release (x86_64-pc-linux-gnu)"
    zsh:          "/usr/bin/zsh => zsh 4.3.17 (x86_64-unknown-linux-gnu)"
    remote_path:  "ubuntu/12.04/x86_64"

  rvm:
    version:      "1.29.8-next (master)"
    updated:      "7 minutes 57 seconds ago"
    path:         "/home/tp00/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.6.3p62"
    date:         "2019-04-16"
    platform:     "x86_64-linux"
    patchlevel:   "2019-04-16 revision 67580"
    full_version: "ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]"

  homes:
    gem:          "/home/tp00/.rvm/gems/ruby-2.6.3"
    ruby:         "/home/tp00/.rvm/rubies/ruby-2.6.3"

  binaries:
    ruby:         "/home/tp00/.rvm/rubies/ruby-2.6.3/bin/ruby"
    irb:          "/home/tp00/.rvm/rubies/ruby-2.6.3/bin/irb"
    gem:          "/home/tp00/.rvm/rubies/ruby-2.6.3/bin/gem"
    rake:         "/home/tp00/.rvm/rubies/ruby-2.6.3/bin/rake"

  environment:
    PATH:         "/home/tp00/.rvm/gems/ruby-2.6.3/bin:/home/tp00/.rvm/gems/ruby-2.6.3@global/bin:/home/tp00/.rvm/rubies/ruby-2.6.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/tp00/.rvm/bin:/home/tp00/.rvm/bin"
    GEM_HOME:     "/home/tp00/.rvm/gems/ruby-2.6.3"
    GEM_PATH:     "/home/tp00/.rvm/gems/ruby-2.6.3:/home/tp00/.rvm/gems/ruby-2.6.3@global"
    MY_RUBY_HOME: "/home/tp00/.rvm/rubies/ruby-2.6.3"
    IRBRC:        "/home/tp00/.rvm/rubies/ruby-2.6.3/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
`

**Comment by ruudgrosmann** [comment]
Just before the timeout message the logging contains

`Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.zip`
Manually downloading this file using curl gives no problems. I do not know if the timeout is about this particular download or not.

**Comment by aaron-suarez** [comment]
Possibly related, a gem I maintain that has Travis CI fails checks on jruby-9000 with the following stack trace:
```
$ rvm get stable
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /home/travis/.rvm/archives/rvm-installer.asc
gpg: Signature made Tue 23 Apr 2019 04:50:26 PM UTC using RSA key ID 39499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D2B AF1C F37B 13E2 069D  6956 105B D0E7 3949 9BDB
GPG verified '/home/travis/.rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Could not download 'https://github.com/rvm/rvm/archive/.tar.gz'.
  curl returned status '22'.
Downloading https://bitbucket.org/mpapis/rvm/get/.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Could not download 'https://bitbucket.org/mpapis/rvm/get/.tar.gz'.
  curl returned status '22'.
Could not update RVM, please report to https://github.com/rvm/rvm/issues
The command "rvm get stable" failed and exited with 22 during .
```

The rest of my Travis checks pass. Seems like it should be trying to curl from `https://github.com/rvm/rvm/archive/master.tar.gz` rather than `https://github.com/rvm/rvm/archive/.tar.gz`

If this is an unrelated issue, please let me know and I can open a new issue for this specifically.

**Comment by ruudgrosmann** [comment]
hi aaron, I don't think this is relateed. In the logging, the name of the last mentioned file download before the exception seems OK and moreover, I can download it by hand with curl. I have no idea why the connection times out, for the downloading of lots of files before the exception went smoothly....

Isn't there a way to get more (debug) output from the installation process in order to track the real problem down more easily?

Ruud

**Comment by aaron-suarez** [comment]
@ruudgrosmann I don't know how to get any more information because I can't ssh into the Travis server or anything like that. I restarted the job a few minutes ago and it still failed. It's open source, feel free to view the logs here https://travis-ci.org/recurly/recurly-client-ruby/jobs/551517709

**Comment by H21lab** [comment]
Behind proxy you can use something like: 
export MAVEN_OPTS="-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3128"

However after this I run into other problem (on Debian 10):
org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (anno) on project jruby-core: Compilation failure
