### ISSUE TITLE
Bundler installs gems to incorrect path on MacOS Mojave

### ISSUE THREAD

**Issue by CodingAnarchy** [rvm/rvm#4787]
## Description

We recently updated to Ruby 2.6.4 via RVM, which produced a conflict where 2.6.3 and 2.6.4 were both installing gems in `~/.rvm/gems/ruby-2.6.3`. Bundler produced an error upon trying to run Rails after the upgrade:

```
~/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require': incompatible library version - ~/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi_c.bundle (LoadError)
```
We had to remove `~/.rvm/gems/ruby-2.6.3` and run `bundle install` again on 2.6.4 in order for Rails to run.  Bundler still installed to `~/.rvm/gems/ruby-2.6.3`, which is the wrong path.

## Steps to reproduce

1. `rvm install 2.6.3`
1. `gem install bundler`
1. `bundle install` a Rails application
1. `rvm install 2.6.4`
1. `gem install bundler`
1. `bundle install`
1. `bundle exec rails s`

## Expected behavior

Rails server loads as with the prior ruby version.

## Actual behavior

```
Traceback (most recent call last):
    34: from bin/rails:9:in `<main>'
    33: from bin/rails:9:in `require'
    32: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
    31: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    30: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:85:in `server'
    29: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:85:in `tap'
    28: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:88:in `block in server'
    27: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:88:in `require'
    26: from /Users/nick.riemondi/Source/portal/config/application.rb:6:in `<top (required)>'
    25: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
    24: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
    23: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
    22: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
    21: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
    20: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
    19: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `require'
    18: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `<top (required)>'
    17: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `require_relative'
    16: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<top (required)>'
    15: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
    14: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
    13: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
    12: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
    11: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-2.1.0/lib/sassc.rb:31:in `<top (required)>'
    10: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-2.1.0/lib/sassc.rb:31:in `require_relative'
     9: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-2.1.0/lib/sassc/native.rb:3:in `<top (required)>'
     8: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
     7: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
     6: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
     5: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
     4: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi.rb:4:in `<top (required)>'
     3: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
     2: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
     1: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
/Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- 2.6/ffi_c (LoadError)
    35: from bin/rails:9:in `<main>'
    34: from bin/rails:9:in `require'
    33: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
    32: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    31: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:85:in `server'
    30: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:85:in `tap'
    29: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:88:in `block in server'
    28: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:88:in `require'
    27: from /Users/nick.riemondi/Source/portal/config/application.rb:6:in `<top (required)>'
    26: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
    25: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
    24: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
    23: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
    22: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
    21: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
    20: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.4/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `require'
    19: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `<top (required)>'
    18: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `require_relative'
    17: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<top (required)>'
    16: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
    15: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
    14: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
    13: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
    12: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-2.1.0/lib/sassc.rb:31:in `<top (required)>'
    11: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-2.1.0/lib/sassc.rb:31:in `require_relative'
    10: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/sassc-2.1.0/lib/sassc/native.rb:3:in `<top (required)>'
     9: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
     8: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
     7: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
     6: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
     5: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi.rb:3:in `<top (required)>'
     4: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi.rb:6:in `rescue in <top (required)>'
     3: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
     2: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
     1: from /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
/Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require': incompatible library version - /Users/nick.riemondi/.rvm/gems/ruby-2.6.3/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi_c.bundle (LoadError)
```

## Environment info

```
ruby-2.6.4:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  system:
    uname:        "Darwin Matthews-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin"
    name:         "OSX"
    version:      "10.14"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin18.0)"
    remote_path:  "osx/10.14/x86_64"
    xcode:        ""

  rvm:
    version:      "1.29.9-next (master)"
    updated:      "10 minutes 3 seconds ago"
    path:         "/Users/mtanous/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.6.4p104"
    date:         "2019-08-28"
    platform:     "x86_64-darwin18"
    patchlevel:   "2019-08-28 revision 67798"
    full_version: "ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]"

  homes:
    gem:          "/Users/mtanous/.rvm/gems/ruby-2.6.4"
    ruby:         "not set"

  binaries:
    ruby:         "/Users/mtanous/.rvm/rubies/ruby-2.6.4/bin/ruby"
    irb:          "/Users/mtanous/.rvm/rubies/ruby-2.6.4/bin/irb"
    gem:          "/Users/mtanous/.rvm/rubies/ruby-2.6.4/bin/gem"
    rake:         "/Users/mtanous/.rvm/gems/ruby-2.6.4/bin/rake"

  environment:
    PATH:         "/Users/mtanous/.rvm/gems/ruby-2.6.4/bin:/Users/mtanous/.rvm/gems/ruby-2.6.4/bin:/Users/mtanous/.rvm/gems/ruby-2.6.4@global/bin:/Users/mtanous/.rvm/rubies/ruby-2.6.4/bin:/Users/mtanous/.rvm/bin:/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/sbin:/Users/mtanous/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Users/mtanous/.go/bin:/Users/mtanous/bin"
    GEM_HOME:     "/Users/mtanous/.rvm/gems/ruby-2.6.4"
    GEM_PATH:     "/Users/mtanous/.rvm/gems/ruby-2.6.4:/Users/mtanous/.rvm/gems/ruby-2.6.4@global"
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by CodingAnarchy** [comment]
Looks like `bundle config` was remembering the old path due to some code in our setup scripts.  Apologies for the false alarm.

**Comment by MaheshKariappa** [comment]
@CodingAnarchy Could you please let me know how did you resolve this , Iam also getting similar error
