### ISSUE TITLE
Error in ruby-2.7.0-preview2 file name, Linux

### ISSUE THREAD

**Issue by jzakiya** [rvm/rvm#4806]
Upgraded ruby-2.7.0-preview1 to ruby-2.7.0-preview2 on Linux.

There is a filename spelling error that is preventing it to run, no space between ``--2.7.0preview2``

```
➜  ~ rvm list
   jruby-9.2.8.0 [ x86_64 ]
   ruby-2.6.5 [ x86_64 ]
=* ruby-2.7.0-preview2 [ x86_64 ]
   truffleruby-19.2.0.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

➜  ~ ruby -v
ruby 2.7.0preview2 (2019-10-22 master 02aadf1032) [x86_64-linux]
➜  ~ irb
Traceback (most recent call last):
        6: from /home/jzakiya/.rvm/gems/ruby-2.7.0-preview2/bin/ruby_executable_hooks:10:in `<main>'
        5: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
        4: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
        3: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
        2: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
        1: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
/home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require': cannot load such file -- rubygems-bundler/noexec (LoadError)
        10: from /home/jzakiya/.rvm/gems/ruby-2.7.0-preview2/bin/ruby_executable_hooks:10:in `<main>'
         9: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `run'
         8: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:49:in `each'
         7: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/executable-hooks-1.6.0/lib/executable-hooks/hooks.rb:50:in `block in run'
         6: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
         5: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:34:in `require'
         4: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:157:in `rescue in require'
         3: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:157:in `require'
         2: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
         1: from /home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:124:in `check'
/home/jzakiya/.rvm/rubies/ruby-2.7.0-preview2/lib/ruby/gems/2.7.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x0000000001e56018> (NoMethodError)
➜  ~ 

```

**Comment by jzakiya** [comment]
This issues occurred when is was upgrading ruby-2.7.0-preview1 to preview2

```rvm upgrade ruby-2.7.0-preview1 ruby-2.7.0-preview2```

However, when installed it directly it runs fine.

```rvm install ruby-2.7.0-preview2```

The only thing with this is I have to individually reinstall all the gems again.

One problem I've found (not an RVM problem) is ``pry`` doesn't work with ``preview1/2``.
