### ISSUE TITLE
failed install ruby 2.3.8

### ISSUE THREAD

**Issue by ibantoo** [rvm/rvm#4892]
all day today i install and reinstall rvm and remove all ruby version on my Mac
it got error to install `rvm install 2.3.8`
error i got is:
```
Error running 
'env GEM_HOME=/Users/myname/.rvm/gems/ruby-2.3.8@global GEM_PATH= /Users/myname/.rvm/rubies/ruby-2.3.8/bin/ruby 
-d /Users/myname/.rvm/src/rubygems-3.0.8/setup.rb --no-document',

please read /Users/myname/.rvm/log/1585228001_ruby-2.3.8/rubygems.install.log
```
log here : 
```
Exception `LoadError' at /Users/myname/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/rubygems.rb:1242 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/myname/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/rubygems.rb:1251 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /Users/myname/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- did_you_mean
/Users/myname/.rvm/src/rubygems-3.0.8/lib/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- openssl (LoadError)
        from /Users/myname/.rvm/src/rubygems-3.0.8/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/myname/.rvm/src/rubygems-3.0.8/lib/rubygems/specification.rb:2481:in `to_ruby'
        from /Users/myname/.rvm/src/rubygems-3.0.8/lib/rubygems/commands/setup_command.rb:405:in `install_default_bundler_gem'
        from /Users/myname/.rvm/src/rubygems-3.0.8/lib/rubygems/commands/setup_command.rb:167:in `execute'
        from /Users/myname/.rvm/src/rubygems-3.0.8/lib/rubygems/command.rb:321:in `invoke_with_build_args'
        from /Users/myname/.rvm/src/rubygems-3.0.8/lib/rubygems/command_manager.rb:184:in `process_args'
        from /Users/myname/.rvm/src/rubygems-3.0.8/lib/rubygems/command_manager.rb:148:in `run'
        from /Users/myname/.rvm/src/rubygems-3.0.8/lib/rubygems/gem_runner.rb:59:in `run'
```

i install rvm without rubygems-bundler and rvm gem first time,
any help? or same issue?

**Comment by ibantoo** [comment]
to all who breaks to intsall ruby 2.3.x with rvm, try using `openssl `1.0`,
