### ISSUE TITLE
Error installing ruby-2.4.8 on ubuntu 18.04

### ISSUE THREAD

**Issue by hurricup** [rvm/rvm#4916]
1. Update to rvm master
2. run `rvm install ruby-2.4.8`
3. Get 
```
hurricup@HIVE:~/.rvm/gems$ rvm install ruby-2.4.8
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/18.04/x86_64/ruby-2.4.8.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /usr/share/rvm/rubies/ruby-2.4.8, this may take a while depending on your cpu(s)...
ruby-2.4.8 - #downloading ruby-2.4.8, this may take a while depending on your connection...
ruby-2.4.8 - #extracting ruby-2.4.8 to /usr/share/rvm/src/ruby-2.4.8.....
ruby-2.4.8 - #configuring..................................................................
ruby-2.4.8 - #post-configuration..
ruby-2.4.8 - #compiling...................................................................................
ruby-2.4.8 - #installing..............
Error running '__rvm_make install',
please read /home/hurricup/.rvm/log/1587732391_ruby-2.4.8/install.log
There has been an error while running make install. Halting the installation.
```

Log ends with: 
```
installing default gems:      /usr/share/rvm/rubies/ruby-2.4.8/lib/ruby/gems/2.4.0 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.3.2
                              io-console 0.4.6
                              json 2.0.4
                              openssl 2.0.9
                              psych 2.2.2
                              rdoc 5.0.1
installing bundle gems:       /usr/share/rvm/rubies/ruby-2.4.8/lib/ruby/gems/2.4.0 (build_info, cache, doc, extensions, gems, specifications)
/usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:383:in `initialize': Permission denied @ rb_sysopen - /usr/share/rvm/rubies/ruby-2.4.8/lib/ruby/gems/2.4.0/gems/minitest-5.10.1/.autotest (Errno::EACCES)
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:383:in `open'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:383:in `block (2 levels) in extract_tar_gz'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package/tar_reader.rb:65:in `each'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:365:in `block in extract_tar_gz'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:492:in `block in open_tar_gz'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:489:in `wrap'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:489:in `open_tar_gz'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:364:in `extract_tar_gz'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:345:in `block (2 levels) in extract_files'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package/tar_reader.rb:65:in `each'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:342:in `block in extract_files'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package/file_source.rb:30:in `open'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package/file_source.rb:30:in `with_read_io'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/package.rb:339:in `extract_files'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/installer.rb:801:in `extract_files'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/installer.rb:302:in `install'
	from ./tool/rbinstall.rb:685:in `call'
	from ./tool/rbinstall.rb:685:in `block in <class:Installer>'
	from ./tool/rbinstall.rb:784:in `block (3 levels) in <main>'
	from /usr/share/rvm/src/ruby-2.4.8/lib/rubygems/user_interaction.rb:51:in `use_ui'
	from ./tool/rbinstall.rb:784:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:780:in `each'
	from ./tool/rbinstall.rb:780:in `block in <main>'
	from ./tool/rbinstall.rb:822:in `block in <main>'
	from ./tool/rbinstall.rb:819:in `each'
	from ./tool/rbinstall.rb:819:in `<main>'
uncommon.mk:284: recipe for target 'do-install-nodoc' failed
make: *** [do-install-nodoc] Error 1
++ return 2
```

Llisting `/usr/share/rvm/rubies/ruby-2.4.8/lib/ruby/gems/2.4.0/gems/`:
```
total 16
drwxr-xr-x 4 hurricup hurricup 4096 апр 24 15:48 ./
drwxr-xr-x 8 hurricup hurricup 4096 апр 24 15:48 ../
dr-xr-xr-x 2 hurricup hurricup 4096 апр 24 15:48 minitest-5.10.1/
drwxr-xr-x 3 hurricup hurricup 4096 апр 24 15:48 rdoc-5.0.1/
```

Here is `rvm info`
```
ruby-2.7.0:

  system:
    uname:        "Linux HIVE 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "18.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)"
    zsh:          "/usr/bin/zsh => zsh 5.4.2 (x86_64-ubuntu-linux-gnu)"
    remote_path:  "ubuntu/18.04/x86_64"

  rvm:
    version:      "1.29.10-next (master)"
    updated:      "25 minutes 16 seconds ago"
    path:         "/usr/share/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.7.0p0"
    date:         "2019-12-25"
    platform:     "x86_64-linux"
    patchlevel:   "2019-12-25 revision 647ee6f091"
    full_version: "ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]"

  homes:
    gem:          "/home/hurricup/.rvm/gems/ruby-2.7.0"
    ruby:         "/usr/share/rvm/rubies/ruby-2.7.0"

  binaries:
    ruby:         "/usr/share/rvm/rubies/ruby-2.7.0/bin/ruby"
    irb:          "/usr/share/rvm/rubies/ruby-2.7.0/bin/irb"
    gem:          "/usr/share/rvm/rubies/ruby-2.7.0/bin/gem"
    rake:         "/usr/share/rvm/rubies/ruby-2.7.0/bin/rake"

  environment:
    PATH:         "/home/hurricup/bin:/home/hurricup/perl5/perlbrew/bin:/home/hurricup/perl5/perlbrew/perls/perl-5.26.2/bin:/home/hurricup/.rvm/gems/ruby-2.7.0/bin:/home/hurricup/.rvm/gems/ruby-2.7.0@global/bin:/usr/share/rvm/rubies/ruby-2.7.0/bin:/home/hurricup/bin:/opt/jbrsdk11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/jbjdk/bin:/snap/bin:/usr/share/rvm/bin"
    GEM_HOME:     "/home/hurricup/.rvm/gems/ruby-2.7.0"
    GEM_PATH:     "/home/hurricup/.rvm/gems/ruby-2.7.0:/home/hurricup/.rvm/gems/ruby-2.7.0@global"
    MY_RUBY_HOME: "/usr/share/rvm/rubies/ruby-2.7.0"
    IRBRC:        "/usr/share/rvm/rubies/ruby-2.7.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by raelgc** [comment]
Hi @hurricup  and thanks for reporting this issue.

Is this a fresh install of rvm or you already had it using other rubies in the past?

In any case, can you try `rvm fix-permissions system` ? (Maybe it'll ask your password).

**Comment by hurricup** [comment]
@raelgc both cases behaves same way. I encountered this issue when tried to re-build my CI docker image (with fresh rvm installation and several rubies) and then, reproduced on my dev machine with existing rvm and rubies. 

Ok, tried `fix-permissions`:
1. removed failed installation of 2.4.8
2. ran  `rvm fix-permissions system`
3. Tried to install again - same result.

Btw. on my dev machine rvm was installed from apt irr. But in docker image it's just a single-user installation: `curl -sSL https://get.rvm.io | bash`

**Comment by hurricup** [comment]
Here is info from docker (this time I using `rvm head`, sorry, tried with master too):

1. console output: 
```
user@70556046c7f3:~$ rvm install 2.4.8
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/18.04/x86_64/ruby-2.4.8.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /home/user/.rvm/rubies/ruby-2.4.8, this may take a while depending on your cpu(s)...
ruby-2.4.8 - #downloading ruby-2.4.8, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.6M  100 11.6M    0     0  2561k      0  0:00:04  0:00:04 --:--:-- 2561k
ruby-2.4.8 - #extracting ruby-2.4.8 to /home/user/.rvm/src/ruby-2.4.8.....
ruby-2.4.8 - #configuring...................................................................
ruby-2.4.8 - #post-configuration..
ruby-2.4.8 - #compiling...................................................................................
ruby-2.4.8 - #installing..............
Error running '__rvm_make install',
please read /home/user/.rvm/log/1587749256_ruby-2.4.8/install.log
There has been an error while running make install. Halting the installation.
```

2. rvm info:
```
ruby-2.4.0:

  system:
    uname:        "Linux 70556046c7f3 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "18.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/18.04/x86_64"

  rvm:
    version:      "1.29.10-next (master)"
    updated:      "1 day 4 hours 52 minutes 31 seconds ago"
    path:         "/home/user/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.0p0"
    date:         "2016-12-24"
    platform:     "x86_64-linux"
    patchlevel:   "2016-12-24 revision 57164"
    full_version: "ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]"

  homes:
    gem:          "/home/user/.rvm/gems/ruby-2.4.0"
    ruby:         "/home/user/.rvm/rubies/ruby-2.4.0"

  binaries:
    ruby:         "/home/user/.rvm/rubies/ruby-2.4.0/bin/ruby"
    irb:          "/home/user/.rvm/rubies/ruby-2.4.0/bin/irb"
    gem:          "/home/user/.rvm/rubies/ruby-2.4.0/bin/gem"
    rake:         "/home/user/.rvm/rubies/ruby-2.4.0/bin/rake"

  environment:
    PATH:         "/home/user/.rvm/gems/ruby-2.4.0/bin:/home/user/.rvm/gems/ruby-2.4.0@global/bin:/home/user/.rvm/rubies/ruby-2.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/user/.rvm/bin"
    GEM_HOME:     "/home/user/.rvm/gems/ruby-2.4.0"
    GEM_PATH:     "/home/user/.rvm/gems/ruby-2.4.0:/home/user/.rvm/gems/ruby-2.4.0@global"
    MY_RUBY_HOME: "/home/user/.rvm/rubies/ruby-2.4.0"
    IRBRC:        "/home/user/.rvm/rubies/ruby-2.4.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```
3. Log tail:
```
installing default gems:      /home/user/.rvm/rubies/ruby-2.4.8/lib/ruby/gems/2.4.0 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.3.2
                              io-console 0.4.6
                              json 2.0.4
                              openssl 2.0.9
                              psych 2.2.2
                              rdoc 5.0.1
installing bundle gems:       /home/user/.rvm/rubies/ruby-2.4.8/lib/ruby/gems/2.4.0 (build_info, cache, doc, extensions, gems, specifications)
/home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:383:in `initialize': Permission denied @ rb_sysopen - /home/user/.rvm/rubies/ruby-2.4.8/lib/ruby/gems/2.4.0/gems/minitest-5.10.1/.autotest (Errno::EACCES)
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:383:in `open'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:383:in `block (2 levels) in extract_tar_gz'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package/tar_reader.rb:65:in `each'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:365:in `block in extract_tar_gz'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:492:in `block in open_tar_gz'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:489:in `wrap'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:489:in `open_tar_gz'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:364:in `extract_tar_gz'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:345:in `block (2 levels) in extract_files'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package/tar_reader.rb:65:in `each'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:342:in `block in extract_files'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package/file_source.rb:30:in `open'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package/file_source.rb:30:in `with_read_io'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/package.rb:339:in `extract_files'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/installer.rb:801:in `extract_files'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/installer.rb:302:in `install'
	from ./tool/rbinstall.rb:685:in `call'
	from ./tool/rbinstall.rb:685:in `block in <class:Installer>'
	from ./tool/rbinstall.rb:784:in `block (3 levels) in <main>'
	from /home/user/.rvm/src/ruby-2.4.8/lib/rubygems/user_interaction.rb:51:in `use_ui'
	from ./tool/rbinstall.rb:784:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:780:in `each'
	from ./tool/rbinstall.rb:780:in `block in <main>'
	from ./tool/rbinstall.rb:822:in `block in <main>'
	from ./tool/rbinstall.rb:819:in `each'
	from ./tool/rbinstall.rb:819:in `<main>'
uncommon.mk:284: recipe for target 'do-install-nodoc' failed
make: *** [do-install-nodoc] Error 1
++ return 2
```
4. Dir contents
```
user@70556046c7f3:~$ ll /home/user/.rvm/rubies/ruby-2.4.8/lib/ruby/gems/2.4.0/gems/
total 16
drwxr-xr-x 4 user user 4096 Apr 24 20:29 ./
drwxr-xr-x 8 user user 4096 Apr 24 20:29 ../
dr-xr-xr-x 2 user user 4096 Apr 24 20:29 minitest-5.10.1/
drwxr-xr-x 3 user user 4096 Apr 24 20:29 rdoc-5.0.1/
```
And again, for some reason `minitest` missing o+w

**Comment by hurricup** [comment]
Is there any workaround to install 2.4.8?

**Comment by raelgc** [comment]
This happens only for `2.4.8`?

**Comment by hurricup** [comment]
Yes. Only this one. I have images containing all versions since 2.0. And only 2.4.8 fails.

**Comment by hurricup** [comment]
Also, is there any particular reason this ruby binary is missing? 
For example, for 2.4.10:
```
Step 17/17 : run bash -l -c "rvm install ruby-2.4.10 --binary --debug  && rvm cleanup all"
 ---> Running in be66225d9d9c
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.10.tar.bz2 --insecure
Remote file exists https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.10.tar.bz2
ruby-2.4.10 - install
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.10.tar.bz2 --insecure
Remote file exists https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.10.tar.bz2
ruby-2.4.10 - #already removed src/ruby-2.4.10
ruby-2.4.10 - #already removed rubies/ruby-2.4.10
Searching for binary rubies, this might take some time.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.10.tar.bz2 --insecure
Remote file exists https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.10.tar.bz2
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.10.tar.bz2
rvm_autolibs_flag=4
Checking requirements for ubuntu.
...
```
And for 2.4.8:
```
Step 18/18 : run bash -l -c "rvm install ruby-2.4.8 --binary --debug && rvm cleanup all"
 ---> Running in 62ab59584c2a
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.4.8.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rubies.travis-ci.org/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://rubies.travis-ci.org/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2
rvm_remote_server_url3 not found
No remote file name found
ruby-2.4.8 - install
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.4.8.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rubies.travis-ci.org/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://rubies.travis-ci.org/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2
rvm_remote_server_url3 not found
No remote file name found
ruby-2.4.8 - #already removed src/ruby-2.4.8
ruby-2.4.8 - #already removed rubies/ruby-2.4.8
Searching for binary rubies, this might take some time.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.4.8.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rubies.travis-ci.org/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://rubies.travis-ci.org/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2
rvm_remote_server_url3 not found
No remote file name found
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.4.8.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 60 --head https://rubies.travis-ci.org/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2 --insecure
Remote file does not exist https://rubies.travis-ci.org/ubuntu/18.04/x86_64/ruby-2.4.8.tar.bz2
rvm_remote_server_url3 not found
No remote file name found
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
__rvm_rm_rf already gone: /home/user/.rvm/tmp/6*
```

Also, why there are multiple curl requests for the same url?

**Comment by raelgc** [comment]
Interesting, I just checked the list and it's really missing. I'll try to compile during this weekend in a 18.04 VM and upload.

**Comment by raelgc** [comment]
Just pushed a PR with 2.4.8. Anyway, it's uploaded to RVM servers, maybe you can try install it again (it should just warn you about missing checksum validation).

**Comment by raelgc** [comment]
Now merged into master. Please, let me know if it works now.

**Comment by hurricup** [comment]
Binary installation works fine now! Thanks

**Comment by raelgc** [comment]
Just a friendly reminder that `2.4.8` is outdated and even the [support for 2.4 series has ended](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/).

**Comment by hurricup** [comment]
Thank you, i'm aware of that. Still - need to test that things working fine on 2.4.8. 
Also, installing from sources still not working.

**Comment by hurricup** [comment]
Tried to force all rubies to install from binaries. Seems 2.4.0 missing too.

**Comment by raelgc** [comment]
Yeap, some of them are missing because on that time no volunteers were building them. I started to build them some... months?... ago, but faced the problem with 2.4.8 on that time and gave up.

Versions supposed to have binaries are the ones that people contribute. I'm trying to build basically on every new ruby release, for 20.04, and I'll try keep the pace for 18.04.

But any help will be really appreciated. Send me an email to `rael.gc@gmail.com` if you want to help with 18.04.
