### ISSUE TITLE
Error running '__rvm_make -j12' on macOS 10.15.5 while installing ruby-2.3.8

### ISSUE THREAD

**Issue by Ramesh-Veeriaperumal** [rvm/rvm#4966]
## Description

Unable to install ruby-2.3.8 on mac OS 10.15.5

## Steps to reproduce

```
rvm install 2.3.8 --with-openssl-dir=$(brew --prefix openssl@1.0)
Checking requirements for osx.
Installing requirements for osx.
Updating system - please wait
Installing required packages: openssl - please wait
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/rameshveeriaperumal/.rvm/rubies/ruby-2.3.8, this may take a while depending on your cpu(s)...
ruby-2.3.8 - #downloading ruby-2.3.8, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.7M  100 13.7M    0     0   341k      0  0:00:41  0:00:41 --:--:--  462k
ruby-2.3.8 - #extracting ruby-2.3.8 to /Users/rameshveeriaperumal/.rvm/src/ruby-2.3.8 - please wait
ruby-2.3.8 - #configuring - please wait
ruby-2.3.8 - #post-configuration - please wait
ruby-2.3.8 - #compiling - please wait
Error running '__rvm_make -j12',
please read /Users/rameshveeriaperumal/.rvm/log/1594563457_ruby-2.3.8/make.log

There has been an error while running make. Halting the installation.
```
## Expected behavior

To get a working ruby

## Actual behavior

```
tail -50 /Users/rameshveeriaperumal/.rvm/log/1594563457_ruby-2.3.8/make.log
                                         ^
                                           _Nonnull 
/usr/local/include/stdlib.h:354:22: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
         strtouq(const char *__str, char **__endptr, int __base);
                            ^
/usr/local/include/stdlib.h:354:22: note: insert '_Nullable' if the pointer may be null
         strtouq(const char *__str, char **__endptr, int __base);
                            ^
                              _Nullable 
/usr/local/include/stdlib.h:354:22: note: insert '_Nonnull' if the pointer should never be null
         strtouq(const char *__str, char **__endptr, int __base);
                            ^
                              _Nonnull 
/usr/local/include/stdlib.h:354:35: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
         strtouq(const char *__str, char **__endptr, int __base);
                                         ^
/usr/local/include/stdlib.h:354:35: note: insert '_Nullable' if the pointer may be null
         strtouq(const char *__str, char **__endptr, int __base);
                                         ^
                                          _Nullable
/usr/local/include/stdlib.h:354:35: note: insert '_Nonnull' if the pointer should never be null
         strtouq(const char *__str, char **__endptr, int __base);
                                         ^
                                          _Nonnull
/usr/local/include/stdlib.h:354:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
         strtouq(const char *__str, char **__endptr, int __base);
                                          ^
/usr/local/include/stdlib.h:354:36: note: insert '_Nullable' if the pointer may be null
         strtouq(const char *__str, char **__endptr, int __base);
                                          ^
                                            _Nullable 
/usr/local/include/stdlib.h:354:36: note: insert '_Nonnull' if the pointer should never be null
         strtouq(const char *__str, char **__endptr, int __base);
                                          ^
                                            _Nonnull 
/usr/local/include/stdlib.h:356:13: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
extern char *suboptarg;         /* getsubopt(3) external variable */
            ^
/usr/local/include/stdlib.h:356:13: note: insert '_Nullable' if the pointer may be null
extern char *suboptarg;         /* getsubopt(3) external variable */
            ^
              _Nullable 
/usr/local/include/stdlib.h:356:13: note: insert '_Nonnull' if the pointer should never be null
extern char *suboptarg;         /* getsubopt(3) external variable */
            ^
              _Nonnull 
190 warnings generated.
linking shared-object -test-/string.bundle
make: *** [build-ext] Error 2
+__rvm_make:0> return 2
```

**Debug mode**:

## Environment info

```
system:

  system:
    uname:        "Darwin FWS-CHE-LT-2882.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.15"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)"
    zsh:          "/bin/zsh => zsh 5.7.1 (x86_64-apple-darwin19.0)"
    remote_path:  "osx/10.15/x86_64"
    xcode:        "11.5"

  rvm:
    version:      "1.29.10 (latest)"
    updated:      "5 hours 1 minute 47 seconds ago"
    path:         "/Users/rameshveeriaperumal/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/local/bin/rake"

  environment:
    PATH:         "/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/rameshveeriaperumal/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

```

**Comment by walterdavis** [comment]
I am having the same issue. Cannot install any version of Ruby I'v tried. I completely nuked and re-installed Homebrew, to no effect. macOS 10.15.6 and Xcode 11.6. I have tried both rvm head and stable, same error, same line as above. `Error running '__rvm_make -j12'`

**Comment by walterdavis** [comment]
The last line of the log before it dies is: `make: ./miniruby: Permission denied`

**Comment by walterdavis** [comment]
Rolling back to RVM version 1.27.0 seems to have solved this for me. Nothing higher than that appears to work here.

**Comment by Ramesh-Veeriaperumal** [comment]
Thanks @walterdavis , I rollbacked to 1.27.0, still faced some issue during installation, This time different error, Followed the steps mentioned in https://stackoverflow.com/questions/59189943/build-failed-os-x-10-15-1-using-ruby-build-20191124-when-installing-ruby-2-4-0, Now i could able to install any ruby version.

**Comment by pedrofurtado** [comment]
Hey everyone! Can you guys confirm if the error persists in rvm 1.29.12 (latest stable version)? 🤝

**Comment by walterdavis** [comment]
I haven't upgraded in a while, but I can confirm that 1.29.9 is working fine for me here. I just installed Ruby 2.7.2, which I hadn't used before, and it worked flawlessly. I got an archive install, for what feels like the first time, and that took almost zero time to install.

**Comment by wintermeyer** [comment]
The following commands all lead to an error on my new MacBook Air :

- rvm install 2.5.8 --with-openssl-dir=$(brew --prefix openssl)
- rvm install 2.5.8

I tried 
- rvm 1.29.12-next
- rvm 1.27.0

System:
- macOS Big Sur 11.1
- MacBook Air (M1, 2020)
- 16 GB RAM

The error:
````
$ rvm install 2.5.8 --with-openssl-dir=$(brew --prefix openssl)    
ruby-2.5.8 - #removing src/ruby-2.5.8 - please wait
Checking requirements for osx.
Certificates bundle '/opt/homebrew/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/stefan/.rvm/rubies/ruby-2.5.8, this may take a while depending on your cpu(s)...
ruby-2.5.8 - #downloading ruby-2.5.8, this may take a while depending on your connection...
ruby-2.5.8 - #extracting ruby-2.5.8 to /Users/stefan/.rvm/src/ruby-2.5.8 - please wait
ruby-2.5.8 - #configuring - please wait
ruby-2.5.8 - #post-configuration - please wait
ruby-2.5.8 - #compiling - please wait
Error running '__rvm_make -j8',
please read /Users/stefan/.rvm/log/1611141181_ruby-2.5.8/make.log

There has been an error while running make. Halting the installation.
````

**Comment by wintermeyer** [comment]
This might help to debug the problem:

**/Users/stefan/.rvm/log/1611141181_ruby-2.5.8/make.log**
````
compiling modify.c
compiling fiddle.c
compiling set_len.c
closure.c:264:14: error: implicit declaration of function 'ffi_prep_closure' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    result = ffi_prep_closure(pcl, cif, callback, (void *)self);
             ^
1 error generated.
make[2]: *** [closure.o] Error 1
make[2]: *** Waiting for unfinished jobs....
compiling zlib.c
compiling enc_str_buf_cat.c
compiling psych.c
compiling new.c
compiling psych_emitter.c
compiling escape.c
make[1]: *** [ext/fiddle/all] Error 2
make[1]: *** Waiting for unfinished jobs....
compiling psych_parser.c
compiling psych_to_ruby.c
linking shared-object -test-/string.bundle
linking shared-object date_core.bundle
compiling psych_yaml_tree.c
linking shared-object cgi/escape.bundle
linking shared-object psych.bundle
linking shared-object zlib.bundle
make: *** [build-ext] Error 2
+__rvm_make:0> return 2
````

**Comment by wintermeyer** [comment]
Work around:

    rvm install 2.5.8 --with-out-ext=fiddle

**Comment by zanella** [comment]
This worked for me on MacOS Catalina: 

`$ export optflags=" -Wno-nullability-completeness " && rvm install 2.5.8`

**Comment by slikstir** [comment]
> This worked for me on MacOS Catalina:
> 
> `$ export optflags=" -Wno-nullability-completeness " && rvm install 2.5.8`

This worked for me on an Intel MacOS Big Sur after trying about 20 other described fixes

**Comment by KLCrow** [comment]
> 1.29.12

I've got "Error running '__rvm_make -j4'," when installing ruby 2.6.7

**Comment by p-funky** [comment]
> > 1.29.12
> 
> I've got "Error running '__rvm_make -j4'," when installing ruby 2.6.7

Same here. Got "Error running '__rvm_make -j4'," when installing ruby 2.7.3

**Comment by maumercado** [comment]
What worked for me given the new default functionality of CLANG in Catalina OSX
```sh
export optflags=" -Wno-nullability-completeness -Wno-error=implicit-function-declaration" && rvm install 2.6.7
```

**Comment by mayur-kambariya** [comment]
1) Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
2) Uninstall Homebrew
  ```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
  rm -rf /opt/homebrew/*
  sudo rm -rf /opt/homebrew
```
3) Reinstall Homebrew
  `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
4) Restart terminal
5) Check Homebrew is working fine: `brew doctor`
6) Reinstall openssl: `brew install openssl`
7) Install Ruby: `rvm install 2.7` Or any version

**Comment by yashka713** [comment]
@mayur-kambariya

Your decision caused an error in the associated gems, in my case it was pg and libpq.

**Comment by mayur-kambariya** [comment]
> @mayur-kambariya
> 
> Your decision caused an error in the associated gems, in my case, it was pg and libpq.

Please add details error here @yashka713

**Comment by yashka713** [comment]
@mayur-kambariya 

After the steps described, I needed to install gems for the project, and `pg` failed with:

```sh
Installing pg 1.1.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/pg-1.1.4/ext
/Users/Yaroslav/.rvm/rubies/ruby-2.6.6/bin/ruby -I /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0 -r ./siteconf20220524-85150-11xfit8.rb extconf.rb
checking for pg_config... yes
Using config values from /opt/homebrew/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... no
checking for PQconnectdb() in -llibpq... no
checking for PQconnectdb() in -lms/libpq... no
Can't find the PostgreSQL client library (libpq)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/Yaroslav/.rvm/rubies/ruby-2.6.6/bin/$(RUBY_BASE_NAME)
        --with-pg
 --without-pg
        --enable-windows-cross
        --disable-windows-cross
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib
        --with-pqlib
        --without-pqlib
        --with-libpqlib
        --without-libpqlib
        --with-ms/libpqlib
        --without-ms/libpqlib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/extensions/x86_64-darwin-21/2.6.0/pg-1.1.4/mkmf.log

extconf failed, exit code 1

 /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:99:in `run'
  /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/tempfile.rb:295:in `open'
  /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in `build'
  /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:185:in `block in build_extension'
  /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
  /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:181:in `build_extension'
  /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:229:in `block in build_extensions'
  /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:226:in `each'
  /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:226:in `build_extensions'
  /Users/Yaroslav/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems/installer.rb:833:in `build_extensions'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/rubygems_gem_installer.rb:66:in `build_extensions'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/source/rubygems.rb:199:in `install'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/worker.rb:62:in `apply_func'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/worker.rb:54:in `loop'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/worker.rb:54:in `process_queue'
  /Users/Yaroslav/.rvm/gems/ruby-2.6.6@project/gems/bundler-2.2.29/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing pg (1.1.4), and Bundler cannot continue.

In Gemfile:
  pg
```

But I already had installed `postgresql` and `libpq`.

This helps me to install `ruby` for an `arm` architecture

- install ruby with
  ```sh
  rvm install 2.6.6 --with-out-ext=fiddle
  ```
- fix raised errors
  ```shell
  gem pristine --all
  ```
- install required dependency(for `sass` gem)
  ```shell
  brew install libffi
  ```

**Comment by mayur-kambariya** [comment]
```
export optflags="-Wno-error=implicit-function-declaration”
brew install libffi
rvm install 2.6.6 --with-out-ext=fiddle
```

**Comment by iAaquibjawed** [comment]
Geting error on mac m1 pro chip while installing ruby verion 2.6.5
Error running '__rvm_make -j10',
please read /Users/sammalik/.rvm/log/1666964526_ruby-2.6.5/make.log

There has been an error while running make. Halting the installation.

**Comment by JasonLunn** [comment]
Unable to install ruby-2.7.0. Compilation an installation steps claim to have finished, but I have no new installations under `~/.rvm/rubies`.

* macOS 12.6.1
* rvm 1.29.12

Attempted install via:

```
export optflags=" -Wno-nullability-completeness -Wno-error=implicit-function-declaration" && rvm install 2.7.0 --with-out-ext=fiddle
```

Results:
```
ruby-2.7.0 - #removing src/ruby-2.7.0............
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/jason/.rvm/rubies/ruby-2.7.0, this may take a while depending on your cpu(s)...
ruby-2.7.0 - #downloading ruby-2.7.0, this may take a while depending on your connection...
ruby-2.7.0 - #extracting ruby-2.7.0 to /Users/jason/.rvm/src/ruby-2.7.0...........................................
ruby-2.7.0 - #configuring...........................................................................
ruby-2.7.0 - #post-configuration.......
ruby-2.7.0 - #compiling........................................................................|
ruby-2.7.0 - #installing.......................................................................|
ruby-2.7.0 - #making binaries executable....
Missing 'ruby' in 'rubygems_detect_ruby_lib_gem_path'.
ruby-2.7.0 - #downloading rubygems-3.0.9
ruby-2.7.0 - #extracting rubygems-3.0.9............................................
ruby-2.7.0 - #removing old rubygems.....................................................................
ruby-2.7.0 - #installing rubygems-3.0.9.
ruby-2.7.0 - #gemset created /Users/jason/.rvm/gems/ruby-2.7.0@global
Required ruby-2.7.0 is not installed.
To install do: 'rvm install "ruby-2.7.0"'
Required ruby-2.7.0 is not installed.
```

**Comment by G33kNoob** [comment]
`You can migrate your previously installed formula list with:
  brew bundle dump
Requirements installation failed with status: 1.`

got error on M1

**Comment by AndyObtiva** [comment]
I get this error on my MacBook Pro with 2.6 GHz 6-Core Intel Core i7 running on Mac Ventura 13.3.1 (22E261).

**Comment by AndyObtiva** [comment]
@yesh4gvm yes. 

The problem happened to me after I migrated another mac to an Intel Mac I got with MacOS Ventura. 

The problem turned out to be caused by a defective installation of Homebrew, due to missing the latest XCode on this Intel Mac laptop. 

I installed the latest XCode, reinstalled homebrew, and reinstalled RVM, then installing Ruby worked. 

I hope this solution helps you and other people facing the problem.

**Comment by yesh4gvm** [comment]
thanks @AndyObtiva for your information. The way to figure out for me is to remove openssl@3 from machine and installing openssl@1 for this installation.

This was due to openssl@3 due to which this throws error. Some gem libraries are dependent on openssl@3 due to which this is happening.After installing ruby successfully through rvm if some gem libraries try to install openssl@3 then to it will work.

But if previous setup was done for 2.6.6 and now you required for 2.7.1 then it will require openssl@1. Some commands to overcome.

`brew uninstall openssl@3`
`brew install openssl@1`

**Comment by czorkol** [comment]
> thanks @AndyObtiva for your information. The way to figure out for me is to remove openssl@3 from machine and installing openssl@1 for this installation.
> 
> This was due to openssl@3 due to which this throws error. Some gem libraries are dependent on openssl@3 due to which this is happening.After installing ruby successfully through rvm if some gem libraries try to install openssl@3 then to it will work.
> 
> But if previous setup was done for 2.6.6 and now you required for 2.7.1 then it will require openssl@1. Some commands to overcome.
> 
> `brew uninstall openssl@3` `brew install openssl@1`

i resolved this problem with these 2 line after 2 days. Thank you so much! :) 

`brew uninstall openssl@3` 
`brew install openssl@1`

**Comment by cloudmagic80** [comment]
> vm install 2.5.8 --with-out-ext=fiddle

This worked for me! Mac M2 Pro 13.2.1 (22D68)

**Comment by wayne-weibel** [comment]
> I installed the latest XCode, reinstalled Homebrew, and reinstalled RVM, then installing Ruby worked.

This finally got me unstuck.  Current homebrew did not recognize rvm so had to install that with 
`curl -sSL https://get.rvm.io | bash`

**Comment by dprophete** [comment]
> `brew uninstall openssl@3`

the problem is you might have a ton of other apps using openssl@3:

```
~/dev/flutter-runtime (main*) » brew uninstall openssl@3
Error: Refusing to uninstall /opt/homebrew/Cellar/openssl@3/3.2.0_1
because it is required by astrometry-net, bat, cocoapods, elixir, erlang, exa, fastlane, ffmpeg, gnutls, gping, grip, httpie, jc, libevent, libgit2, libmicrohttpd, librist, libssh, libssh2, libwebsockets, md5sha1sum, mercurial, mosquitto, nghttp2, node, pyenv, python@3.10, python@3.11, python@3.12, python@3.9, ruby@3.1, scrcpy, srt, tmux, unbound and wget, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies openssl@3
```

I am a little worried here :-)

(and `rvm install 2.5.8 --with-out-ext=fiddle` also failed on my M2...)

**Comment by wuxulome** [comment]
This worked for me! Mac M3 Pro 14.25
```
export PKG_CONFIG_PATH="/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib/pkgconfig"
rvm install 2.6.5 --default --with-openssl-dir=/opt/homebrew/Cellar/openssl@1.1/1.1.1w
```

**Comment by silva-fernanda** [comment]
forget rvm, use **rbenv** install. it takes longer to install ruby, not sure why, but it worked.
