### ISSUE TITLE
cannot     load such file -- zlib (LoadError)

### ISSUE THREAD

**Issue by uestcsp** [rvm/rvm#4981]
ENV:
Mac macOS Catalina 10.15.6
Xcode 12.0 && Command Line Tools for 12.0
rvm version 1.29.10

OPT:
`rvm_rubygems_version=2.7.10 rvm install 1.9.3`

RESULT:
ruby-1.9.3-p551 - #downloading rubygems-2.7.10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  843k  100  843k    0     0  24669      0  0:00:35  0:00:35 --:--:-- 39579
ruby-1.9.3-p551 - #extracting rubygems-2.7.10.....
ruby-1.9.3-p551 - #removing old rubygems........
ruby-1.9.3-p551 - #installing rubygems-2.7.10...
Error running 'env GEM_HOME=/Users/shaopeng/.rvm/gems/ruby-1.9.3-p551@global GEM_PATH= /Users/shaopeng/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -d /Users/shaopeng/.rvm/src/rubygems-2.7.10/setup.rb --no-document',
please read /Users/shaopeng/.rvm/log/1600935236_ruby-1.9.3-p551/rubygems.install.log

ERROR LOG:
 1 [2020-09-24 16:16:36] /Users/shaopeng/.rvm/rubies/ruby-1.9.3-p551/bin/ruby
  2 current path: /Users/shaopeng/.rvm/src/rubygems-2.7.10
  3 PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/op    t/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:    /Library/Apple/usr/bin:/Users/shaopeng/.rvm/bin
  4 command(7): env GEM_HOME=/Users/shaopeng/.rvm/gems/ruby-1.9.3-p551@global GEM_PATH= /Users/shaopeng/.rvm    /rubies/ruby-1.9.3-p551/bin/ruby -d /Users/shaopeng/.rvm/src/rubygems-2.7.10/setup.rb --no-document
  5 Exception `LoadError' at /Users/shaopeng/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rubygems.rb:1264 - c    annot load such file -- rubygems/defaults/operating_system
  6 Exception `LoadError' at /Users/shaopeng/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/rubygems.rb:1273 - c    annot load such file -- rubygems/defaults/ruby
  7 /Users/shaopeng/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/yaml.rb:84:in `<top (required)>':
  8 It seems your ruby installation is missing psych (for YAML output).
  9 To eliminate this warning, please install libyaml and reinstall your ruby.
 10 YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0    ).
 **_11 /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require': cannot     load such file -- zlib (LoadError)_**
 12     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require    '
 13     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/package.rb:47:in `<top (required)>'
 14     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require    '
 15     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require
from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/commands/pristine_command.rb:3:in `<top (    required)>'
 17     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require    '
 18     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/core_ext/kernel_require.rb:54:in `require    '
 19     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/commands/setup_command.rb:583:in `regener    ate_binstubs'
 20     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/commands/setup_command.rb:155:in `execute    '
 21     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/command.rb:313:in `invoke_with_build_args    '
 22     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/command_manager.rb:173:in `process_args'
 23     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/command_manager.rb:143:in `run'
 24     from /Users/shaopeng/.rvm/src/rubygems-2.7.10/lib/rubygems/gem_runner.rb:59:in `run'
 25     from setup.rb:46:in `<main>'
 26 Bundler 1.16.6 installed
 27 RubyGems 2.7.10 installed

what's wrong with this?

**Comment by syter** [comment]
any solutions? @uestcsp

**Comment by uestcsp** [comment]
> any solutions? @uestcsp

yes, it has been Resolved

**Comment by dfop02** [comment]
can you share how solved, @uestcsp ? I have similar issues

**Comment by xvrdmng** [comment]
Hi, Im having the same zlib issue, please share how you fix the issue, thanks!

**Comment by martyb688** [comment]
Hello @uestcsp. I am also having the same problem, please share the fix. Thanks

**Comment by uestcsp** [comment]
I will write a detailed introduction explaining how to solve this problem later.

**Comment by xvrdmng** [comment]
Thanks @uestcsp, I took an alternative route I installed chruby with rubybuild, that didn't do the trick, the errors are related to the new command line tools, I downloaded XCode 11.7, and with the sudo xcode-select -s command I pointed to the command line tools inside the old xcode.

Then I used the following commands:

brew install rbenv/tap/openssl@1.0
RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.0)" ruby-build 1.9.3-p551 ~/.rubies/ruby-1.9.3 

I think it will be able to fix the issue in rvm too but I haven't tried. Before the installation I reverted to the normal Commad Line Tools with sudo xcode-select -s /Library/Developer/CommandLineTools

Hope this will help someone

**Comment by uestcsp** [comment]
@xvrdmng yes, it's the problem of Xcode
Xcode 11.7 + Command Line Tool 11.5 + openssl@1.0(install with homebrew) can resolve this issue
