### ISSUE TITLE
Gem issue with Ruby 3.0.0 install

### ISSUE THREAD

**Issue by jzakiya** [rvm/rvm#5019]
System: PCLinuxOS 2021; KDE5; Kernel 5.9.16; ZSH

Installed Ruby 3.0.0 yesterday (Xmas) and it can't access rubygems.
Rubies  *preview1|2 and rc1 installed|ran with no problem.
libyaml on system named prefixed lib64yaml*, but again, all other rubies (Ruby-*, JRuby-*, Truffleruby-20-*) work.

```
➜  ~ rvm use ruby-3.0.0
Using /home/jzakiya/.rvm/gems/ruby-3.0.0
Error loading RubyGems plugin "/home/jzakiya/.rvm/gems/ruby-3.0.0/plugins/yard_plugin.rb": cannot load such file -- /home/jzakiya/.rvm/gems/ruby-3.0.0-rc1/gems/yard-0.9.25/lib/rubygems_plugin.rb (LoadError)
/home/jzakiya/.rvm/gems/ruby-3.0.0/gems/yaml-0.1.1/lib/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
<internal:/home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': /home/jzakiya/.rvm/gems/ruby-3.0.0/gems/stringio-3.0.0/lib/stringio.so: undefined symbol: rb_cData - /home/jzakiya/.rvm/gems/ruby-3.0.0/gems/stringio-3.0.0/lib/stringio.so (LoadError)
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/psych/nodes/node.rb:2:in `<top (required)>'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/psych/nodes.rb:2:in `<top (required)>'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/psych.rb:15:in `<top (required)>'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/jzakiya/.rvm/gems/ruby-3.0.0/gems/yaml-0.1.1/lib/yaml.rb:4:in `<top (required)>'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems.rb:641:in `load_yaml'
        from /home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/config_file.rb:336:in `load_file'
        from /home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/config_file.rb:181:in `initialize'
        from /home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/gem_runner.rb:73:in `new'
        from /home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/gem_runner.rb:73:in `do_configuration'
        from /home/jzakiya/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/gem_runner.rb:38:in `run'
        from /home/jzakiya/.rvm/rubies/ruby-3.0.0/bin/gem:21:in `<main>'
➜  ~ 

```

**Comment by michaelbach** [comment]
I have (nearly) the same issue (using Jekyll) after update to Ruby 3.0.0. The advice "please install libyaml and reinstall your ruby" did not solve the issue for me. Ruby runs, but trying to run gem results in the error `…  It seems your ruby installation is missing psych (for YAML output). To eliminate this warning, please install libyaml and reinstall your ruby. …`

**Comment by DonPiotr** [comment]
Same with rbenv. Any clue?

**Comment by jzakiya** [comment]
It has been 5 months now, and Ruby 3 is unusable not only if PCLOS but also Manjoro (via Virtual Box).
This is not an upstream issue, as the same problem exists for both Linux OSs.

Up until Ruby 3.0, all the other MRI rubies compiled and ran (with gems), then all of a sudden 3.0 somehow can't compile and run on the same systems all the other MRI rubies still run on.  The common element here is the same system (and libraries) that run all the other rubies.  

This is not a problem with PCLOS or Manjaro, this is an RVM problem with creating a correct install for Ruby 3.0.
Please fix your problems!

```
[jzakiya@jzakiya-pc ~]$ uname -a
Linux jzakiya-pc 5.10.34-1-MANJARO #1 SMP Sun May 2 11:29:56 UTC 2021 x86_64 GNU/Linux

[jzakiya@jzakiya-pc ~]$ rvm reinstall ruby-3.0.1
ruby-3.0.1 - #removing rubies/ruby-3.0.1..
Searching for binary rubies, this might take some time.
No binary rubies available for: manjaro/21.0.4/x86_64/ruby-3.0.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for manjaro.
Requirements installation successful.
Installing Ruby from source to: /home/jzakiya/.rvm/rubies/ruby-3.0.1, this may take a while depending on your cpu(s)...
ruby-3.0.1 - #downloading ruby-3.0.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0  2597k      0  0:00:07  0:00:07 --:--:-- 4344k
ruby-3.0.1 - #extracting ruby-3.0.1 to /home/jzakiya/.rvm/src/ruby-3.0.1.....
ruby-3.0.1 - #configuring.........................................................................
ruby-3.0.1 - #post-configuration..
ruby-3.0.1 - #compiling..........................................................................................
ruby-3.0.1 - #installing.....................
ruby-3.0.1 - #making binaries executable...
Installed rubygems 3.2.15 is newer than 3.0.9 provided with installed ruby, skipping installation, use --force to force installation.
ruby-3.0.1 - #gemset created /home/jzakiya/.rvm/gems/ruby-3.0.1@global
ruby-3.0.1 - #importing gemset /home/jzakiya/.rvm/gemsets/global.gems..........................................................
ruby-3.0.1 - #generating global wrappers........
ruby-3.0.1 - #gemset created /home/jzakiya/.rvm/gems/ruby-3.0.1
ruby-3.0.1 - #importing gemsetfile /home/jzakiya/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-3.0.1 - #generating default wrappers.............
Error running 'run_gem_wrappers regenerate',
please read /home/jzakiya/.rvm/log/1621275061_ruby-3.0.1/gemset.wrappers.default.log
ruby-3.0.1 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-3.0.1 - #complete 
Ruby was built without documentation, to build it run: rvm docs generate-ri
Making gemset ruby-3.0.1 pristine...........................................................................................................................................|
'command gem pristine bigdecimal --version 3.0.0 date --version 3.1.0 dbm --version 1.1.0 digest --version 3.0.0 etc --version 1.2.0 fcntl --version 1.0.0 fiddle --version 1.0.6 fiddle --version 1.0.5 gdbm --version 2.1.0 io-console --version 0.5.7 io-nonblock --version 0.1.0 io-wait --version 0.1.0 json --version 2.5.1 openssl --version 2.2.0 pathname --version 0.1.0 psych --version 3.3.0 psych --version 3.2.1 racc --version 1.5.1 readline-ext --version 0.1.1 stringio --version 3.0.0 strscan --version 3.0.0 syslog --version 0.1.0 zlib --version 1.1.0' failed, you need to fix these gems manually.
.
Error running '__rvm_with ruby-3.0.1 gemset_pristine',
please read /home/jzakiya/.rvm/log/1621275061_ruby-3.0.1/gemset.pristine-ruby-3.0.1.log
```
