### ISSUE TITLE
Error on installing ruby-3.0.1 on Ubuntu-20.04.2

### ISSUE THREAD

**Issue by gencer** [rvm/rvm#5065]
## Description

rvm fails to compile/install Ruby 3.0.1 from source.

```bash
Error running '__rvm_make -j2',
please read /var/lib/buildkite-agent/.rvm/log/1617965270_ruby-3.0.1/make.log

There has been an error while running make. Halting the installation.
```

## Steps to reproduce

 1. `rvm install 3.0.1`
 2. 

## Expected behavior

Expedted the build succees.

## Actual behavior

* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/gencer/a399a50058c187188d530e6e6d5a1647) - only for issues with `install`

## Environment info

```

ruby-3.0.0:

  system:
    uname:        "Linux bk-focal-i-RcaihZ6FhQ 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "20.04"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/20.04/x86_64"

  rvm:
    version:      "1.29.12-next (master)"
    updated:      "4 minutes 6 seconds ago"
    path:         "/var/lib/buildkite-agent/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "3.0.0p0"
    date:         "2020-12-25"
    platform:     "x86_64-linux"
    patchlevel:   "2020-12-25 revision 95aff21468"
    full_version: "ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]"

  homes:
    gem:          "/var/lib/buildkite-agent/.rvm/gems/ruby-3.0.0"
    ruby:         "/var/lib/buildkite-agent/.rvm/rubies/ruby-3.0.0"

  binaries:
    ruby:         "/var/lib/buildkite-agent/.rvm/rubies/ruby-3.0.0/bin/ruby"
    irb:          "/var/lib/buildkite-agent/.rvm/rubies/ruby-3.0.0/bin/irb"
    gem:          "/var/lib/buildkite-agent/.rvm/rubies/ruby-3.0.0/bin/gem"
    rake:         "/var/lib/buildkite-agent/.rvm/rubies/ruby-3.0.0/bin/rake"

  environment:
    PATH:         "/var/lib/buildkite-agent/.rvm/gems/ruby-3.0.0/bin:/var/lib/buildkite-agent/.rvm/gems/ruby-3.0.0@global/bin:/var/lib/buildkite-agent/.rvm/rubies/ruby-3.0.0/bin:/var/lib/buildkite-agent/vcpkg:/var/lib/buildkite-agent/.gvm/pkgsets/go1.16.2/global/bin:/var/lib/buildkite-agent/.gvm/gos/go1.16.2/bin:/var/lib/buildkite-agent/.gvm/pkgsets/go1.16.2/global/overlay/bin:/var/lib/buildkite-agent/.gvm/bin:/var/lib/buildkite-agent/.gvm/bin:/var/lib/buildkite-agent/.pyenv/plugins/pyenv-virtualenv/shims:/var/lib/buildkite-agent/.pyenv/shims:/var/lib/buildkite-agent/.pyenv/bin:/var/lib/buildkite-agent/vcpkg:/var/lib/buildkite-agent/.gvm/pkgsets/go1.16.2/global/bin:/var/lib/buildkite-agent/.gvm/gos/go1.16.2/bin:/var/lib/buildkite-agent/.gvm/pkgsets/go1.16.2/global/overlay/bin:/var/lib/buildkite-agent/.gvm/bin:/var/lib/buildkite-agent/.gvm/bin:/var/lib/buildkite-agent/.pyenv/plugins/pyenv-virtualenv/shims:/var/lib/buildkite-agent/.pyenv/shims:/var/lib/buildkite-agent/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/var/lib/buildkite-agent/n/bin:/var/lib/buildkite-agent/.rvm/bin:/var/lib/buildkite-agent/.rvm/bin"
    GEM_HOME:     "/var/lib/buildkite-agent/.rvm/gems/ruby-3.0.0"
    GEM_PATH:     "/var/lib/buildkite-agent/.rvm/gems/ruby-3.0.0:/var/lib/buildkite-agent/.rvm/gems/ruby-3.0.0@global"
    MY_RUBY_HOME: "/var/lib/buildkite-agent/.rvm/rubies/ruby-3.0.0"
    IRBRC:        "/var/lib/buildkite-agent/.rvm/rubies/ruby-3.0.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

```

**Comment by raelgc** [comment]
The error appears to be around this:

```
make[2]: Entering directory '/var/lib/buildkite-agent/.rvm/src/ruby-3.0.1'
./tool/file2lastrev.rb:6:in `require': cannot load such file -- optparse (LoadError)
	from ./tool/file2lastrev.rb:6:in `<main>'
```

**Comment by gencer** [comment]
@raelgc Ah. I thought I've quoted these lines in my issue. Thanks for the lookup. Any ideas?

**Comment by markoong** [comment]
Same for v 2.7.2, 2.7.3, Mageia 8 GNU/Linux:

make[2]: Entering directory '/home/user/.rvm/src/ruby-2.7.3'
./tool/file2lastrev.rb:6:in `require': cannot load such file -- optparse (LoadError)
        from ./tool/file2lastrev.rb:6:in `<main>'
make[2]: *** [uncommon.mk:1130: revision.tmp] Error 1

**Comment by smoothdvd** [comment]
Install 2.7.3 and set global version to 2.7.3, then install 3.0.1 again, no error.

**Comment by raelgc** [comment]
Any lucky [updating `rvm` to `master`](https://github.com/rvm/ubuntu_rvm#2-i-need-to-upgrade-to-master-without-wait-for-new-package-release)?

**Comment by GeoffKarnov** [comment]
```
rvm --version
rvm 1.29.12 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
```

I had the same issue when installing `ruby-3.0.2` on `Ubuntu 21.04`
using ruby 2.7.3 (which I already had installed) made the install step work: 
```
rvm use ruby-2.7.3
rvm install ruby-3.0.2
```

**Comment by duzhor** [comment]
Same on CentOS-6. Use `rvm install 2.2` to solved. I don't know how to solve the higher version.

**Comment by fizvlad** [comment]
Encountered this error while upgrading ruby from 3.1.0 to 3.1.1. Somehow installation `rvm install 3.1.1` worked after switching to ruby 3.0.3 :thinking:

**Comment by Gam1ta** [comment]
I was installing the ubuntu 20.04 operating system and I was installing ruby 3.0.0 but it sent me the same error so I had to use version 3.1.1, please clarify that if it is a small project it is easy to restructure it in case it a large project I do not recommend it.

- rvm install 3.1.1

**Comment by aswin2108** [comment]
I faced a similar issue:
```
Error running '__rvm_make -j8',
please read /usr/share/rvm/log/1663317642_ruby-3.0.0/make.log
There has been an error while running make. 
Halting the installation.
```
I am using Ubuntu 22.04 LTS. This error was appearing when excecuting ```rvm install ruby```  
Solved when ```rvm install 3.1.1``` was executed!

**Comment by saviokmua** [comment]
I had a similar issue when installing old ruby version (2.4.0) in Docker:

Solution:

```
rvm pkg install openssl
rvm install 2.4.0 -C --with-openssl-dir=/usr/local/rvm/usr

```

**Comment by snappa** [comment]
> rvm install 3.1.1 on LTS 22.04 worked for some reason.  I suspect that it's because it didn't need to be compiled.  I then tried "rvm install 2.7.2" and it failed with the same error.

**Comment by cauta** [comment]
> I had a similar issue when installing old ruby version (2.4.0) in Docker:
> 
> Solution:
> 
> ```
> rvm pkg install openssl
> rvm install 2.4.0 -C --with-openssl-dir=/usr/local/rvm/usr
> ```

this solution works for me, 
but i tried different location of openssl: 
```rvm install 2.6.6 -C --with-openssl-dir=/home/myuser/.rvm/usr```
because install openssl log throw this:
```
Extracting openssl to /home/myuser/.rvm/src/openssl-1.0.1i.....
Configuring openssl in /home/myuser/.rvm/src/openssl-1.0.1i...................................
Compiling openssl in /home/myuser/.rvm/src/openssl-1.0.1i....................................................................................................................................................
Installing openssl to /home/myuser/.rvm/usr.................................................................................................................................................
................................
```
