### ISSUE TITLE
Error Installing Ruby 2.6.6 on Big Sur 11.2.3

### ISSUE THREAD

**Issue by sheef-code** [rvm/rvm#5069]
## Description
Trying to install ruby 2.6.6 on rvm version 1.29.12-next but results into error.

## Steps to reproduce
```rvm install 2.6.6```

## Result of running command 
<img width="940" alt="Screen Shot 2021-04-14 at 5 53 43 PM" src="https://user-images.githubusercontent.com/43546293/114799385-59869680-9d4c-11eb-8d38-c7e8d2b0b171.png">

## Install Log 
```
+__rvm_make:0> make install
./revision.h unchanged
generating -darwin20-fake.rb
-darwin20-fake.rb updated
	BASERUBY = /usr/bin/ruby --disable=gems
	CC = gcc
	LD = ld
	LDSHARED = gcc -dynamiclib
	CFLAGS = -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens   -fno-common -pipe 
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -DCANONICALIZATION_FOR_MATHN
	CPPFLAGS = -I/opt/homebrew/opt/libyaml/include -I/opt/homebrew/opt/libksba/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/openssl@1.1/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I.ext/include/-darwin20 -I./include -I. -I./enc/unicode/12.1.0 
	DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/libksba/lib -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/zlib/lib -L/opt/homebrew/opt/openssl@1.1/lib -install_name /Users/shifathsalam/.rvm/rubies/ruby-2.6.6/lib/libruby.2.6.dylib -compatibility_version 2.6 -current_version 2.6.6  -fstack-protector-strong -framework Security -framework Foundation  -fstack-protector-strong -framework Security -framework Foundation  
	SOLIBS = -lpthread -ldl -lobjc
	LANG = en_US.UTF-8
	LC_ALL = 
	LC_CTYPE = 
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: arm64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
generating enc.mk
making srcs under enc
make[1]: Nothing to be done for `srcs'.
generating transdb.h
transdb.h unchanged
generating makefiles ext/configure-ext.mk
ext/configure-ext.mk updated
generating makefile exts.mk
exts.mk updated
./revision.h unchanged
*** Following extensions are not compiled:
syslog:
	Could not be configured. It will not be installed.
	Check ext/syslog/mkmf.log for more details.
gdbm:
	Could not be configured. It will not be installed.
	Check ext/gdbm/mkmf.log for more details.
pty:
	Could not be configured. It will not be installed.
	Check ext/pty/mkmf.log for more details.
digest/rmd160:
	Could not be configured. It will not be installed.
	Check ext/digest/rmd160/mkmf.log for more details.
digest/sha1:
	Could not be configured. It will not be installed.
	Check ext/digest/sha1/mkmf.log for more details.
digest/sha2:
	Could not be configured. It will not be installed.
	Check ext/digest/sha2/mkmf.log for more details.
date:
	Could not be configured. It will not be installed.
	Check ext/date/mkmf.log for more details.
readline:
	Could not be configured. It will not be installed.
	Check ext/readline/mkmf.log for more details.
io/console:
	Could not be configured. It will not be installed.
	Check ext/io/console/mkmf.log for more details.
io/nonblock:
	Could not be configured. It will not be installed.
	Check ext/io/nonblock/mkmf.log for more details.
io/wait:
	Could not be configured. It will not be installed.
	Check ext/io/wait/mkmf.log for more details.
etc:
	Could not be configured. It will not be installed.
	Check ext/etc/mkmf.log for more details.
fiddle:
	Could not be configured. It will not be installed.
	Check ext/fiddle/mkmf.log for more details.
zlib:
	Could not be configured. It will not be installed.
	Check ext/zlib/mkmf.log for more details.
json/parser:
	Could not be configured. It will not be installed.
	Check ext/json/parser/mkmf.log for more details.
racc/cparse:
	Could not be configured. It will not be installed.
	Check ext/racc/cparse/mkmf.log for more details.
rbconfig/sizeof:
	Could not be configured. It will not be installed.
	Check ext/rbconfig/sizeof/mkmf.log for more details.
dbm:
	Could not be configured. It will not be installed.
	Check ext/dbm/mkmf.log for more details.
openssl:
	Could not be configured. It will not be installed.
	Check ext/openssl/mkmf.log for more details.
socket:
	Could not be configured. It will not be installed.
	Check ext/socket/mkmf.log for more details.
*** Fix the problems, then remove these directories and try again if you want.
making enc
make[1]: Nothing to be done for `enc'.
making trans
make[1]: Nothing to be done for `./enc/trans'.
making encs
make[1]: Nothing to be done for `encs'.
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./-darwin20-fake ./tool/rbinstall.rb --make="/Library/Developer/CommandLineTools/usr/bin/make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
/Users/shifathsalam/.rvm/src/ruby-2.6.6/.ext/common/digest.rb:16:in `const_missing': library not found for class Digest::SHA512 -- digest/sha2.so (LoadError)
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/security.rb:349:in `<module:Security>'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/security.rb:332:in `<top (required)>'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/package.rb:44:in `<top (required)>'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/installer.rb:11:in `<top (required)>'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./tool/rbinstall.rb:707:in `<module:RbInstall>'
	from ./tool/rbinstall.rb:643:in `<main>'
/Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- digest/sha2.so (LoadError)
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/.ext/common/digest.rb:17:in `const_missing'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/security.rb:349:in `<module:Security>'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/security.rb:332:in `<top (required)>'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/package.rb:44:in `<top (required)>'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/installer.rb:11:in `<top (required)>'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shifathsalam/.rvm/src/ruby-2.6.6/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./tool/rbinstall.rb:707:in `<module:RbInstall>'
	from ./tool/rbinstall.rb:643:in `<main>'
make: *** [do-install-nodoc] Error 1
+__rvm_make:0> return 2
```

**Comment by BenjiLewis** [comment]
I'm not sure if this will help... But i've had a similar issue bundling with 2.6.6 on Big Sur. 

Ensure you have `openssl@1.1`. if not, install it using `brew install openssl@1.1`.
Add `openssl@1.1` to your path, something like this in your `.zshrc`: 
```
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"`
```
And then re-install ruby 2.6.6.

**Comment by mayur-kambariya** [comment]
1) Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
2) Uninstall Homebrew
  ```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
  rm -rf /opt/homebrew/*
  sudo rm -rf /opt/homebrew
```
3) Reinstall Homebrew
  `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
4) Restart terminal
5) Check Homebrew is working fine: `brew doctor`
6) Reinstall openssl: `brew install openssl`
7) Install Ruby: `rvm install 2.7` Or any version

**Comment by walterdavis** [comment]
In a recent quest to get my M1 to properly host an old app that I didn't want to upgrade, I tried to delete and re-install an old Intel copy of 2.6.6 that was left over by Migration Assistant. I finally came across this advice, which helped me install it to the point where it worked properly to run migrations in that project, and host locally. The production server still runs 2.6.6 and yes, I know that's old and busted. 

```sh
export optflags="-Wno-error=implicit-function-declaration"; export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"; export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"; export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig" | rvm install 2.6.6
```

The install proceeded without a hitch, and everything works perfectly on my M1 Max laptop. But when I do `rvm list`, I see this:

```sh
   ruby-1.9.1-p431 [ i386 ]
   ruby-1.9.3-p551 [ x86_64 ]
   ruby-2.4.6 [ x86_64 ]
   ruby-2.5.1 [ x86_64 ]
   ruby-2.6.5 [ x86_64 ]
 * ruby-2.6.6 [ broken ]
   ruby-2.7.2 [ x86_64 ]
=> ruby-2.7.4 [ arm64 ]
   ruby-3.0.0 [ x86_64 ]
```

I reinstalled twice to see if anything changed, and it did not. Can you explain what "broken" means in this context? I've never seen this before, despite using RVM since it was first released.

Thanks!

**Comment by kahinJunio** [comment]
rvm install 2.6.6 --with-out-ext=fiddle solved for me than later use rvm use 2.6.6

**Comment by amitk-vmware** [comment]
check where your openssl@1.1 is installed by:
`brew --prefix openssl@1.1`

After that set the following flags, based on your OpenSSL installation destination:
```text
echo 'export PATH="/usr/local/opt/openssl@1.1/1.1.1m/bin:$PATH"' >> ~/.zshrc
export LDFLAGS="-L/usr/local/opt/openssl@1.1/1.1.1m/lib"
export CPPFLAGS="-I/usr/local/Cellar/openssl@1.1/1.1.1m/include"
export PKG_CONFIG_PATH="/usr/local/Cellar/openssl@1.1/1.1.1m/lib/pkgconfig"
source ~/.zshrc
rvm autolibs disable
export RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC
export optflags="-Wno-error=implicit-function-declaration"
rvm install 2.5.7 --with-openssl-dir=/usr/local/Cellar/openssl@1.1/1.1.1m/
```

After trying multiple solutions this has worked for me in the end.
