### ISSUE TITLE
Permission denied installing 3.1.2 on M1 Monterey 12.3.1 rvm 1.29.12-next

### ISSUE THREAD

**Issue by gisborne** [rvm/rvm#5213]
`rvm install 3.1.2` fails with "Error running '__rvm_make install',
please read /Users/gisborne/.rvm/log/1651737903_ruby-3.1.2/install.log"

This log ends with

```installing extension headers:       /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/Users/gisborne/.rvm/rubies/ruby-3.1.2/include/ruby-3.1.0/arm64-darwin21
/Users/gisborne/.rvm/src/ruby-3.1.2/lib/fileutils.rb:240:in `mkdir': Permission denied @ dir_s_mkdir - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/Users (Errno::EACCES)
        from /Users/gisborne/.rvm/src/ruby-3.1.2/lib/fileutils.rb:240:in `fu_mkdir'
        from /Users/gisborne/.rvm/src/ruby-3.1.2/lib/fileutils.rb:221:in `block (2 levels) in mkdir_p'
        from /Users/gisborne/.rvm/src/ruby-3.1.2/lib/fileutils.rb:219:in `reverse_each'
        from /Users/gisborne/.rvm/src/ruby-3.1.2/lib/fileutils.rb:219:in `block in mkdir_p'
        from /Users/gisborne/.rvm/src/ruby-3.1.2/lib/fileutils.rb:211:in `each'
        from /Users/gisborne/.rvm/src/ruby-3.1.2/lib/fileutils.rb:211:in `mkdir_p'
        from ./tool/rbinstall.rb:218:in `makedirs'
        from ./tool/rbinstall.rb:331:in `prepare'
        from ./tool/rbinstall.rb:432:in `block in <main>'
        from ./tool/rbinstall.rb:1127:in `block in <main>'
        from ./tool/rbinstall.rb:1124:in `each'
        from ./tool/rbinstall.rb:1124:in `<main>'
make: *** [do-install-nodoc] Error 1
+__rvm_make:0> return 2```

## Steps to reproduce

See above. I am using M1 Monterey 12.3.1 rvm 1.29.12-next

## Expected behavior

Ruby 3.1.2 installs

## Actual behavior

See above.

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

<!-- When the above output does not seem to include a meaningful error message, you might want to additionally attach the output of the same command(s) run with the `--debug` switch. -->

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info

<!-- Paste below the output of the `rvm info` command. -->

**Comment by btrewern** [comment]
It seems odd but if you remove your installation via `rvm implode` or similar then reinstall rvm and the first time you do

`rvm install 3.1.2`

it works.

Not sure what is happening but this has helped me.

**Comment by pavanscs** [comment]
no it will not work please don't try this

**Comment by btrewern** [comment]
This did work at the time, I tried it more than once.  Don't do it if you have other rubies installed but if you do need to get 3.1.2 installed it was a possible work around.

**Comment by KostyaSha** [comment]
`rvm implode ` didn't help.

**Comment by KostyaSha** [comment]
I think this issue is described here https://bugs.ruby-lang.org/issues/19403 and fixed in 3.1.4
