### ISSUE TITLE
Ruby 3.2.0 won't run

### ISSUE THREAD

**Issue by jzakiya** [rvm/rvm#5286]
Installed 3.2.0 yesterday (multiple times) on PCLinuxOS (PCLOS).
When I start with `irb` or try `gem update` get this output.

```
  ~ ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]
➜  ~ irb
Ignoring bigdecimal-3.1.3 because its extensions are not built. Try: gem pristine bigdecimal --version 3.1.3
Ignoring cgi-0.3.6 because its extensions are not built. Try: gem pristine cgi --version 0.3.6
Ignoring date-3.3.3 because its extensions are not built. Try: gem pristine date --version 3.3.3
Ignoring debug-1.7.0 because its extensions are not built. Try: gem pristine debug --version 1.7.0
Ignoring digest-3.1.1 because its extensions are not built. Try: gem pristine digest --version 3.1.1
Ignoring erb-4.0.2 because its extensions are not built. Try: gem pristine erb --version 4.0.2
Ignoring etc-1.4.2 because its extensions are not built. Try: gem pristine etc --version 1.4.2
Ignoring fcntl-1.0.2 because its extensions are not built. Try: gem pristine fcntl --version 1.0.2
Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
Ignoring fiddle-1.1.1 because its extensions are not built. Try: gem pristine fiddle --version 1.1.1
Ignoring io-console-0.6.0 because its extensions are not built. Try: gem pristine io-console --version 0.6.0
Ignoring io-nonblock-0.2.0 because its extensions are not built. Try: gem pristine io-nonblock --version 0.2.0
Ignoring io-wait-0.3.0 because its extensions are not built. Try: gem pristine io-wait --version 0.3.0
Ignoring json-2.6.3 because its extensions are not built. Try: gem pristine json --version 2.6.3
Ignoring nio4r-2.5.8 because its extensions are not built. Try: gem pristine nio4r --version 2.5.8
Ignoring openssl-3.0.1 because its extensions are not built. Try: gem pristine openssl --version 3.0.1
Ignoring pathname-0.2.1 because its extensions are not built. Try: gem pristine pathname --version 0.2.1
Ignoring psych-5.0.1 because its extensions are not built. Try: gem pristine psych --version 5.0.1
Ignoring puma-6.0.0 because its extensions are not built. Try: gem pristine puma --version 6.0.0
Ignoring racc-1.6.1 because its extensions are not built. Try: gem pristine racc --version 1.6.1
Ignoring rbs-2.8.1 because its extensions are not built. Try: gem pristine rbs --version 2.8.1
Ignoring readline-ext-0.1.5 because its extensions are not built. Try: gem pristine readline-ext --version 0.1.5
<internal:/home/jzakiya/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': libruby.so.3.1: cannot open shared object file: No such file or directory - /home/jzakiya/.rvm/gems/ruby-3.2.0/gems/io-console-0.6.0/lib/io/console.so (LoadError)
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/jzakiya/.rvm/gems/ruby-3.2.0/gems/reline-0.3.2/lib/reline.rb:1:in `<top (required)>'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/jzakiya/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/irb.rb:13:in `<top (required)>'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/jzakiya/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:9:in `<top (required)>'
        from /home/jzakiya/.rvm/gems/ruby-3.2.0/bin/irb:25:in `load'
        from /home/jzakiya/.rvm/gems/ruby-3.2.0/bin/irb:25:in `<main>'
        from /home/jzakiya/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `eval'
        from /home/jzakiya/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `<main>'
➜  ~ 


```

**Comment by duffyjp** [comment]
Do you have whatever the PCLinuxOS equivalent to Ubuntu's `build-essential` package installed?

**Comment by jzakiya** [comment]
I looked here - https://packages.ubuntu.com/bionic/build-essential

to see what it included, shown below.  PCLOS is not based on Ubuntu|Debian.

PCLOS has:

gcc, g++ : 12.2.1

glibc, glibc-devel: 2.36

make: 1:4.4

This problem only occurs with `Ruby-3.2.0`, as all those < 3.2.0 were upgraded without problems.

I also upgraded to `jruby-9.4.0.0` and `truffleruby-22.3.0` with no problem, so whatever it is it's unique to 3.2.0.

**Comment by mathieujobin** [comment]
how about 3.2.1 ?

**Comment by jzakiya** [comment]
```
➜  ~ rvm list
Warning! PATH is not properly set up, /home/jzakiya/.rvm/gems/ruby-3.2.1/bin is not at first place.
         Usually this is caused by shell initialization files. Search for PATH=... entries.
         You can also re-add RVM to your profile by running: rvm get stable --auto-dotfiles
         To fix it temporarily in this shell session run: rvm use ruby-3.2.1
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
   jruby-9.4.1.0 [ x86_64 ]
=* ruby-3.2.1 [ x86_64 ]
   truffleruby-22.3.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

➜  ~ ruby -v
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-linux]
➜  ~ irb
Ignoring bigdecimal-3.1.3 because its extensions are not built. Try: gem pristine bigdecimal --version 3.1.3
Ignoring cgi-0.3.6 because its extensions are not built. Try: gem pristine cgi --version 0.3.6
Ignoring date-3.3.3 because its extensions are not built. Try: gem pristine date --version 3.3.3
Ignoring debug-1.7.0 because its extensions are not built. Try: gem pristine debug --version 1.7.0
Ignoring digest-3.1.1 because its extensions are not built. Try: gem pristine digest --version 3.1.1
Ignoring erb-4.0.2 because its extensions are not built. Try: gem pristine erb --version 4.0.2
Ignoring etc-1.4.2 because its extensions are not built. Try: gem pristine etc --version 1.4.2
Ignoring fcntl-1.0.2 because its extensions are not built. Try: gem pristine fcntl --version 1.0.2
Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
Ignoring fiddle-1.1.1 because its extensions are not built. Try: gem pristine fiddle --version 1.1.1
Ignoring io-console-0.6.0 because its extensions are not built. Try: gem pristine io-console --version 0.6.0
Ignoring io-nonblock-0.2.0 because its extensions are not built. Try: gem pristine io-nonblock --version 0.2.0
Ignoring io-wait-0.3.0 because its extensions are not built. Try: gem pristine io-wait --version 0.3.0
Ignoring json-2.6.3 because its extensions are not built. Try: gem pristine json --version 2.6.3
Ignoring nio4r-2.5.8 because its extensions are not built. Try: gem pristine nio4r --version 2.5.8
Ignoring openssl-3.0.1 because its extensions are not built. Try: gem pristine openssl --version 3.0.1
Ignoring pathname-0.2.1 because its extensions are not built. Try: gem pristine pathname --version 0.2.1
Ignoring psych-5.0.1 because its extensions are not built. Try: gem pristine psych --version 5.0.1
Ignoring puma-6.0.0 because its extensions are not built. Try: gem pristine puma --version 6.0.0
Ignoring racc-1.6.1 because its extensions are not built. Try: gem pristine racc --version 1.6.1
Ignoring rbs-2.8.1 because its extensions are not built. Try: gem pristine rbs --version 2.8.1
Ignoring readline-ext-0.1.5 because its extensions are not built. Try: gem pristine readline-ext --version 0.1.5
<internal:/home/jzakiya/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require': libruby.so.3.1: cannot open shared object file: No such file or directory - /home/jzakiya/.rvm/gems/ruby-3.2.1/gems/io-console-0.6.0/lib/io/console.so (LoadError)
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from /home/jzakiya/.rvm/gems/ruby-3.2.1/gems/reline-0.3.2/lib/reline.rb:1:in `<top (required)>'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from /home/jzakiya/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/irb.rb:13:in `<top (required)>'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from <internal:/home/jzakiya/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
        from /home/jzakiya/.rvm/rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:9:in `<top (required)>'
        from /home/jzakiya/.rvm/gems/ruby-3.2.1/bin/irb:25:in `load'
        from /home/jzakiya/.rvm/gems/ruby-3.2.1/bin/irb:25:in `<main>'
        from /home/jzakiya/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `eval'
        from /home/jzakiya/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `<main>'
➜  ~ 
```

**Comment by jzakiya** [comment]
I had to uninstall all the ruby-3.x,y versions I had, then was able to install 3.2.2 and all the errors seem to have gone away.
It installed and runs now, including fixing all the issues it had with gems. So after 3 months (since Dec 25, 2022) I can run 3.2

Thanks for finally fixing this. :-)
