### ISSUE TITLE
Errors with OpenSSL and zlib on MacOS Sonoma 14.4 M2 when installing ruby 3.3.0

### ISSUE THREAD

**Issue by llenodo** [rvm/rvm#5448]
## Description

Errors with OpenSSL and zlib trying to install ruby 3.3.0 on an M2 mac running MacOS Sonoma 14.4. 

## Steps to reproduce

`rvm install 3.3.0`

## Expected behavior

`rvm install 3.3.0` works

## Actual behavior

First I got the openssl error:

```
# console output
Error running '__rvm_make -j12',

# make.log output 
openssl_missing.c:24:13: error: incomplete definition of type 'struct X509_crl_st'
        *psig = crl->signature;
                ~~~^
/usr/local/Cellar/openssl@3/3.2.1/include/openssl/types.h:162:16: note: forward declaration of 'struct X509_crl_st'
typedef struct X509_crl_st X509_CRL;
               ^
openssl_missing.c:26:13: error: incomplete definition of type 'struct X509_crl_st'
        *palg = crl->sig_alg;
                ~~~^
/usr/local/Cellar/openssl@3/3.2.1/include/openssl/types.h:162:16: note: forward declaration of 'struct X509_crl_st'
typedef struct X509_crl_st X509_CRL;
               ^
openssl_missing.c:36:13: error: incomplete definition of type 'struct X509_req_st'
        *psig = req->signature;
                ~~~^
/usr/local/Cellar/openssl@3/3.2.1/include/openssl/x509.h:283:16: note: forward declaration of 'struct X509_req_st'
typedef struct X509_req_st X509_REQ;
               ^
openssl_missing.c:38:13: error: incomplete definition of type 'struct X509_req_st'
        *palg = req->sig_alg;
                ~~~^
/usr/local/Cellar/openssl@3/3.2.1/include/openssl/x509.h:283:16: note: forward declaration of 'struct X509_req_st'
typedef struct X509_req_st X509_REQ;
               ^
```

This was able to be resolved by adding `--with-openssl-dir=/usr/local/opt/openssl@1.1` 

After that, I encountered errors with zlib:

```
# console output
'command gem pristine --extensions debug --version 1.9.1 racc --version 1.7.3 rbs --version 3.4.0' failed, you need to fix these gems manually.
.
Error running '__rvm_with ruby-3.3.0@global gemset_pristine',
please read /Users/llenodo/.rvm/log/1710811018_ruby-3.3.0/gemset.pristine-ruby-3.3.0@global.log

# gemset.pristine-ruby-3.3.0@global.log output
++ gem pristine --extensions debug --version 1.9.1
<internal:/Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require': cannot load such file -- zlib (LoadError)
	from <internal:/Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/package.rb:197:in `initialize'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/package.rb:162:in `new'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/package.rb:162:in `new'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/installer.rb:114:in `at'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/commands/pristine_command.rb:197:in `block in execute'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/commands/pristine_command.rb:133:in `each'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/commands/pristine_command.rb:133:in `execute'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/command_manager.rb:254:in `invoke_command'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/command_manager.rb:193:in `process_args'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/command_manager.rb:151:in `run'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
	from /Users/llenodo/.rvm/rubies/ruby-3.3.0/bin/gem:12:in `<main>'
++ _failed+=("${_gem} --version ${_version}")
```

Resolved by adding both the `arch -x86_64` and `--with-zlib-dir=$(brew --prefix zlib)` flags

## Environment info
ruby-3.3.0:

  system:
    uname:        "Darwin llenodos-macbook-pro.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:45:49 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6020 arm64"
    name:         "OSX"
    version:      "14.4"
    architecture: "arm64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)"
    zsh:          "/bin/zsh => zsh 5.9 (x86_64-apple-darwin23.0)"
    remote_path:  "osx/14.4/arm64"
    xcode:        "15.3"

  rvm:
    version:      "1.29.12-next (master)"
    updated:      "16 hours 45 minutes 29 seconds ago"
    path:         "/Users/llenodo/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

**Comment by llenodo** [comment]
I was able to finally get this installed by runnign the following command:

`arch -x86_64 rvm reinstall 3.3.0 --with-openssl-dir=/usr/local/opt/openssl@1.1 --with-zlib-dir=$(brew --prefix zlib)`

**Comment by HarlemSquirrel** [comment]
I was able to install on M3 Pro MacBook Pro running 14.3 like so
```
rvm install 3.2.3 --with-openssl-dir=/usr/local/opt/openssl@1.1
```

**Comment by JsonKit** [comment]
https://rvm_io.global.ssl.fastly.net can not be visited

**Comment by JsonKit** [comment]
![image](https://github.com/rvm/rvm/assets/14355698/d157ce82-816c-40cf-93d3-78f10b9d4e95)

**Comment by darkBuddha** [comment]
i am also affected
