### ISSUE TITLE
The compiler in required packages and the compiler for pre-built binaries mismatch

### ISSUE THREAD

**Issue by nobu** [rvm/rvm#5502]
## Description

From https://github.com/rubygems/rubygems/issues/8015
> When users use pre-compiled ruby provided by rvm, some issues happend with compiler flag differences.
> 
> https://ml.ruby-lang.org/archives/list/ruby-talk@ml.ruby-lang.org/message/OI3BLGJEEZHEFHAYMCNU7AM5BV465R6T/
> https://github.com/rubygems/rubygems/issues/1508#issuecomment-2336873801
> https://github.com/ruby/bigdecimal/issues/297#issuecomment-2328928055
> gcc: error: unrecognized command line option ‘-fdeclspec’
> gcc: error: unrecognized command line option ‘-Wextra-tokens’; did you mean ‘-Wextra-semi’?
> gcc: error: unrecognized command line option ‘-Wdivision-by-zero’; did you mean ‘-Wdiv-by-zero’?
> gcc: error: unrecognized command line option ‘-Wshorten-64-to-32’
>  extconf.rb or RubyGems build toolchain use RbConfig::CONFIG by pre-compiled binary built by clang. But it's not working with gcc.

These options are for `clang` but not for `gcc`.

### Cause

`rvm install` does install required packages, including `gcc`.

```shell-session
ubuntu@diverting-whistler:~$ rvm install 3.3.4 --binary
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/22.04/x86_64/ruby-3.3.4.tar.bz2
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system...
Installing required packages: bzip2, g++, gcc, autoconf, automake, bison, libc6-dev, libffi-dev, libgdbm-dev, libncurses5-dev, libsqlite3-dev, libtool, libyaml-dev, make, pkg-config, sqlite3, zlib1g-dev, libgmp-dev, libreadline-dev, libssl-dev................................
Requirements installation successful.
```

However, the binary to be installed is compiled with `clang`.

```shell-session
$ curl -sSL https://rubies.travis-ci.org/ubuntu/22.04/x86_64/ruby-3.3.4.tar.bz2 | tar -Oxj --wildcards '*/rbconfig.rb' | grep --F 'CONFIG["CC"]'
  CONFIG["CC"] = "clang"
```

If `clang` is not installed at this time, `__rvm_fix_gcc_path()` in scripts/functions/build replaces `CONFIG["CC"]` line with `CONFIG["CC"] = ENV["CC"] || "/usr/bin/gcc"` (`/usr/bin/gcc` is found since `rvm install` installed it).

This script replaces only `CC`, but `CFLAGS` is unchanged and results in the above mismatch.

### Resolution

The package installed by `rvm install` and the package used to build pre-built binaries should match.

## Steps to reproduce

https://github.com/rubygems/rubygems/issues/8015#issuecomment-2343997197
> 1. Install rvm 1.29.12
>
> 2. Install ruby 3.3.4
> 
> 3. Install [bigdecimal](https://github.com/ruby/bigdecimal) gem
> 
>    ```
>    gem install bigdecimal
>    ```

## Expected behavior

Succeed to install extension libraries.

```shell-session
$ gem install bigdecimal
Building native extensions. This could take a while...
Successfully installed bigdecimal-3.1.8
Parsing documentation for bigdecimal-3.1.8
Installing ri documentation for bigdecimal-3.1.8
Done installing documentation for bigdecimal after 0 seconds
1 gem installed
```

## Actual behavior

Fail to install extension libraries.

```shell-session
$ gem install bigdecimal
Fetching bigdecimal-3.1.8.gem
Building native extensions. This could take a while...
ERROR:  Error installing bigdecimal:
	ERROR: Failed to build gem native extension.

    current directory: /home/ubuntu/.rvm/gems/ruby-3.3.4/gems/bigdecimal-3.1.8/ext/bigdecimal
/home/ubuntu/.rvm/rubies/ruby-3.3.4/bin/ruby extconf.rb
checking for __builtin_clz()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include=${opt-dir}/include
	--without-opt-include
	--with-opt-lib=${opt-dir}/lib
	--without-opt-lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/ubuntu/.rvm/rubies/ruby-3.3.4/bin/$(RUBY_BASE_NAME)
/home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:480:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

	from /home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:606:in `block in try_compile'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:555:in `with_werror'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:606:in `try_compile'
	from extconf.rb:6:in `block in have_builtin_func'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:983:in `block in checking_for'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:344:in `block (2 levels) in postpone'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:314:in `open'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:344:in `block in postpone'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:314:in `open'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:340:in `postpone'
	from /home/ubuntu/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/mkmf.rb:982:in `checking_for'
	from extconf.rb:5:in `have_builtin_func'
	from extconf.rb:18:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ubuntu/.rvm/gems/ruby-3.3.4/extensions/x86_64-linux/3.3.0/bigdecimal-3.1.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/ubuntu/.rvm/gems/ruby-3.3.4/gems/bigdecimal-3.1.8 for inspection.
Results logged to /home/ubuntu/.rvm/gems/ruby-3.3.4/extensions/x86_64-linux/3.3.0/bigdecimal-3.1.8/gem_make.out

A new release of RubyGems is available: 3.5.11 → 3.5.18!
Run `gem update --system 3.5.18` to update your installation.
```

## Environment info

```
ruby-3.3.4:

  system:
    uname:        "Linux unruffled-chamois 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "22.04"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/22.04/x86_64"

  rvm:
    version:      "1.29.12 (latest)"
    updated:      "27 minutes 46 seconds ago"
    path:         "/home/ubuntu/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "3.3.4"
    date:         "2024-07-09"
    platform:     "x86_64-linux"
    patchlevel:   "2024-07-09 revision be1089c8ec"
    full_version: "ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]"

  homes:
    gem:          "/home/ubuntu/.rvm/gems/ruby-3.3.4"
    ruby:         "/home/ubuntu/.rvm/rubies/ruby-3.3.4"

  binaries:
    ruby:         "/home/ubuntu/.rvm/rubies/ruby-3.3.4/bin/ruby"
    irb:          "/home/ubuntu/.rvm/rubies/ruby-3.3.4/bin/irb"
    gem:          "/home/ubuntu/.rvm/rubies/ruby-3.3.4/bin/gem"
    rake:         "/home/ubuntu/.rvm/rubies/ruby-3.3.4/bin/rake"

  environment:
    PATH:         "/home/ubuntu/.rvm/gems/ruby-3.3.4/bin:/home/ubuntu/.rvm/gems/ruby-3.3.4@global/bin:/home/ubuntu/.rvm/rubies/ruby-3.3.4/bin:/home/ubuntu/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    GEM_HOME:     "/home/ubuntu/.rvm/gems/ruby-3.3.4"
    GEM_PATH:     "/home/ubuntu/.rvm/gems/ruby-3.3.4:/home/ubuntu/.rvm/gems/ruby-3.3.4@global"
    MY_RUBY_HOME: "/home/ubuntu/.rvm/rubies/ruby-3.3.4"
    IRBRC:        "/home/ubuntu/.rvm/rubies/ruby-3.3.4/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by nobu** [comment]
Not only `CFLAGS`, also config.h should contain compiler specific info.
Using a different compiler can't work.

**Comment by ur5us** [comment]
Just ran into the same issue. For anyone looking for a fix for the time being, you have to force RVM to compile Ruby on your system by using the `--disable-binary` flag, e.g. `rvm install 3.3.5 --disable-binary`. Sadly, the flag is not documented on the site nor in the help for the `install` command.

**Comment by jharrell26** [comment]
Same issue for me. Worked around by installing clang `sudo apt install clang`

Why did this suddenly stop working? I built a server a couple of months ago and didn't hit this issue.
