### ISSUE TITLE
Install of ruby 3.3 (3.3.5) on AlmaLinux 8, perhaps EL8 generally, results in a broken psych gem ("cannot load such file" on require), despite libyaml being installed

### ISSUE THREAD

**Issue by anjumjfax** [rvm/rvm#5514]
## Description

When using Ruby 3.3 installed with RVM on AlmaLinux 8, the psych gem is broken. This becomes immediately clear when just using basic tools like gem or bundler, which quickly errors out with,

```
$ gem install foo
<internal:/home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- psych (LoadError)
	from <internal:/home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems.rb:594:in `load_yaml'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:1240:in `_load'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/safe_marshal/visitors/to_ruby.rb:351:in `call_method'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/safe_marshal/visitors/to_ruby.rb:182:in `visit_Gem_SafeMarshal_Elements_UserDefined'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/safe_marshal/visitors/visitor.rb:6:in `visit'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/safe_marshal/visitors/to_ruby.rb:28:in `visit'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/safe_marshal.rb:71:in `load'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/safe_marshal.rb:61:in `safe_load'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/source.rb:162:in `fetch_spec'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/resolver/api_specification.rb:93:in `spec'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/resolver/installer_set.rb:99:in `add_always_install'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/dependency_installer.rb:318:in `resolve_dependencies'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/commands/install_command.rb:198:in `install_gem'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/commands/install_command.rb:223:in `block in install_gems'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/commands/install_command.rb:216:in `each'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/commands/install_command.rb:216:in `install_gems'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/commands/install_command.rb:162:in `execute'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/command.rb:326:in `invoke_with_build_args'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/command_manager.rb:255:in `invoke_command'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/command_manager.rb:194:in `process_args'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/command_manager.rb:152:in `run'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/gem_runner.rb:56:in `run'
	from /home/anjum/.rvm/rubies/ruby-3.3.5/bin/gem:12:in `<main>'
```

But can be more precisely reproduced by indeed just requiring psych alone.

```
$ ruby -e "require 'psych'"
<internal:/home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- psych (LoadError)
	from <internal:/home/anjum/.rvm/rubies/ruby-3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from -e:1:in `<main>'
```

I've seen something like this issue before, and I know that it's fixed by installing the system pack libyaml, `dnf install libyaml`. But that's already installed. 

```
# dnf install libyaml
Last metadata expiration check: 1:17:01 ago on Tue 05 Nov 2024 10:32:30 AM UTC.
Package libyaml-0.1.7-5.el8.x86_64 is already installed.
Package libyaml-0.1.7-5.el8.i686 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```
## Steps to reproduce

 1. Setup AlmaLinux 8 in a virtual machine.
 2. Install RVM using ordinary instructions, getting the GPG key and then curl-and-pipe into bash
 3. Run `source ~/.rvm/scripts/rvm`
 4. Run `rvm install ruby-3.3.5'
 5. Run `ruby -e "require 'psych'"`

## Expected behavior

It should not error, the output should be silent.

## Actual behavior

It errors with "cannot load such file -- psych"

## Environment info

Environment,

```
# uname -a
Linux hostname 4.18.0-425.13.1.el8_7.x86_64 #1 SMP Tue Feb 21 04:20:52 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rwaffen** [comment]
Same here with RHEL 8.8 and ruby 3.3.5.
3.1.2 is working. This was an older ruby i had install in the past.

**Comment by rwaffen** [comment]
same psych problem occurs also when i try to install ruby-3.2.5.

**Comment by rwaffen** [comment]
3.3.6 seems to work again.

**Comment by rwaffen** [comment]
ruby 3.3.6 looks a bit better, but also has issues with psych

**Comment by anjumjfax** [comment]
I was just about to say, I still have an issue with psych on ruby 3.3.6 installed with rvm, which as far as I'm aware is the whole issue so not sure what is meant by working again.

**Comment by vicomte** [comment]
You'll need to enable the [powertools in 8/crb in 9] repo to get libyaml-devel, it was removed from the base repo as ruby used to include source for libyaml and doesn't anymore.

**Comment by rwaffen** [comment]
thx for the hint, gonna try that...
